DELETE FROM permissions WHERE code IN (
    'CUSTOMERS_READ', 'CUSTOMERS_WRITE',
    'SERVICES_READ', 'SERVICES_WRITE',
    'PERFUMES_READ', 'PERFUMES_WRITE',
    'ORDERS_READ', 'ORDERS_CREATE', 'ORDERS_UPDATE', 'ORDERS_CANCEL',
    'PAYMENTS_READ', 'PAYMENTS_RECORD',
    'EXPENSES_READ', 'EXPENSES_WRITE',
    'REPORTS_READ', 'RECEIPTS_MANAGE', 'AUDIT_READ'
);
