ALTER TABLE orders
    ADD COLUMN customer_name_snapshot TEXT,
    ADD COLUMN customer_phone_snapshot TEXT,
    ADD COLUMN receipt_qr_id TEXT;

-- Preserve every existing order and capture the currently related customer
-- values explicitly before making the name snapshot mandatory.
UPDATE orders o
SET customer_name_snapshot=c.name,
    customer_phone_snapshot=c.phone
FROM customers c
WHERE c.business_id=o.business_id AND c.id=o.customer_id;

UPDATE orders
SET receipt_qr_id=gen_random_uuid()::text
WHERE receipt_qr_id IS NULL;

ALTER TABLE orders
    ALTER COLUMN customer_name_snapshot SET NOT NULL,
    ALTER COLUMN receipt_qr_id SET NOT NULL,
    ALTER COLUMN receipt_qr_id SET DEFAULT gen_random_uuid()::text;

CREATE UNIQUE INDEX orders_receipt_qr_id_uq ON orders (receipt_qr_id);

CREATE FUNCTION snapshot_order_customer_for_receipt()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT c.name, c.phone
    INTO NEW.customer_name_snapshot, NEW.customer_phone_snapshot
    FROM customers c
    WHERE c.business_id=NEW.business_id AND c.id=NEW.customer_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'order customer does not exist in the same business'
            USING ERRCODE='23503';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER orders_receipt_customer_snapshot_before_insert
    BEFORE INSERT ON orders
    FOR EACH ROW
    EXECUTE FUNCTION snapshot_order_customer_for_receipt();

COMMENT ON COLUMN orders.customer_name_snapshot IS
    'Customer display name captured when the order was received; receipts never resolve historical customer identity through the mutable customer row.';
COMMENT ON COLUMN orders.customer_phone_snapshot IS
    'Optional customer phone captured when the order was received for receipt sharing; not refreshed from later customer edits.';
COMMENT ON COLUMN orders.receipt_qr_id IS
    'Opaque non-authorizing QR locator generated by PostgreSQL; lookup still requires authentication and current order authorization.';
COMMENT ON INDEX orders_receipt_qr_id_uq IS
    'Globally unique opaque receipt QR locator; it is not a credential or a substitute for authorization.';
