// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for TokenPairTokenType.
const (
	Bearer TokenPairTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenPairTokenType enum.
func (e TokenPairTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	ADMIN        UserRole = "ADMIN"
	LAUNDRYSTAFF UserRole = "LAUNDRY_STAFF"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case ADMIN:
		return true
	case LAUNDRYSTAFF:
		return true
	default:
		return false
	}
}

// AuthSessionResponse defines model for AuthSessionResponse.
type AuthSessionResponse struct {
	Tokens TokenPair   `json:"tokens"`
	User   CurrentUser `json:"user"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	// BusinessId Database identifier backed by a PostgreSQL BIGINT.
	BusinessId EntityId            `json:"businessId"`
	Email      openapi_types.Email `json:"email"`
	FullName   string              `json:"fullName"`

	// Id Database identifier backed by a PostgreSQL BIGINT.
	Id          EntityId   `json:"id"`
	OutletIds   []EntityId `json:"outletIds"`
	Permissions []string   `json:"permissions"`
	Role        UserRole   `json:"role"`
}

// DecimalQuantity Positive decimal quantity with up to three fractional digits, encoded as a string for exact transport.
type DecimalQuantity = string

// EntityId Database identifier backed by a PostgreSQL BIGINT.
type EntityId = int64

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Stable machine-readable error code.
	Code    string         `json:"code"`
	Details *[]ErrorDetail `json:"details,omitempty"`
	Message string         `json:"message"`

	// RequestId Request identifier for support and log correlation.
	RequestId *string `json:"requestId,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// JakartaDateTime RFC 3339 timestamp with an explicit offset, normally Asia/Jakarta (`+07:00`).
type JakartaDateTime = time.Time

// LocalDate ISO 8601 calendar date interpreted in Asia/Jakarta.
type LocalDate = openapi_types.Date

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password *string             `json:"password,omitempty"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	// RefreshToken Refresh token for the session that will be revoked.
	RefreshToken *string `json:"refreshToken,omitempty"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Page       int32 `json:"page"`
	PageSize   int32 `json:"pageSize"`
	TotalItems int64 `json:"totalItems"`
	TotalPages int32 `json:"totalPages"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken Opaque refresh token issued by the login or refresh operation.
	RefreshToken *string `json:"refreshToken,omitempty"`
}

// RupiahAmount Exact whole-rupiah amount. Fractional rupiah values are not accepted.
type RupiahAmount = int64

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken           *string            `json:"accessToken,omitempty"`
	AccessTokenExpiresAt  *JakartaDateTime   `json:"accessTokenExpiresAt,omitempty"`
	RefreshToken          *string            `json:"refreshToken,omitempty"`
	RefreshTokenExpiresAt *JakartaDateTime   `json:"refreshTokenExpiresAt,omitempty"`
	TokenType             TokenPairTokenType `json:"tokenType"`
}

// TokenPairTokenType defines model for TokenPair.TokenType.
type TokenPairTokenType string

// UserRole defines model for UserRole.
type UserRole string

// Page defines model for Page.
type Page = int32

// PageSize defines model for PageSize.
type PageSize = int32

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate a user
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// Revoke the current authentication session
	// (POST /auth/logout)
	Logout(ctx echo.Context) error
	// Get the authenticated user
	// (GET /auth/me)
	GetCurrentUser(ctx echo.Context) error
	// Refresh an authentication session
	// (POST /auth/refresh)
	RefreshToken(ctx echo.Context) error
	// Check application health
	// (GET /health)
	GetHealth(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// RefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshToken(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout, options.OperationMiddlewares["logout"]...)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetCurrentUser, options.OperationMiddlewares["getCurrentUser"]...)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.RefreshToken, options.OperationMiddlewares["refreshToken"]...)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth, options.OperationMiddlewares["getHealth"]...)

}

type BadRequestJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type ServiceUnavailableJSONResponse ErrorResponse

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int32
}
type TooManyRequestsJSONResponse struct {
	Body ErrorResponse

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate *string
}
type UnauthorizedJSONResponse struct {
	Body ErrorResponse

	Headers UnauthorizedResponseHeaders
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthSessionResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response Login429JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Login500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout400JSONResponse struct{ BadRequestJSONResponse }

func (response Logout400JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Logout500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Logout500JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse CurrentUser

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetCurrentUser403JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUser500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetCurrentUser500JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse TokenPair

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken400JSONResponse struct{ BadRequestJSONResponse }

func (response RefreshToken400JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response RefreshToken429JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response RefreshToken500JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetHealth500JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate a user
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Revoke the current authentication session
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Get the authenticated user
	// (GET /auth/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// Refresh an authentication session
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Check application health
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx echo.Context) error {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(ctx echo.Context) error {
	var request GetCurrentUserRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx.Request().Context(), request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		return validResponse.VisitGetCurrentUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx echo.Context) error {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx.Request().Context(), request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		return validResponse.VisitRefreshTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx echo.Context) error {
	var request GetHealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.Request().Context(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		return validResponse.VisitGetHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FpRV+M40v0rOvrmYeZbJzgEuoe87IYOzISlgQ7p6cMAOwi7EmuwJbckEzKc/Pc9JTmOnRhCehpe9qWb",
	"xJbqqupW6aqURxrIJJUChNG080hTplgCBpT9dMbGgP+HoAPFU8OloB16KqBxyzSEJGVjICJLbkE1qUc5",
	"Pv2agZpSjwqWAO1QfIV6VAcRJMzNNWJZbGin5dGRVAkztEO5MO1t6tGEC55kiX1opim4RzAGRWczz+I5",
	"53/VYDqxIIgcEQWBVKEmKSiLzyMBS1MICTOk5fvP4bRT12Ld9uvAsoccrO+vgT7zqAKdSqHBOnafhQP4",
	"moE2+CmQwoCwf7I0jXnAcFVbf2pc2mMJzw8KRrRD/29rEbQt91RvHSgl1SA34kxWXTSMgChnlHBNEhbj",
	"iiAkUpER47Em9yzmobXdpDOPHkp1y8MQxNtiZJmJQBi0ACHJNCiEK6QhLI7lBEJiJEYX0RMTAZEpqAXq",
	"vjCgBIvPQd2DshbfDn9XkEzAQwoBYtcWAgEcRWQQZEpBaEEiOB7AZ8HuGY/ZbQxviNGygKscIA+AhJCC",
	"CEEEU3R1tkBlwQ6l/MjENCesfkM2SEkSJqZz2moyAQUkYSEQLmzsC0rwBMiEi1BOMMMjYGFewwZg1LTR",
	"HRlQq2XjHAIpQo2MmjBuyC2MpMI0MWrKxbhZqQabVStczmeBZJaK/wXhGwZ4kUBcCpvrXGsuxh6BhxQD",
	"72HOc2HzfcldX758aZQmqCm1+8AUqHKaopUgYnEMYgxVn+Vu0UZxMbZemc0fW3No6hy05lIUS0LvhCHH",
	"aVl8pjC9Dce6OWKxBo+mpa8eqZF3IPQ6pw3xrTPGFRIaa8q6AR8wWYX5rPOtZ54ztHM5N5lPdF0EX97+",
	"CYFBC+XRmy3nNtNcgNb9cC0PhOFm2g/RHiSMxxWOum+85QB4dJTF8Ynd8x5XH/KNrMrMxGD6oQXODSR6",
	"k9G5caYUw304E/xrBn03i1EZzDyagrLUlaJqImUGizzt0P9cdhu/X+M/fmPvj+v//6FuyS+wpKQrwc+B",
	"x2gO8L1lPvCQeuXAeYX3C2fnFso+qy6vjkU9CHjC4k8Zs25bTcUzqbnh91jA7Zvka/4qmXATkSzFwmYi",
	"BUBGigWOgiTkY260R0AEMkRhpAkjzltkJBWBBxYYYhQTOpXKYELDA0tS9BBtNbd3fcReCoHf2Lt+bHl7",
	"sx+vrprzT+3ZT/+sjUbBgZXl9JhhKCwJD7GyjDgocsuCOwjJ7ZQwcia1GSs4/3RM9vu/9E+GFWg721WN",
	"9m5nTYn2qC2lPTB58myQpiMOsV3BwjNPZlwCWudCevF2kmncbghzqovY0YSFoQKtV2dZYpwzv5i6jj3V",
	"fWKz5SExanZLg5qAJCyIuICGAhbaL5zAwTFVrvRPfuse93t/fBgc9A5Ohv3u8Xmdf0IbgA2KSClqy9n9",
	"lLsPrHslHgm0nkgV4rbIRSCVgsBSfAVWLjrqiDqYy+gFTzFxdJZiwhAmQhLLMbGzx7k0LTvGb/1797d3",
	"7y/eD9q/vzu6+PXd4Z7/qX30aWd/beRtZJ4P/K/AYhN9Y+S1YSazf4HAvLmk8g6tLMDLu7Ug80nqwB2x",
	"O6YM6zEDQ57UkGxw+IG02+09K+m0YUnqihkTqF5iHnBD5GikwXhEYLrH8ZR0NWdb+dTkx5t/+O87vn/z",
	"U9Xr2/72u4a/19huD1t+p7XbafvuRVoqHCEz0EDTdZQ4lgGLe7WqqH9+Sn5+57dIwGIQIVMEZyJYbFSq",
	"AI8DXFRwPgVuGU09kDEXpRPkBgEupMLCNgsTLv4Vs0zEcty0u9mKjkjYwzGIsYloZ3t3pwbSPLEqKqT4",
	"sjJBa/tnW5nnn39ens6jE8UNnIp4mu/QSwSboyrmr6PasRzLzHyblxSMFOjIysa6/LdPiRWCNvXxLKKd",
	"jiUmYoZMeBxjfVdwL+/AquzSilsbr7gCqG61Z2zMha01H8GwDZebLhfMTZsz3qKBUp7mb/ZNPGqkYXF/",
	"visU877ffW6v95+c6YyNoTrTznML9Wu7UOWw5O2tUveohLhitC5mOY9eg6KnKfuaIf3KTOVaZ05MIV9j",
	"LCK4J85fKjVSXputgyzlLOomMnPH4Sr4A6tAJ5GMoaHsm4TZV5vkcKFj8yf3LM5AE6bANYmCAFLjMm7B",
	"w13f9zemzOLQuFlkEILWRWBQJy1cVVM6S+8f2AO67joyxPHpiHYun5dDyzvq7NpbMmmDUyXLWkzlAa8F",
	"ypJyaC0v5IZrL1QlR/7dOtlR9vvSksvGnnD4U2uuo29xFCwB7/Y+9k+oR4+7n096g4s/zofdw8PS6BJo",
	"DUGmuJmeo7fyjrBdYjfDfHukt/bT4ZyuR1+GdLnLc/RlSNw68uRG9Rlzd5676eZ9J5vOHZL3bK4y328H",
	"9nX7J9wU3RpEeLvk5siY1DWYuBjJmk4Qns1ESLpnfRJIYTA1i93w2MkJgrIiVFNydnrevBJXojcXWPPE",
	"zTSQQvStSL3Pww+53GuS/fyI3RixgIvxlSgkopsFzVaUID7/SwooS0JiAUgRT0sArkSh324uLi4uGh8/",
	"Nnq9Gwt4UC5Ars4cnZ+ekLxQ4DHClaq8IDVJr3oa5646XYnSgduRQb/gnI6P2L3kIRnFkhkuxo1UcmGu",
	"RKog4FZxxFLr5pVlOTc2Y+be7571qUfvQWkXMr/Zavq2d5OCYCmnHdpu+s22O9FHlopbLDPRlt0drDaQ",
	"bmsqdgc8ETkFSotT0r4Mp9+tw1lRt7Nqlhf1rHSbsu373812XUNyfY9VZ0EAEObd/R2Hp85MgXurdAVk",
	"h7TWD6m0k3HQ9t76Qcvd+5lHd1+Cr+4epVy7aOfy2qM6SxKmplWPAGH23gb5yMbaFseKv+g1zlTwTGbm",
	"WaLh81djWumI8CKq7dTdIjjhn2t9xwatR1kcT9+UEN8rsNXt6PJ6Von0wC7TVtvA9bmXLwPyk9CL4u96",
	"AGOoCf0vYMqN9FfM+mq3fyXb88fuMpKJkLDy9mr3PngwzW9PZL+9ftDiOvbNIv0LGHfLtnIl+6LQ5nqq",
	"nNtL52hpmMHdMW+CVk8r6GgFJlMC3xAwyb9PGbc/N6iSZVCVe69RLZaOa2+8M5WusFYZWu1IzM9AzoXW",
	"yf/DO9PcN0x8Y52KbEO1VKaWfZ9KZTSZRGAicOoXJTE6HwVc6dqidNGOOrJ0z+6t1j7Xx33NsrfUKa7T",
	"OYu57XpKa1lawN+KHo59QQms+dnEc4H/EEFwR0ruIdHcpfN45z6+dvfSFpK2ZbF+A8CwureoRzMV0w7d",
	"smfbfL7HZ9xXin3eHy9+fJSjmHlPKQt0fb7XNuwmVJClNMsSd2fXs/8GAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
