// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for HealthUnavailableResponseStatus.
const (
	Unavailable HealthUnavailableResponseStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthUnavailableResponseStatus enum.
func (e HealthUnavailableResponseStatus) Valid() bool {
	switch e {
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for TokenPairTokenType.
const (
	Bearer TokenPairTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenPairTokenType enum.
func (e TokenPairTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	ADMIN        UserRole = "ADMIN"
	LAUNDRYSTAFF UserRole = "LAUNDRY_STAFF"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case ADMIN:
		return true
	case LAUNDRYSTAFF:
		return true
	default:
		return false
	}
}

// AuthSessionResponse defines model for AuthSessionResponse.
type AuthSessionResponse struct {
	Tokens TokenPair   `json:"tokens"`
	User   CurrentUser `json:"user"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	// BusinessId Database identifier backed by a PostgreSQL BIGINT.
	BusinessId EntityId            `json:"businessId"`
	Email      openapi_types.Email `json:"email"`
	FullName   string              `json:"fullName"`

	// Id Database identifier backed by a PostgreSQL BIGINT.
	Id          EntityId   `json:"id"`
	OutletIds   []EntityId `json:"outletIds"`
	Permissions []string   `json:"permissions"`
	Role        UserRole   `json:"role"`
}

// DecimalQuantity Positive decimal quantity with up to three fractional digits, encoded as a string for exact transport.
type DecimalQuantity = string

// EntityId Database identifier backed by a PostgreSQL BIGINT.
type EntityId = int64

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Stable machine-readable error code.
	Code    string         `json:"code"`
	Details *[]ErrorDetail `json:"details,omitempty"`
	Message string         `json:"message"`

	// RequestId Request identifier for support and log correlation.
	RequestId *string `json:"requestId,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HealthUnavailableResponse defines model for HealthUnavailableResponse.
type HealthUnavailableResponse struct {
	Status HealthUnavailableResponseStatus `json:"status"`
}

// HealthUnavailableResponseStatus defines model for HealthUnavailableResponse.Status.
type HealthUnavailableResponseStatus string

// JakartaDateTime RFC 3339 timestamp with an explicit offset, normally Asia/Jakarta (`+07:00`).
type JakartaDateTime = time.Time

// LocalDate ISO 8601 calendar date interpreted in Asia/Jakarta.
type LocalDate = openapi_types.Date

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password *string             `json:"password,omitempty"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	// RefreshToken Refresh token for the session that will be revoked.
	RefreshToken *string `json:"refreshToken,omitempty"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Page       int32 `json:"page"`
	PageSize   int32 `json:"pageSize"`
	TotalItems int64 `json:"totalItems"`
	TotalPages int32 `json:"totalPages"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken Opaque refresh token issued by the login or refresh operation.
	RefreshToken *string `json:"refreshToken,omitempty"`
}

// RupiahAmount Exact whole-rupiah amount. Fractional rupiah values are not accepted.
type RupiahAmount = int64

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken           *string            `json:"accessToken,omitempty"`
	AccessTokenExpiresAt  *JakartaDateTime   `json:"accessTokenExpiresAt,omitempty"`
	RefreshToken          *string            `json:"refreshToken,omitempty"`
	RefreshTokenExpiresAt *JakartaDateTime   `json:"refreshTokenExpiresAt,omitempty"`
	TokenType             TokenPairTokenType `json:"tokenType"`
}

// TokenPairTokenType defines model for TokenPair.TokenType.
type TokenPairTokenType string

// UserRole defines model for UserRole.
type UserRole string

// Page defines model for Page.
type Page = int32

// PageSize defines model for PageSize.
type PageSize = int32

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate a user
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// Revoke the current authentication session
	// (POST /auth/logout)
	Logout(ctx echo.Context) error
	// Get the authenticated user
	// (GET /auth/me)
	GetCurrentUser(ctx echo.Context) error
	// Refresh an authentication session
	// (POST /auth/refresh)
	RefreshToken(ctx echo.Context) error
	// Compatibility readiness check
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// Check whether the HTTP process is live
	// (GET /livez)
	GetLiveness(ctx echo.Context) error
	// Check whether the API is ready to serve database-backed requests
	// (GET /readyz)
	GetReadiness(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// RefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshToken(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetLiveness converts echo context to params.
func (w *ServerInterfaceWrapper) GetLiveness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLiveness(ctx)
	return err
}

// GetReadiness converts echo context to params.
func (w *ServerInterfaceWrapper) GetReadiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReadiness(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout, options.OperationMiddlewares["logout"]...)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetCurrentUser, options.OperationMiddlewares["getCurrentUser"]...)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.RefreshToken, options.OperationMiddlewares["refreshToken"]...)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth, options.OperationMiddlewares["getHealth"]...)
	router.GET(options.BaseURL+"/livez", wrapper.GetLiveness, options.OperationMiddlewares["getLiveness"]...)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadiness, options.OperationMiddlewares["getReadiness"]...)

}

type BadRequestJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type ServiceUnavailableJSONResponse ErrorResponse

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int32
}
type TooManyRequestsJSONResponse struct {
	Body ErrorResponse

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate *string
}
type UnauthorizedJSONResponse struct {
	Body ErrorResponse

	Headers UnauthorizedResponseHeaders
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthSessionResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response Login429JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Login500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout400JSONResponse struct{ BadRequestJSONResponse }

func (response Logout400JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Logout500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Logout500JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse CurrentUser

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetCurrentUser403JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUser500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetCurrentUser500JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse TokenPair

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken400JSONResponse struct{ BadRequestJSONResponse }

func (response RefreshToken400JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response RefreshToken429JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response RefreshToken500JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse HealthUnavailableResponse

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse HealthResponse

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse HealthResponse

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503JSONResponse HealthUnavailableResponse

func (response GetReadiness503JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate a user
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Revoke the current authentication session
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Get the authenticated user
	// (GET /auth/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// Refresh an authentication session
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Compatibility readiness check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Check whether the HTTP process is live
	// (GET /livez)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// Check whether the API is ready to serve database-backed requests
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx echo.Context) error {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(ctx echo.Context) error {
	var request GetCurrentUserRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx.Request().Context(), request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		return validResponse.VisitGetCurrentUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx echo.Context) error {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx.Request().Context(), request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		return validResponse.VisitRefreshTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx echo.Context) error {
	var request GetHealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.Request().Context(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		return validResponse.VisitGetHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(ctx echo.Context) error {
	var request GetLivenessRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx.Request().Context(), request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		return validResponse.VisitGetLivenessResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(ctx echo.Context) error {
	var request GetReadinessRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx.Request().Context(), request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		return validResponse.VisitGetReadinessResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FpvV9s49v4qOvrNi5nfOsEQaIfsi920KTPpUqAhnR6msEWxbxINtuRKMpBy8t33XMlx5MQQ0inM2bNv",
	"WuI/uo/ufe7Voyvf0UimmRQgjKbtO5oxxVIwoOyvEzYG/D8GHSmeGS4FbdNjAY0h0xCTjI2BiDwdgmrS",
	"gHK8+yUHNaUBFSwF2qb4CA2ojiaQMjfWiOWJoe3tgI6kSpmhbcqFae3QgKZc8DRP7U0zzcDdgjEoOpsF",
	"Fs8p/1qD6ciCIHJEFERSxZpkoCy+gEQsyyAmzJDtMHwIpx26FutOWAeW3RZgw3AN9FlAFehMCg3Wsa9Y",
	"3IcvOWiDvyIpDAj7J8uyhEcMZ7X1h8ap3Xl4flAwom36f1uLoG25u3rrjVJS9QsjzmTVRYMJEOWMEq5J",
	"yhKcEcREKjJiPNHkmiU8trabdBbQA6mGPI5BPC9GlpsJCIMWICa5BoVwhTSEJYm8gZgYidFF9MRMgMgM",
	"1AJ1TxhQgiWnoK5BWYvPh78jSC7gNoMIsWsLgQC+RWQU5UpBbEEiOB7BB8GuGU/YMIFnxGhZwFUBkEdA",
	"YshAxCCiKbo6X6CyYAdSvmNiWhBWPyMbpCQpE9M5bTW5AQUkZTEQLmzsS0rwFMgNF7G8wQyfAIuLGtYH",
	"o6aNzsiAWi0bpxBJEWtk1A3jhgxhJBWmiVFTLsbNSjXYrFrhdD4IJLNU/CvEzxjgRQJxKWyuc625GAcE",
	"bjMMfIA5z4XN9yV3ffz4seENUFNqXwFToPw0RSvRhCUJiDFUfVa4RRvFxdh6ZTa/bc2hqVPQmktRTgm9",
	"E8cch2XJicL0Nhzr5oglGgKaeZfuqJFXIPQ6pw3wqRPGFRIaa8q6F15jsgrzQRdLzzxnaPvT3GQx0EUZ",
	"fDn8AyKDFvy3N5vOMNdcgNa9eC0PhOFm2ovRHqSMJxWOuivBcgACOsqT5MiueXerN/lGVmVuEjC92ALn",
	"BlK9yduFcaYUw3U4F/xLDj03ilE5zAKagbLUlaJqImMGizxt039/6jR+v8B/wsb+54v//6Fuyo+wpKQr",
	"wQ+Bx2j28bllPvCYBn7ggtL7pbMLC77PqtOrY1EXIp6y5H3OrNtWU/FEam74NRZw+yT5UjxKbriZkDzD",
	"wmYmCoCMFIscBUnMx9zogICIZIzCSBNGnLfISCoCtywyxCgmdCaVwYSGW5Zm6CG63dzZCxG7F4KwsX9x",
	"tx3sz348P2/Of7VmP/2jNholB1am02WGobAkPMbKMuKgyJBFVxCT4ZQwciK1GSs4fX9IXvV+6R0NKtB2",
	"d6oa7cXumhIdUFtKu2CK5NkgTUccEjuDhWfuzbgUtC6E9OLpNNe43BDmVBexbxMWxwq0Xh1liXHO/GLo",
	"OvZU14nNpofEqFktDWoCkrJowgU0FLDYXnACB9+pcqV39FvnsNf9/Lr/pvvmaNDrHJ7W+Se2AdigiHhR",
	"W87u+9z9xrpX4pZA6xupYlwWuYikUhBZiq/AKkRHHVH7cxm94Ckmjs4zTBjCREwSOSZ29KSQpr5jwu1/",
	"7f324uXZy37r9xdvz359cbAfvm+9fb/7am3kbWQeDvyvwBIz+cbIa8NMbv8CgXnzicortLIAL6/WgiwG",
	"uR+cJ3y/G05PtlYB+zf+BPK37Iopw7rMwICnNenRP3hNWq3WvhWj2rA0c2WYCdRdCY+4IXI00mACIrBQ",
	"JcmUdDRnW8XQ5MfLv4Uv22F4+VOVLzvhzotGuN/YaQ22w/b2XrsVugepV/JiZqCBpuvIfCgjlnRr9Vzv",
	"9Jj8/CLcJhFLQMRMERyJYJlUmQLcyHBRwXkfuGU09UDGXHh73w1CXoqchW0Wp1z8M2G5SOS4adfhFQWU",
	"sttDEGMzoe2dvd0aSPOSUNFP5cXKANs7P9s1Zf775+XhAnqjuIFjkUwLbbFEsDmqcvw6qh3KsczNt3lJ",
	"wUiBnljBW1e57F1iJawtWriL0k6BEzNhhtzwJMGVScG1vAK7P/BmvL3xjCuA6mZ7wsZc2Cr5DgzbcLrZ",
	"cqnftK0ULFo//jB/suMTUCMNS3rz9awc9+XeQyolvHekEzaG6ki7D000rO2f+WEpGnNe38tDXDFaF7OC",
	"R09B0eOMfcmRfj5Tuda5k4HI1wSLCK7m84e8FtBTs7WfZ5xNOqnM3Ua+Cv6N1c43E5lAQ9knCbOPNsnB",
	"QoEXd65ZkoMmTIFrb0URZMZl3IKHe2EYbkyZxXZ3s8ggBK3LwKDCW7iqpnR6z7+xrQXdcWRIkuMRbX96",
	"WMgtr6izi2DJpA1OlSxrMfkvPBUoS8qBtbwQIK4xUtUexbV1ssP3+9KUfWP3OPy+OdfRt9zEesA73Xe9",
	"IxrQw86Ho27/7PPpoHNw4L3tgdYQ5Yqb6Sl6q+hl2yl2csy3Ozq0vw7mdH37cUCX+1NvPw6Im0eR3Kib",
	"E+52opedomNm07lNim7TeR6Grcg+bv+Ey7LPhAiHS26eGJO51hgXI1nTw8JdpYhJ56RHIikMpma5Gh46",
	"OUFQVsRqSk6OT5vn4lx05wJrnri5BlKKvhWp92HwupB7TfKqaA40RiziYnwuSonoRkGzFSWI979KAb4k",
	"JBaAFMnUA3AuSv12eXZ2dtZ4967R7V5awH2/ALk68/b0+IgUhQI3QK5UFQWpSbrVPgJ31elceK0CRwb9",
	"iA4D3mLXksdklEhmuBg3MsmFOReZgohbxZFIrZvnluXc2IyZe79z0qMBvQalXcjC5nYztF2nDATLOG3T",
	"VjNstlwvYmKpuMVyM9myq4PVBtItTeXqgHs5p0Bpub97JePpd+vNVtTtrJrlZT3zzoF2wvC72a5rpa7v",
	"Dus8igDi4lxi1+GpM1Pi3vIOr+wr2+tfqTTC8aWd/fUvLZ87zAK69xh8dSdAfu2i7U8XAdV5mjI1rXoE",
	"CLMnTshHNta2OFb8RS9wpJJnMjcPEg3vPxnTvC3Co6i2W3f+4YR/ofUdG7Qe5UkyfVZCfK/AVpejTxez",
	"SqT7dpq22kauQ798jFHshB4Vf9cDGENN6H8B4x8BPGHWV88pVrK9uO2OUZmICfOXV7v2wa1pfnsih631",
	"Ly0Okp8t0r+AceeDK4fJjwptoaf83F7aR0vDDK6ORfu2ultBRyswuRL4hICb4nrGuP1QokqWflXuPUW1",
	"WNquPfPK5B2+rTK02pGY74GcC62T/4dXprlvmPjGOjWx3VavTC1pgYQzbXXv5RbucaZfL/9OFGRSGU1u",
	"JmAmoPxTF66J92lAsFr0XHf3KevdUnO7TuAsxrYs8vCjAq5+27Dn6td3hFbX2q5BWfVq9ZOLBxjxWqYZ",
	"M3zIE26mBGNm9xUkmkB05bGhCIRjQcKv4eu9JOhKcJ/XoBNwH+Q7TNiDEs1GYGmSKWn3bTiitZspOQRd",
	"y4XD4pm/lg0D3Fmd9ErkXBOVC2E/7njQ0ejQMgdwKfl1MDjxh0Ef3Odxl0wPyYP+PHR/rXvuTe7/xtxY",
	"CRkGHgOO0cDdqP0gi8TFMXOjOFuef11UG0xrD6u1tpqjXl2hHfcUDWiuEtqmW7ZxVIx390CJ8r69Kg6f",
	"ym8SCxSz4D7ZjulZCNmGVXglzbxRlhaG2cXsPwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
