// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (business_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, business_id, user_id, token_hash, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	BusinessID int64              `json:"business_id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type CreateRefreshTokenRow struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.BusinessID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i CreateRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveRefreshSession = `-- name: GetActiveRefreshSession :one
SELECT id, business_id, user_id, expires_at, revoked_at
FROM refresh_tokens
WHERE id = $1
  AND business_id = $2
  AND user_id = $3
  AND revoked_at IS NULL
  AND expires_at > now()
`

type GetActiveRefreshSessionParams struct {
	ID         int64 `json:"id"`
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
}

type GetActiveRefreshSessionRow struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	UserID     int64              `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetActiveRefreshSession(ctx context.Context, arg GetActiveRefreshSessionParams) (GetActiveRefreshSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveRefreshSession, arg.ID, arg.BusinessID, arg.UserID)
	var i GetActiveRefreshSessionRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveUser = `-- name: GetActiveUser :one
SELECT id, business_id, email, full_name, role, is_active
FROM users
WHERE id = $1 AND business_id = $2 AND is_active = TRUE
`

type GetActiveUserParams struct {
	ID         int64 `json:"id"`
	BusinessID int64 `json:"business_id"`
}

type GetActiveUserRow struct {
	ID         int64  `json:"id"`
	BusinessID int64  `json:"business_id"`
	Email      string `json:"email"`
	FullName   string `json:"full_name"`
	Role       string `json:"role"`
	IsActive   bool   `json:"is_active"`
}

func (q *Queries) GetActiveUser(ctx context.Context, arg GetActiveUserParams) (GetActiveUserRow, error) {
	row := q.db.QueryRow(ctx, getActiveUser, arg.ID, arg.BusinessID)
	var i GetActiveUserRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, business_id, user_id, token_hash, expires_at, revoked_at
FROM refresh_tokens
WHERE token_hash = $1
FOR UPDATE
`

type GetRefreshTokenForUpdateRow struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash string) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, business_id, email, full_name, password_hash, role, is_active
FROM users
WHERE lower(email) = lower($1)
`

type GetUserForLoginRow struct {
	ID           int64  `json:"id"`
	BusinessID   int64  `json:"business_id"`
	Email        string `json:"email"`
	FullName     string `json:"full_name"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, lower string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, lower)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const listUserOutletIDs = `-- name: ListUserOutletIDs :many
SELECT outlet_id
FROM user_outlets
WHERE business_id = $1 AND user_id = $2
ORDER BY outlet_id
`

type ListUserOutletIDsParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) ListUserOutletIDs(ctx context.Context, arg ListUserOutletIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserOutletIDs, arg.BusinessID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var outlet_id int64
		if err := rows.Scan(&outlet_id); err != nil {
			return nil, err
		}
		items = append(items, outlet_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionCodes = `-- name: ListUserPermissionCodes :many
SELECT permission_code
FROM user_permissions
WHERE business_id = $1 AND user_id = $2
ORDER BY permission_code
`

type ListUserPermissionCodesParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) ListUserPermissionCodes(ctx context.Context, arg ListUserPermissionCodesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPermissionCodes, arg.BusinessID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_code string
		if err := rows.Scan(&permission_code); err != nil {
			return nil, err
		}
		items = append(items, permission_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens
SET revoked_at = now()
WHERE id = $1 AND business_id = $2 AND user_id = $3 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	ID         int64 `json:"id"`
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.BusinessID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
