// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomerOrderHistory = `-- name: CountCustomerOrderHistory :one
SELECT count(*)
FROM orders
WHERE business_id = $1 AND customer_id = $2
  AND ($3::boolean OR outlet_id = ANY($4::bigint[]))
`

type CountCustomerOrderHistoryParams struct {
	BusinessID int64   `json:"business_id"`
	CustomerID int64   `json:"customer_id"`
	IsAdmin    bool    `json:"is_admin"`
	OutletIds  []int64 `json:"outlet_ids"`
}

func (q *Queries) CountCustomerOrderHistory(ctx context.Context, arg CountCustomerOrderHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomerOrderHistory,
		arg.BusinessID,
		arg.CustomerID,
		arg.IsAdmin,
		arg.OutletIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomers = `-- name: CountCustomers :one
SELECT count(*)
FROM customers
WHERE business_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%' OR COALESCE(phone, '') ILIKE '%' || $2::text || '%')
`

type CountCustomersParams struct {
	BusinessID int64  `json:"business_id"`
	Search     string `json:"search"`
}

func (q *Queries) CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers, arg.BusinessID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (business_id, name, phone, address)
VALUES ($1, $2, $3, $4)
RETURNING id, business_id, name, phone, address, created_at, updated_at
`

type CreateCustomerParams struct {
	BusinessID int64       `json:"business_id"`
	Name       string      `json:"name"`
	Phone      pgtype.Text `json:"phone"`
	Address    pgtype.Text `json:"address"`
}

type CreateCustomerRow struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Name       string             `json:"name"`
	Phone      pgtype.Text        `json:"phone"`
	Address    pgtype.Text        `json:"address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.BusinessID,
		arg.Name,
		arg.Phone,
		arg.Address,
	)
	var i CreateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateCustomer = `-- name: DeactivateCustomer :one
UPDATE customers
SET deleted_at = now(), updated_at = now()
WHERE business_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, business_id, name, phone, address, created_at, updated_at, deleted_at
`

type DeactivateCustomerParams struct {
	BusinessID int64 `json:"business_id"`
	CustomerID int64 `json:"customer_id"`
}

type DeactivateCustomerRow struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Name       string             `json:"name"`
	Phone      pgtype.Text        `json:"phone"`
	Address    pgtype.Text        `json:"address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) DeactivateCustomer(ctx context.Context, arg DeactivateCustomerParams) (DeactivateCustomerRow, error) {
	row := q.db.QueryRow(ctx, deactivateCustomer, arg.BusinessID, arg.CustomerID)
	var i DeactivateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, business_id, name, phone, address, created_at, updated_at
FROM customers
WHERE business_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetCustomerParams struct {
	BusinessID int64 `json:"business_id"`
	CustomerID int64 `json:"customer_id"`
}

type GetCustomerRow struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Name       string             `json:"name"`
	Phone      pgtype.Text        `json:"phone"`
	Address    pgtype.Text        `json:"address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomer(ctx context.Context, arg GetCustomerParams) (GetCustomerRow, error) {
	row := q.db.QueryRow(ctx, getCustomer, arg.BusinessID, arg.CustomerID)
	var i GetCustomerRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerForHistory = `-- name: GetCustomerForHistory :one
SELECT id
FROM customers
WHERE business_id = $1 AND id = $2
`

type GetCustomerForHistoryParams struct {
	BusinessID int64 `json:"business_id"`
	CustomerID int64 `json:"customer_id"`
}

func (q *Queries) GetCustomerForHistory(ctx context.Context, arg GetCustomerForHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCustomerForHistory, arg.BusinessID, arg.CustomerID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCustomerForUpdate = `-- name: GetCustomerForUpdate :one
SELECT id, business_id, name, phone, address, created_at, updated_at
FROM customers
WHERE business_id = $1 AND id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type GetCustomerForUpdateParams struct {
	BusinessID int64 `json:"business_id"`
	CustomerID int64 `json:"customer_id"`
}

type GetCustomerForUpdateRow struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Name       string             `json:"name"`
	Phone      pgtype.Text        `json:"phone"`
	Address    pgtype.Text        `json:"address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerForUpdate(ctx context.Context, arg GetCustomerForUpdateParams) (GetCustomerForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCustomerForUpdate, arg.BusinessID, arg.CustomerID)
	var i GetCustomerForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomerOrderHistory = `-- name: ListCustomerOrderHistory :many
SELECT id, business_id, outlet_id, customer_id, invoice_number, status,
       payment_status, total_amount, received_at, due_at, completed_at, cancelled_at, created_at
FROM orders
WHERE business_id = $1 AND customer_id = $2
  AND ($3::boolean OR outlet_id = ANY($4::bigint[]))
ORDER BY created_at DESC, id DESC
LIMIT $6 OFFSET $5
`

type ListCustomerOrderHistoryParams struct {
	BusinessID int64   `json:"business_id"`
	CustomerID int64   `json:"customer_id"`
	IsAdmin    bool    `json:"is_admin"`
	OutletIds  []int64 `json:"outlet_ids"`
	PageOffset int32   `json:"page_offset"`
	PageLimit  int32   `json:"page_limit"`
}

type ListCustomerOrderHistoryRow struct {
	ID            int64              `json:"id"`
	BusinessID    int64              `json:"business_id"`
	OutletID      int64              `json:"outlet_id"`
	CustomerID    int64              `json:"customer_id"`
	InvoiceNumber string             `json:"invoice_number"`
	Status        string             `json:"status"`
	PaymentStatus string             `json:"payment_status"`
	TotalAmount   int64              `json:"total_amount"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	DueAt         pgtype.Timestamptz `json:"due_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListCustomerOrderHistory(ctx context.Context, arg ListCustomerOrderHistoryParams) ([]ListCustomerOrderHistoryRow, error) {
	rows, err := q.db.Query(ctx, listCustomerOrderHistory,
		arg.BusinessID,
		arg.CustomerID,
		arg.IsAdmin,
		arg.OutletIds,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerOrderHistoryRow
	for rows.Next() {
		var i ListCustomerOrderHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.OutletID,
			&i.CustomerID,
			&i.InvoiceNumber,
			&i.Status,
			&i.PaymentStatus,
			&i.TotalAmount,
			&i.ReceivedAt,
			&i.DueAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, business_id, name, phone, address, created_at, updated_at
FROM customers
WHERE business_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%' OR COALESCE(phone, '') ILIKE '%' || $2::text || '%')
ORDER BY lower(name), id
LIMIT $4 OFFSET $3
`

type ListCustomersParams struct {
	BusinessID int64  `json:"business_id"`
	Search     string `json:"search"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListCustomersRow struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Name       string             `json:"name"`
	Phone      pgtype.Text        `json:"phone"`
	Address    pgtype.Text        `json:"address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.BusinessID,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersRow
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $1, phone = $2, address = $3, updated_at = now()
WHERE business_id = $4 AND id = $5 AND deleted_at IS NULL
RETURNING id, business_id, name, phone, address, created_at, updated_at
`

type UpdateCustomerParams struct {
	Name       string      `json:"name"`
	Phone      pgtype.Text `json:"phone"`
	Address    pgtype.Text `json:"address"`
	BusinessID int64       `json:"business_id"`
	CustomerID int64       `json:"customer_id"`
}

type UpdateCustomerRow struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Name       string             `json:"name"`
	Phone      pgtype.Text        `json:"phone"`
	Address    pgtype.Text        `json:"address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (UpdateCustomerRow, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.Name,
		arg.Phone,
		arg.Address,
		arg.BusinessID,
		arg.CustomerID,
	)
	var i UpdateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
