// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOutletDashboard = `-- name: GetOutletDashboard :one
WITH outlet_scope AS MATERIALIZED (
    SELECT o.id, o.business_id, o.code, o.name, o.phone, o.address, o.is_active, o.created_at, o.updated_at,
           b.timezone,
           (now() AT TIME ZONE b.timezone)::date AS business_date
    FROM outlets o
    JOIN businesses b ON b.id=o.business_id AND b.is_active
    JOIN users actor ON actor.business_id=o.business_id
        AND actor.id=$1 AND actor.is_active
        AND actor.role=CASE WHEN $2::boolean THEN 'ADMIN' ELSE 'LAUNDRY_STAFF' END
    WHERE o.business_id=$3
      AND o.id=$4
      AND o.is_active
      AND ($2::boolean OR EXISTS (
          SELECT 1 FROM user_outlets assignment
          WHERE assignment.business_id=o.business_id
            AND assignment.outlet_id=o.id
            AND assignment.user_id=actor.id
      ))
), local_day AS (
    SELECT outlet_scope.id, outlet_scope.business_id, outlet_scope.code, outlet_scope.name, outlet_scope.phone, outlet_scope.address, outlet_scope.is_active, outlet_scope.created_at, outlet_scope.updated_at, outlet_scope.timezone, outlet_scope.business_date,
           business_date::timestamp AT TIME ZONE timezone AS day_start,
           (business_date + 1)::timestamp AT TIME ZONE timezone AS day_end
    FROM outlet_scope
), payment_totals AS (
    SELECT p.business_id, p.outlet_id,
           count(*)::bigint AS confirmed_payment_count,
           COALESCE(sum(p.amount), 0)::bigint AS confirmed_payment_amount
    FROM payments p
    JOIN local_day d ON d.business_id=p.business_id AND d.id=p.outlet_id
    WHERE p.status='CONFIRMED'
      AND p.confirmed_at >= d.day_start
      AND p.confirmed_at < d.day_end
    GROUP BY p.business_id, p.outlet_id
), expense_totals AS (
    SELECT e.business_id, e.outlet_id,
           count(*)::bigint AS expense_count,
           COALESCE(sum(e.amount), 0)::bigint AS expense_amount
    FROM expenses e
    JOIN local_day d ON d.business_id=e.business_id AND d.id=e.outlet_id
    WHERE e.expense_at >= d.day_start
      AND e.expense_at < d.day_end
    GROUP BY e.business_id, e.outlet_id
)
SELECT d.id AS outlet_id, d.business_id, d.code, d.name, d.phone, d.address, d.is_active, d.created_at, d.updated_at,
       d.timezone, d.business_date,
       COALESCE(p.confirmed_payment_count, 0)::bigint AS confirmed_payment_count,
       COALESCE(p.confirmed_payment_amount, 0)::bigint AS confirmed_payment_amount,
       COALESCE(e.expense_count, 0)::bigint AS expense_count,
       COALESCE(e.expense_amount, 0)::bigint AS expense_amount
FROM local_day d
LEFT JOIN payment_totals p ON p.business_id=d.business_id AND p.outlet_id=d.id
LEFT JOIN expense_totals e ON e.business_id=d.business_id AND e.outlet_id=d.id
`

type GetOutletDashboardParams struct {
	UserID     int64 `json:"user_id"`
	IsAdmin    bool  `json:"is_admin"`
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
}

type GetOutletDashboardRow struct {
	OutletID               int64              `json:"outlet_id"`
	BusinessID             int64              `json:"business_id"`
	Code                   string             `json:"code"`
	Name                   string             `json:"name"`
	Phone                  pgtype.Text        `json:"phone"`
	Address                pgtype.Text        `json:"address"`
	IsActive               bool               `json:"is_active"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	Timezone               string             `json:"timezone"`
	BusinessDate           pgtype.Date        `json:"business_date"`
	ConfirmedPaymentCount  int64              `json:"confirmed_payment_count"`
	ConfirmedPaymentAmount int64              `json:"confirmed_payment_amount"`
	ExpenseCount           int64              `json:"expense_count"`
	ExpenseAmount          int64              `json:"expense_amount"`
}

func (q *Queries) GetOutletDashboard(ctx context.Context, arg GetOutletDashboardParams) (GetOutletDashboardRow, error) {
	row := q.db.QueryRow(ctx, getOutletDashboard,
		arg.UserID,
		arg.IsAdmin,
		arg.BusinessID,
		arg.OutletID,
	)
	var i GetOutletDashboardRow
	err := row.Scan(
		&i.OutletID,
		&i.BusinessID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.BusinessDate,
		&i.ConfirmedPaymentCount,
		&i.ConfirmedPaymentAmount,
		&i.ExpenseCount,
		&i.ExpenseAmount,
	)
	return i, err
}
