// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package postgresql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExpenseCategories = `-- name: CountExpenseCategories :one
SELECT count(*) FROM expense_categories
WHERE business_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%')
  AND ($3::boolean OR is_active)
`

type CountExpenseCategoriesParams struct {
	BusinessID      int64  `json:"business_id"`
	Search          string `json:"search"`
	IncludeInactive bool   `json:"include_inactive"`
}

func (q *Queries) CountExpenseCategories(ctx context.Context, arg CountExpenseCategoriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenseCategories, arg.BusinessID, arg.Search, arg.IncludeInactive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpenses = `-- name: CountExpenses :one
SELECT count(*) FROM expenses
JOIN outlets o ON o.business_id=expenses.business_id AND o.id=expenses.outlet_id AND o.is_active
WHERE expenses.business_id=$1
  AND ($2::boolean OR expenses.outlet_id=ANY($3::bigint[]))
  AND ($4::bigint IS NULL OR expenses.outlet_id=$4)
  AND expenses.expense_at >= ($5::date::timestamp AT TIME ZONE 'Asia/Jakarta')
  AND expenses.expense_at < (($6::date + 1)::timestamp AT TIME ZONE 'Asia/Jakarta')
`

type CountExpensesParams struct {
	BusinessID int64       `json:"business_id"`
	IsAdmin    bool        `json:"is_admin"`
	OutletIds  []int64     `json:"outlet_ids"`
	OutletID   pgtype.Int8 `json:"outlet_id"`
	DateFrom   pgtype.Date `json:"date_from"`
	DateTo     pgtype.Date `json:"date_to"`
}

func (q *Queries) CountExpenses(ctx context.Context, arg CountExpensesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenses,
		arg.BusinessID,
		arg.IsAdmin,
		arg.OutletIds,
		arg.OutletID,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (business_id,outlet_id,category_id,amount,description,expense_at,receipt_reference,created_by)
SELECT $1, o.id, $2, $3, $4,
       $5, $6, $7
FROM outlets o
JOIN users u ON u.business_id=o.business_id AND u.id=$7 AND u.is_active
JOIN expense_categories c ON c.business_id=o.business_id AND c.id=$2 AND c.is_active
WHERE o.business_id=$1 AND o.id=$8 AND o.is_active
  AND ($9::boolean OR EXISTS (
      SELECT 1 FROM user_outlets uo WHERE uo.business_id=o.business_id AND uo.outlet_id=o.id AND uo.user_id=u.id))
RETURNING id,business_id,outlet_id,category_id,amount,description,expense_at,receipt_reference,created_by,created_at,updated_at,version
`

type CreateExpenseParams struct {
	BusinessID       int64              `json:"business_id"`
	CategoryID       int64              `json:"category_id"`
	Amount           int64              `json:"amount"`
	Description      string             `json:"description"`
	ExpenseAt        pgtype.Timestamptz `json:"expense_at"`
	ReceiptReference pgtype.Text        `json:"receipt_reference"`
	UserID           int64              `json:"user_id"`
	OutletID         int64              `json:"outlet_id"`
	IsAdmin          bool               `json:"is_admin"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.BusinessID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.ExpenseAt,
		arg.ReceiptReference,
		arg.UserID,
		arg.OutletID,
		arg.IsAdmin,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.ExpenseAt,
		&i.ReceiptReference,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (business_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, business_id, name, description, is_active, created_at, updated_at
`

type CreateExpenseCategoryParams struct {
	BusinessID  int64       `json:"business_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, createExpenseCategory, arg.BusinessID, arg.Name, arg.Description)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveExpenseCategory = `-- name: GetActiveExpenseCategory :one
SELECT id FROM expense_categories
WHERE business_id=$1 AND id=$2 AND is_active
FOR SHARE
`

type GetActiveExpenseCategoryParams struct {
	BusinessID int64 `json:"business_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) GetActiveExpenseCategory(ctx context.Context, arg GetActiveExpenseCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveExpenseCategory, arg.BusinessID, arg.CategoryID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getExpense = `-- name: GetExpense :one
SELECT e.id, e.business_id, e.outlet_id, e.category_id, e.amount, e.description, e.expense_at,
       e.receipt_reference, e.created_by, e.created_at, e.updated_at, e.version
FROM expenses e
JOIN outlets o ON o.business_id=e.business_id AND o.id=e.outlet_id AND o.is_active
WHERE e.business_id=$1 AND e.id=$2
  AND ($3::boolean OR EXISTS (
      SELECT 1 FROM user_outlets uo WHERE uo.business_id=e.business_id
        AND uo.outlet_id=e.outlet_id AND uo.user_id=$4))
`

type GetExpenseParams struct {
	BusinessID int64 `json:"business_id"`
	ExpenseID  int64 `json:"expense_id"`
	IsAdmin    bool  `json:"is_admin"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpense,
		arg.BusinessID,
		arg.ExpenseID,
		arg.IsAdmin,
		arg.UserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.ExpenseAt,
		&i.ReceiptReference,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getExpenseCategory = `-- name: GetExpenseCategory :one
SELECT id, business_id, name, description, is_active, created_at, updated_at
FROM expense_categories WHERE business_id = $1 AND id = $2
`

type GetExpenseCategoryParams struct {
	BusinessID int64 `json:"business_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) GetExpenseCategory(ctx context.Context, arg GetExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getExpenseCategory, arg.BusinessID, arg.CategoryID)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseCategoryForUpdate = `-- name: GetExpenseCategoryForUpdate :one
SELECT id, business_id, name, description, is_active, created_at, updated_at
FROM expense_categories WHERE business_id = $1 AND id = $2
FOR UPDATE
`

type GetExpenseCategoryForUpdateParams struct {
	BusinessID int64 `json:"business_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) GetExpenseCategoryForUpdate(ctx context.Context, arg GetExpenseCategoryForUpdateParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getExpenseCategoryForUpdate, arg.BusinessID, arg.CategoryID)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseForUpdate = `-- name: GetExpenseForUpdate :one
SELECT e.id, e.business_id, e.outlet_id, e.category_id, e.amount, e.description, e.expense_at,
       e.receipt_reference, e.created_by, e.created_at, e.updated_at, e.version
FROM expenses e
JOIN outlets o ON o.business_id=e.business_id AND o.id=e.outlet_id AND o.is_active
JOIN users u ON u.business_id=e.business_id AND u.id=$1 AND u.is_active
WHERE e.business_id=$2 AND e.id=$3
  AND ($4::boolean OR EXISTS (
      SELECT 1 FROM user_outlets uo WHERE uo.business_id=e.business_id
        AND uo.outlet_id=e.outlet_id AND uo.user_id=$1))
FOR UPDATE OF e, o, u
`

type GetExpenseForUpdateParams struct {
	UserID     int64 `json:"user_id"`
	BusinessID int64 `json:"business_id"`
	ExpenseID  int64 `json:"expense_id"`
	IsAdmin    bool  `json:"is_admin"`
}

func (q *Queries) GetExpenseForUpdate(ctx context.Context, arg GetExpenseForUpdateParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseForUpdate,
		arg.UserID,
		arg.BusinessID,
		arg.ExpenseID,
		arg.IsAdmin,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.ExpenseAt,
		&i.ReceiptReference,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertExpenseAuditLog = `-- name: InsertExpenseAuditLog :exec
INSERT INTO audit_logs (business_id,outlet_id,actor_user_id,action,entity_type,entity_id,old_values,new_values,ip_address,user_agent)
VALUES ($1,$2,$3,$4,'expense',
        $5,$6,$7,$8,$9)
`

type InsertExpenseAuditLogParams struct {
	BusinessID  int64       `json:"business_id"`
	OutletID    pgtype.Int8 `json:"outlet_id"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	EntityID    pgtype.Int8 `json:"entity_id"`
	OldValues   []byte      `json:"old_values"`
	NewValues   []byte      `json:"new_values"`
	IpAddress   *netip.Addr `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertExpenseAuditLog(ctx context.Context, arg InsertExpenseAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertExpenseAuditLog,
		arg.BusinessID,
		arg.OutletID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityID,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const insertExpenseCategoryAuditLog = `-- name: InsertExpenseCategoryAuditLog :exec
INSERT INTO audit_logs (business_id,actor_user_id,action,entity_type,entity_id,old_values,new_values,ip_address,user_agent)
VALUES ($1,$2,$3,'expense_category',
        $4,$5,$6,$7,$8)
`

type InsertExpenseCategoryAuditLogParams struct {
	BusinessID  int64       `json:"business_id"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	EntityID    pgtype.Int8 `json:"entity_id"`
	OldValues   []byte      `json:"old_values"`
	NewValues   []byte      `json:"new_values"`
	IpAddress   *netip.Addr `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertExpenseCategoryAuditLog(ctx context.Context, arg InsertExpenseCategoryAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertExpenseCategoryAuditLog,
		arg.BusinessID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityID,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT id, business_id, name, description, is_active, created_at, updated_at
FROM expense_categories
WHERE business_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%')
  AND ($3::boolean OR is_active)
ORDER BY lower(name), id
LIMIT $5 OFFSET $4
`

type ListExpenseCategoriesParams struct {
	BusinessID      int64  `json:"business_id"`
	Search          string `json:"search"`
	IncludeInactive bool   `json:"include_inactive"`
	PageOffset      int32  `json:"page_offset"`
	PageLimit       int32  `json:"page_limit"`
}

func (q *Queries) ListExpenseCategories(ctx context.Context, arg ListExpenseCategoriesParams) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listExpenseCategories,
		arg.BusinessID,
		arg.Search,
		arg.IncludeInactive,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseCategory
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT expenses.id, expenses.business_id, expenses.outlet_id, expenses.category_id,
       expenses.amount, expenses.description, expenses.expense_at,
       expenses.receipt_reference, expenses.created_by, expenses.created_at, expenses.updated_at, expenses.version
FROM expenses
JOIN outlets o ON o.business_id=expenses.business_id AND o.id=expenses.outlet_id AND o.is_active
WHERE expenses.business_id=$1
  AND ($2::boolean OR expenses.outlet_id=ANY($3::bigint[]))
  AND ($4::bigint IS NULL OR expenses.outlet_id=$4)
  AND expenses.expense_at >= ($5::date::timestamp AT TIME ZONE 'Asia/Jakarta')
  AND expenses.expense_at < (($6::date + 1)::timestamp AT TIME ZONE 'Asia/Jakarta')
ORDER BY expenses.expense_at DESC, expenses.id DESC
LIMIT $8 OFFSET $7
`

type ListExpensesParams struct {
	BusinessID int64       `json:"business_id"`
	IsAdmin    bool        `json:"is_admin"`
	OutletIds  []int64     `json:"outlet_ids"`
	OutletID   pgtype.Int8 `json:"outlet_id"`
	DateFrom   pgtype.Date `json:"date_from"`
	DateTo     pgtype.Date `json:"date_to"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.BusinessID,
		arg.IsAdmin,
		arg.OutletIds,
		arg.OutletID,
		arg.DateFrom,
		arg.DateTo,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.OutletID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.ExpenseAt,
			&i.ReceiptReference,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveExpenseOutlet = `-- name: LockActiveExpenseOutlet :one
SELECT o.id FROM outlets o
JOIN users u ON u.business_id=o.business_id AND u.id=$1 AND u.is_active
WHERE o.business_id=$2 AND o.id=$3 AND o.is_active
  AND ($4::boolean OR EXISTS (
      SELECT 1 FROM user_outlets uo WHERE uo.business_id=o.business_id AND uo.outlet_id=o.id AND uo.user_id=u.id))
FOR SHARE OF o, u
`

type LockActiveExpenseOutletParams struct {
	UserID     int64 `json:"user_id"`
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	IsAdmin    bool  `json:"is_admin"`
}

func (q *Queries) LockActiveExpenseOutlet(ctx context.Context, arg LockActiveExpenseOutletParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockActiveExpenseOutlet,
		arg.UserID,
		arg.BusinessID,
		arg.OutletID,
		arg.IsAdmin,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockExpenseOutletAssignment = `-- name: LockExpenseOutletAssignment :one
SELECT user_id FROM user_outlets
WHERE business_id=$1 AND user_id=$2 AND outlet_id=$3
FOR SHARE
`

type LockExpenseOutletAssignmentParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
	OutletID   int64 `json:"outlet_id"`
}

func (q *Queries) LockExpenseOutletAssignment(ctx context.Context, arg LockExpenseOutletAssignmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockExpenseOutletAssignment, arg.BusinessID, arg.UserID, arg.OutletID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses e SET category_id=$1, amount=$2,
    description=$3, expense_at=$4,
    receipt_reference=$5, updated_at=now(), version=version+1
WHERE e.business_id=$6 AND e.id=$7
  AND e.version=$8
  AND EXISTS (SELECT 1 FROM outlets o WHERE o.business_id=e.business_id AND o.id=e.outlet_id AND o.is_active)
  AND EXISTS (SELECT 1 FROM users u WHERE u.business_id=e.business_id AND u.id=$9 AND u.is_active)
  AND ($10::boolean OR EXISTS (
      SELECT 1 FROM user_outlets uo WHERE uo.business_id=e.business_id AND uo.outlet_id=e.outlet_id AND uo.user_id=$9))
  AND EXISTS (SELECT 1 FROM expense_categories c WHERE c.business_id=e.business_id AND c.id=$1 AND c.is_active)
RETURNING id,business_id,outlet_id,category_id,amount,description,expense_at,receipt_reference,created_by,created_at,updated_at,version
`

type UpdateExpenseParams struct {
	CategoryID       int64              `json:"category_id"`
	Amount           int64              `json:"amount"`
	Description      string             `json:"description"`
	ExpenseAt        pgtype.Timestamptz `json:"expense_at"`
	ReceiptReference pgtype.Text        `json:"receipt_reference"`
	BusinessID       int64              `json:"business_id"`
	ExpenseID        int64              `json:"expense_id"`
	ExpectedVersion  int64              `json:"expected_version"`
	UserID           int64              `json:"user_id"`
	IsAdmin          bool               `json:"is_admin"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.ExpenseAt,
		arg.ReceiptReference,
		arg.BusinessID,
		arg.ExpenseID,
		arg.ExpectedVersion,
		arg.UserID,
		arg.IsAdmin,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.ExpenseAt,
		&i.ReceiptReference,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateExpenseCategory = `-- name: UpdateExpenseCategory :one
UPDATE expense_categories SET name=$1, description=$2,
    is_active=$3, updated_at=now()
WHERE business_id=$4 AND id=$5
RETURNING id, business_id, name, description, is_active, created_at, updated_at
`

type UpdateExpenseCategoryParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	BusinessID  int64       `json:"business_id"`
	CategoryID  int64       `json:"category_id"`
}

func (q *Queries) UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, updateExpenseCategory,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.BusinessID,
		arg.CategoryID,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
