// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package postgresql

import (
	"context"
)

const checkDatabaseHealth = `-- name: CheckDatabaseHealth :one
SELECT 1 AS healthy
`

func (q *Queries) CheckDatabaseHealth(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, checkDatabaseHealth)
	var healthy int32
	err := row.Scan(&healthy)
	return healthy, err
}
