// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: management.sql

package postgresql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const addStaffOutlet = `-- name: AddStaffOutlet :exec
INSERT INTO user_outlets (business_id,user_id,outlet_id) VALUES ($1,$2,$3)
`

type AddStaffOutletParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
	OutletID   int64 `json:"outlet_id"`
}

func (q *Queries) AddStaffOutlet(ctx context.Context, arg AddStaffOutletParams) error {
	_, err := q.db.Exec(ctx, addStaffOutlet, arg.BusinessID, arg.UserID, arg.OutletID)
	return err
}

const addStaffPermission = `-- name: AddStaffPermission :exec
INSERT INTO user_permissions (business_id,user_id,permission_code,granted_by)
VALUES ($1,$2,$3,$4)
`

type AddStaffPermissionParams struct {
	BusinessID     int64  `json:"business_id"`
	UserID         int64  `json:"user_id"`
	PermissionCode string `json:"permission_code"`
	GrantedBy      int64  `json:"granted_by"`
}

func (q *Queries) AddStaffPermission(ctx context.Context, arg AddStaffPermissionParams) error {
	_, err := q.db.Exec(ctx, addStaffPermission,
		arg.BusinessID,
		arg.UserID,
		arg.PermissionCode,
		arg.GrantedBy,
	)
	return err
}

const countActiveAssignedStaffWithoutOtherOutlet = `-- name: CountActiveAssignedStaffWithoutOtherOutlet :one
SELECT count(DISTINCT u.id)
FROM users u
JOIN user_outlets uo ON uo.business_id=u.business_id AND uo.user_id=u.id
WHERE u.business_id=$1 AND u.is_active AND u.role='LAUNDRY_STAFF' AND uo.outlet_id=$2
AND NOT EXISTS (
    SELECT 1 FROM user_outlets other_uo
    JOIN outlets other ON other.id=other_uo.outlet_id AND other.business_id=other_uo.business_id AND other.is_active
    WHERE other_uo.business_id=u.business_id AND other_uo.user_id=u.id AND other_uo.outlet_id<>$2
)
`

type CountActiveAssignedStaffWithoutOtherOutletParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
}

func (q *Queries) CountActiveAssignedStaffWithoutOtherOutlet(ctx context.Context, arg CountActiveAssignedStaffWithoutOtherOutletParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAssignedStaffWithoutOtherOutlet, arg.BusinessID, arg.OutletID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveOutlets = `-- name: CountActiveOutlets :one
SELECT count(DISTINCT id) FROM outlets WHERE business_id=$1 AND is_active AND id=ANY($2::bigint[])
`

type CountActiveOutletsParams struct {
	BusinessID int64   `json:"business_id"`
	Column2    []int64 `json:"column_2"`
}

func (q *Queries) CountActiveOutlets(ctx context.Context, arg CountActiveOutletsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOutlets, arg.BusinessID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOtherActiveAdmins = `-- name: CountOtherActiveAdmins :one
SELECT count(*) FROM users WHERE business_id=$1 AND role='ADMIN' AND is_active AND id<>$2
`

type CountOtherActiveAdminsParams struct {
	BusinessID int64 `json:"business_id"`
	ID         int64 `json:"id"`
}

func (q *Queries) CountOtherActiveAdmins(ctx context.Context, arg CountOtherActiveAdminsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherActiveAdmins, arg.BusinessID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOutlets = `-- name: CountOutlets :one
SELECT count(*) FROM outlets WHERE business_id = $1
`

func (q *Queries) CountOutlets(ctx context.Context, businessID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOutlets, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStaff = `-- name: CountStaff :one
SELECT count(*) FROM users WHERE business_id=$1
`

func (q *Queries) CountStaff(ctx context.Context, businessID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countStaff, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOutlet = `-- name: CreateOutlet :one
INSERT INTO outlets (business_id, code, name, phone, address)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, business_id, code, name, phone, address, is_active, created_at, updated_at
`

type CreateOutletParams struct {
	BusinessID int64       `json:"business_id"`
	Code       string      `json:"code"`
	Name       string      `json:"name"`
	Phone      pgtype.Text `json:"phone"`
	Address    pgtype.Text `json:"address"`
}

func (q *Queries) CreateOutlet(ctx context.Context, arg CreateOutletParams) (Outlet, error) {
	row := q.db.QueryRow(ctx, createOutlet,
		arg.BusinessID,
		arg.Code,
		arg.Name,
		arg.Phone,
		arg.Address,
	)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStaff = `-- name: CreateStaff :one
INSERT INTO users (business_id,email,full_name,password_hash,role)
VALUES ($1,$2,$3,$4,'LAUNDRY_STAFF')
RETURNING id,business_id,email,full_name,role,is_active,created_at,updated_at
`

type CreateStaffParams struct {
	BusinessID   int64  `json:"business_id"`
	Email        string `json:"email"`
	FullName     string `json:"full_name"`
	PasswordHash string `json:"password_hash"`
}

type CreateStaffRow struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Email      string             `json:"email"`
	FullName   string             `json:"full_name"`
	Role       string             `json:"role"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (CreateStaffRow, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.BusinessID,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
	)
	var i CreateStaffRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStaffOutlets = `-- name: DeleteStaffOutlets :exec
DELETE FROM user_outlets WHERE business_id=$1 AND user_id=$2
`

type DeleteStaffOutletsParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) DeleteStaffOutlets(ctx context.Context, arg DeleteStaffOutletsParams) error {
	_, err := q.db.Exec(ctx, deleteStaffOutlets, arg.BusinessID, arg.UserID)
	return err
}

const deleteStaffPermissions = `-- name: DeleteStaffPermissions :exec
DELETE FROM user_permissions WHERE business_id=$1 AND user_id=$2
`

type DeleteStaffPermissionsParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) DeleteStaffPermissions(ctx context.Context, arg DeleteStaffPermissionsParams) error {
	_, err := q.db.Exec(ctx, deleteStaffPermissions, arg.BusinessID, arg.UserID)
	return err
}

const getOutlet = `-- name: GetOutlet :one
SELECT id, business_id, code, name, phone, address, is_active, created_at, updated_at
FROM outlets WHERE business_id = $1 AND id = $2
`

type GetOutletParams struct {
	BusinessID int64 `json:"business_id"`
	ID         int64 `json:"id"`
}

func (q *Queries) GetOutlet(ctx context.Context, arg GetOutletParams) (Outlet, error) {
	row := q.db.QueryRow(ctx, getOutlet, arg.BusinessID, arg.ID)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutletForUpdate = `-- name: GetOutletForUpdate :one
SELECT id, business_id, code, name, phone, address, is_active
FROM outlets WHERE business_id = $1 AND id = $2 FOR UPDATE
`

type GetOutletForUpdateParams struct {
	BusinessID int64 `json:"business_id"`
	ID         int64 `json:"id"`
}

type GetOutletForUpdateRow struct {
	ID         int64       `json:"id"`
	BusinessID int64       `json:"business_id"`
	Code       string      `json:"code"`
	Name       string      `json:"name"`
	Phone      pgtype.Text `json:"phone"`
	Address    pgtype.Text `json:"address"`
	IsActive   bool        `json:"is_active"`
}

func (q *Queries) GetOutletForUpdate(ctx context.Context, arg GetOutletForUpdateParams) (GetOutletForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOutletForUpdate, arg.BusinessID, arg.ID)
	var i GetOutletForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.IsActive,
	)
	return i, err
}

const getStaff = `-- name: GetStaff :one
SELECT id, business_id, email, full_name, role, is_active
FROM users WHERE business_id=$1 AND id=$2
`

type GetStaffParams struct {
	BusinessID int64 `json:"business_id"`
	ID         int64 `json:"id"`
}

type GetStaffRow struct {
	ID         int64  `json:"id"`
	BusinessID int64  `json:"business_id"`
	Email      string `json:"email"`
	FullName   string `json:"full_name"`
	Role       string `json:"role"`
	IsActive   bool   `json:"is_active"`
}

func (q *Queries) GetStaff(ctx context.Context, arg GetStaffParams) (GetStaffRow, error) {
	row := q.db.QueryRow(ctx, getStaff, arg.BusinessID, arg.ID)
	var i GetStaffRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getStaffForUpdate = `-- name: GetStaffForUpdate :one
SELECT id, business_id, email, full_name, role, is_active
FROM users WHERE business_id=$1 AND id=$2 FOR UPDATE
`

type GetStaffForUpdateParams struct {
	BusinessID int64 `json:"business_id"`
	ID         int64 `json:"id"`
}

type GetStaffForUpdateRow struct {
	ID         int64  `json:"id"`
	BusinessID int64  `json:"business_id"`
	Email      string `json:"email"`
	FullName   string `json:"full_name"`
	Role       string `json:"role"`
	IsActive   bool   `json:"is_active"`
}

func (q *Queries) GetStaffForUpdate(ctx context.Context, arg GetStaffForUpdateParams) (GetStaffForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getStaffForUpdate, arg.BusinessID, arg.ID)
	var i GetStaffForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (business_id,actor_user_id,action,entity_type,entity_id,old_values,new_values,ip_address,user_agent)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertAuditLogParams struct {
	BusinessID  int64       `json:"business_id"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    pgtype.Int8 `json:"entity_id"`
	OldValues   []byte      `json:"old_values"`
	NewValues   []byte      `json:"new_values"`
	IpAddress   *netip.Addr `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.BusinessID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const listOutlets = `-- name: ListOutlets :many
SELECT id, business_id, code, name, phone, address, is_active, created_at, updated_at
FROM outlets WHERE business_id = $1 ORDER BY id LIMIT $2 OFFSET $3
`

type ListOutletsParams struct {
	BusinessID int64 `json:"business_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListOutlets(ctx context.Context, arg ListOutletsParams) ([]Outlet, error) {
	rows, err := q.db.Query(ctx, listOutlets, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outlet
	for rows.Next() {
		var i Outlet
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Code,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT code,description FROM permissions ORDER BY code
`

type ListPermissionsRow struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

func (q *Queries) ListPermissions(ctx context.Context) ([]ListPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsRow
	for rows.Next() {
		var i ListPermissionsRow
		if err := rows.Scan(&i.Code, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaff = `-- name: ListStaff :many
SELECT id, business_id, email, full_name, role, is_active, created_at, updated_at
FROM users WHERE business_id=$1 ORDER BY id LIMIT $2 OFFSET $3
`

type ListStaffParams struct {
	BusinessID int64 `json:"business_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type ListStaffRow struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Email      string             `json:"email"`
	FullName   string             `json:"full_name"`
	Role       string             `json:"role"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListStaff(ctx context.Context, arg ListStaffParams) ([]ListStaffRow, error) {
	rows, err := q.db.Query(ctx, listStaff, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffRow
	for rows.Next() {
		var i ListStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffOutletIDs = `-- name: ListStaffOutletIDs :many
SELECT uo.outlet_id FROM user_outlets uo
JOIN outlets o ON o.business_id=uo.business_id AND o.id=uo.outlet_id AND o.is_active
WHERE uo.business_id=$1 AND uo.user_id=$2 ORDER BY uo.outlet_id
`

type ListStaffOutletIDsParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) ListStaffOutletIDs(ctx context.Context, arg ListStaffOutletIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listStaffOutletIDs, arg.BusinessID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var outlet_id int64
		if err := rows.Scan(&outlet_id); err != nil {
			return nil, err
		}
		items = append(items, outlet_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffPermissionCodes = `-- name: ListStaffPermissionCodes :many
SELECT permission_code FROM user_permissions WHERE business_id=$1 AND user_id=$2 ORDER BY permission_code
`

type ListStaffPermissionCodesParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) ListStaffPermissionCodes(ctx context.Context, arg ListStaffPermissionCodesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listStaffPermissionCodes, arg.BusinessID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_code string
		if err := rows.Scan(&permission_code); err != nil {
			return nil, err
		}
		items = append(items, permission_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveBusiness = `-- name: LockActiveBusiness :one
SELECT id FROM businesses WHERE id=$1 AND is_active FOR UPDATE
`

func (q *Queries) LockActiveBusiness(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockActiveBusiness, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const lockActiveOutlets = `-- name: LockActiveOutlets :many
SELECT id FROM outlets WHERE business_id=$1 AND is_active AND id=ANY($2::bigint[]) FOR SHARE
`

type LockActiveOutletsParams struct {
	BusinessID int64   `json:"business_id"`
	Column2    []int64 `json:"column_2"`
}

func (q *Queries) LockActiveOutlets(ctx context.Context, arg LockActiveOutletsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockActiveOutlets, arg.BusinessID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutlet = `-- name: UpdateOutlet :one
UPDATE outlets SET code=$3, name=$4, phone=$5, address=$6, is_active=$7, updated_at=now()
WHERE business_id=$1 AND id=$2
RETURNING id, business_id, code, name, phone, address, is_active, created_at, updated_at
`

type UpdateOutletParams struct {
	BusinessID int64       `json:"business_id"`
	ID         int64       `json:"id"`
	Code       string      `json:"code"`
	Name       string      `json:"name"`
	Phone      pgtype.Text `json:"phone"`
	Address    pgtype.Text `json:"address"`
	IsActive   bool        `json:"is_active"`
}

func (q *Queries) UpdateOutlet(ctx context.Context, arg UpdateOutletParams) (Outlet, error) {
	row := q.db.QueryRow(ctx, updateOutlet,
		arg.BusinessID,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Phone,
		arg.Address,
		arg.IsActive,
	)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStaff = `-- name: UpdateStaff :one
UPDATE users SET full_name=$3,is_active=$4,updated_at=now()
WHERE business_id=$1 AND id=$2
RETURNING id,business_id,email,full_name,role,is_active,created_at,updated_at
`

type UpdateStaffParams struct {
	BusinessID int64  `json:"business_id"`
	ID         int64  `json:"id"`
	FullName   string `json:"full_name"`
	IsActive   bool   `json:"is_active"`
}

type UpdateStaffRow struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Email      string             `json:"email"`
	FullName   string             `json:"full_name"`
	Role       string             `json:"role"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) (UpdateStaffRow, error) {
	row := q.db.QueryRow(ctx, updateStaff,
		arg.BusinessID,
		arg.ID,
		arg.FullName,
		arg.IsActive,
	)
	var i UpdateStaffRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
