// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresql

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	OutletID    pgtype.Int8        `json:"outlet_id"`
	ActorUserID pgtype.Int8        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.Int8        `json:"entity_id"`
	OldValues   []byte             `json:"old_values"`
	NewValues   []byte             `json:"new_values"`
	IpAddress   *netip.Addr        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

type Business struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Timezone  string             `json:"timezone"`
	Phone     pgtype.Text        `json:"phone"`
	Address   pgtype.Text        `json:"address"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Name       string             `json:"name"`
	Phone      pgtype.Text        `json:"phone"`
	Email      pgtype.Text        `json:"email"`
	Address    pgtype.Text        `json:"address"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Expense struct {
	ID               int64              `json:"id"`
	BusinessID       int64              `json:"business_id"`
	OutletID         int64              `json:"outlet_id"`
	CategoryID       int64              `json:"category_id"`
	Amount           int64              `json:"amount"`
	Description      string             `json:"description"`
	ExpenseAt        pgtype.Timestamptz `json:"expense_at"`
	ReceiptReference pgtype.Text        `json:"receipt_reference"`
	CreatedBy        int64              `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ExpenseCategory struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type InvoiceCounter struct {
	BusinessID  int64              `json:"business_id"`
	OutletID    int64              `json:"outlet_id"`
	CounterDate pgtype.Date        `json:"counter_date"`
	NextNumber  int64              `json:"next_number"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID                 int64              `json:"id"`
	BusinessID         int64              `json:"business_id"`
	OutletID           int64              `json:"outlet_id"`
	CustomerID         int64              `json:"customer_id"`
	InvoiceNumber      string             `json:"invoice_number"`
	Status             string             `json:"status"`
	PaymentStatus      string             `json:"payment_status"`
	TotalAmount        int64              `json:"total_amount"`
	Notes              pgtype.Text        `json:"notes"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	DueAt              pgtype.Timestamptz `json:"due_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy        pgtype.Int8        `json:"cancelled_by"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy          int64              `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID                      int64              `json:"id"`
	BusinessID              int64              `json:"business_id"`
	OutletID                int64              `json:"outlet_id"`
	OrderID                 int64              `json:"order_id"`
	ServiceID               int64              `json:"service_id"`
	PerfumeID               pgtype.Int8        `json:"perfume_id"`
	ServiceNameSnapshot     string             `json:"service_name_snapshot"`
	ServiceUnitSnapshot     string             `json:"service_unit_snapshot"`
	UnitPriceAmountSnapshot int64              `json:"unit_price_amount_snapshot"`
	PerfumeNameSnapshot     pgtype.Text        `json:"perfume_name_snapshot"`
	Quantity                pgtype.Numeric     `json:"quantity"`
	LineTotalAmount         int64              `json:"line_total_amount"`
	Notes                   pgtype.Text        `json:"notes"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type OrderStatusHistory struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	OutletID   int64              `json:"outlet_id"`
	OrderID    int64              `json:"order_id"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	ChangedBy  int64              `json:"changed_by"`
	Notes      pgtype.Text        `json:"notes"`
	ChangedAt  pgtype.Timestamptz `json:"changed_at"`
}

type Outlet struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Code       string             `json:"code"`
	Name       string             `json:"name"`
	Phone      pgtype.Text        `json:"phone"`
	Address    pgtype.Text        `json:"address"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID                int64              `json:"id"`
	BusinessID        int64              `json:"business_id"`
	OutletID          int64              `json:"outlet_id"`
	OrderID           int64              `json:"order_id"`
	Amount            int64              `json:"amount"`
	Method            string             `json:"method"`
	Status            string             `json:"status"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Notes             pgtype.Text        `json:"notes"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
	VoidedAt          pgtype.Timestamptz `json:"voided_at"`
	VoidedBy          pgtype.Int8        `json:"voided_by"`
	VoidReason        pgtype.Text        `json:"void_reason"`
	CreatedBy         int64              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PaymentRefund struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	OutletID   int64              `json:"outlet_id"`
	OrderID    int64              `json:"order_id"`
	PaymentID  int64              `json:"payment_id"`
	Amount     int64              `json:"amount"`
	Reason     string             `json:"reason"`
	RefundedBy int64              `json:"refunded_by"`
	RefundedAt pgtype.Timestamptz `json:"refunded_at"`
}

type Perfume struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Permission struct {
	Code        string             `json:"code"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ReceiptTemplate struct {
	ID                      int64              `json:"id"`
	BusinessID              int64              `json:"business_id"`
	OutletID                int64              `json:"outlet_id"`
	Name                    string             `json:"name"`
	HeaderText              pgtype.Text        `json:"header_text"`
	FooterText              pgtype.Text        `json:"footer_text"`
	WhatsappMessageTemplate pgtype.Text        `json:"whatsapp_message_template"`
	PaperWidthMm            int32              `json:"paper_width_mm"`
	IsDefault               bool               `json:"is_default"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

type RefreshToken struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Service struct {
	ID                       int64              `json:"id"`
	BusinessID               int64              `json:"business_id"`
	Name                     string             `json:"name"`
	Unit                     string             `json:"unit"`
	UnitPriceAmount          int64              `json:"unit_price_amount"`
	EstimatedDurationMinutes int32              `json:"estimated_duration_minutes"`
	IsActive                 bool               `json:"is_active"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID           int64              `json:"id"`
	BusinessID   int64              `json:"business_id"`
	Email        string             `json:"email"`
	FullName     string             `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserOutlet struct {
	BusinessID int64              `json:"business_id"`
	UserID     int64              `json:"user_id"`
	OutletID   int64              `json:"outlet_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type UserPermission struct {
	BusinessID     int64              `json:"business_id"`
	UserID         int64              `json:"user_id"`
	PermissionCode string             `json:"permission_code"`
	GrantedBy      int64              `json:"granted_by"`
	GrantedAt      pgtype.Timestamptz `json:"granted_at"`
}
