// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresql

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	OutletID    pgtype.Int8        `json:"outlet_id"`
	ActorUserID pgtype.Int8        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.Int8        `json:"entity_id"`
	OldValues   []byte             `json:"old_values"`
	NewValues   []byte             `json:"new_values"`
	IpAddress   *netip.Addr        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

// Root tenant. All business-owned records are scoped to one business.
type Business struct {
	// Stable BIGINT tenant identifier.
	ID   int64  `json:"id"`
	Name string `json:"name"`
	// Business timezone; the application currently permits only Asia/Jakarta.
	Timezone string      `json:"timezone"`
	Phone    pgtype.Text `json:"phone"`
	Address  pgtype.Text `json:"address"`
	// False prevents the tenant from being used without deleting its records.
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	Name       string             `json:"name"`
	Phone      pgtype.Text        `json:"phone"`
	Email      pgtype.Text        `json:"email"`
	Address    pgtype.Text        `json:"address"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Expense struct {
	ID               int64              `json:"id"`
	BusinessID       int64              `json:"business_id"`
	OutletID         int64              `json:"outlet_id"`
	CategoryID       int64              `json:"category_id"`
	Amount           int64              `json:"amount"`
	Description      string             `json:"description"`
	ExpenseAt        pgtype.Timestamptz `json:"expense_at"`
	ReceiptReference pgtype.Text        `json:"receipt_reference"`
	CreatedBy        int64              `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ExpenseCategory struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type InvoiceCounter struct {
	BusinessID  int64              `json:"business_id"`
	OutletID    int64              `json:"outlet_id"`
	CounterDate pgtype.Date        `json:"counter_date"`
	NextNumber  int64              `json:"next_number"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID                 int64              `json:"id"`
	BusinessID         int64              `json:"business_id"`
	OutletID           int64              `json:"outlet_id"`
	CustomerID         int64              `json:"customer_id"`
	InvoiceNumber      string             `json:"invoice_number"`
	Status             string             `json:"status"`
	PaymentStatus      string             `json:"payment_status"`
	TotalAmount        int64              `json:"total_amount"`
	Notes              pgtype.Text        `json:"notes"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	DueAt              pgtype.Timestamptz `json:"due_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy        pgtype.Int8        `json:"cancelled_by"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy          int64              `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	// Client-supplied request idempotency key, unique within a business and outlet.
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	// SHA-256 hash of the canonical decoded order creation payload used to reject key reuse with a different payload.
	RequestHash []byte `json:"request_hash"`
}

type OrderItem struct {
	ID                      int64              `json:"id"`
	BusinessID              int64              `json:"business_id"`
	OutletID                int64              `json:"outlet_id"`
	OrderID                 int64              `json:"order_id"`
	ServiceID               int64              `json:"service_id"`
	PerfumeID               pgtype.Int8        `json:"perfume_id"`
	ServiceNameSnapshot     string             `json:"service_name_snapshot"`
	ServiceUnitSnapshot     string             `json:"service_unit_snapshot"`
	UnitPriceAmountSnapshot int64              `json:"unit_price_amount_snapshot"`
	PerfumeNameSnapshot     pgtype.Text        `json:"perfume_name_snapshot"`
	Quantity                pgtype.Numeric     `json:"quantity"`
	LineTotalAmount         int64              `json:"line_total_amount"`
	Notes                   pgtype.Text        `json:"notes"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type OrderStatusHistory struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	OutletID   int64              `json:"outlet_id"`
	OrderID    int64              `json:"order_id"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	ChangedBy  int64              `json:"changed_by"`
	Notes      pgtype.Text        `json:"notes"`
	ChangedAt  pgtype.Timestamptz `json:"changed_at"`
}

// A physical or operational location owned by exactly one business.
type Outlet struct {
	ID int64 `json:"id"`
	// Tenant owner; paired with id by tenant-aware foreign keys.
	BusinessID int64 `json:"business_id"`
	// Business-local outlet code, unique within business_id.
	Code    string      `json:"code"`
	Name    string      `json:"name"`
	Phone   pgtype.Text `json:"phone"`
	Address pgtype.Text `json:"address"`
	// False disables new outlet activity without deleting historical records.
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID         int64 `json:"id"`
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	OrderID    int64 `json:"order_id"`
	// Whole rupiah credited to the order; for cash, tender above the outstanding balance is excluded and returned as change.
	Amount int64 `json:"amount"`
	// Payment method constrained to CASH, BCA_TRANSFER, or QRIS; BCA_TRANSFER is displayed as BCA Transfer in UI.
	Method            string             `json:"method"`
	Status            string             `json:"status"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Notes             pgtype.Text        `json:"notes"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
	VoidedAt          pgtype.Timestamptz `json:"voided_at"`
	VoidedBy          pgtype.Int8        `json:"voided_by"`
	VoidReason        pgtype.Text        `json:"void_reason"`
	CreatedBy         int64              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	// Client retry key scoped to business, outlet, and order; NULL for legacy rows.
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	// SHA-256 hash of the normalized payment request used to detect idempotency-key payload conflicts.
	RequestHash []byte `json:"request_hash"`
}

type PaymentRefund struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	OutletID   int64              `json:"outlet_id"`
	OrderID    int64              `json:"order_id"`
	PaymentID  int64              `json:"payment_id"`
	Amount     int64              `json:"amount"`
	Reason     string             `json:"reason"`
	RefundedBy int64              `json:"refunded_by"`
	RefundedAt pgtype.Timestamptz `json:"refunded_at"`
}

type Perfume struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

// Global catalog of permission codes; grants remain tenant-scoped in user_permissions.
type Permission struct {
	// Stable uppercase permission identifier, not a tenant identifier.
	Code        string             `json:"code"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ReceiptTemplate struct {
	ID                      int64              `json:"id"`
	BusinessID              int64              `json:"business_id"`
	OutletID                int64              `json:"outlet_id"`
	Name                    string             `json:"name"`
	HeaderText              pgtype.Text        `json:"header_text"`
	FooterText              pgtype.Text        `json:"footer_text"`
	WhatsappMessageTemplate pgtype.Text        `json:"whatsapp_message_template"`
	PaperWidthMm            int32              `json:"paper_width_mm"`
	IsDefault               bool               `json:"is_default"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

// Revocable refresh sessions. token_hash stores a one-way hash, never a raw refresh token.
type RefreshToken struct {
	ID int64 `json:"id"`
	// Tenant key paired with user_id for a tenant-aware session foreign key.
	BusinessID int64 `json:"business_id"`
	// Session owner; must belong to business_id.
	UserID int64 `json:"user_id"`
	// Unique one-way hash of the opaque refresh token.
	TokenHash string `json:"token_hash"`
	// Exclusive refresh-session expiry timestamp.
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// Token consumed by rotation or revoked by logout; retained for replay detection.
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Stable family across refresh rotations; historical token hashes remain stored for replay detection.
	FamilyID int64 `json:"family_id"`
}

// Business-shared service catalog. A service applies to every outlet in its business; outlet-specific pricing is not modelled.
type Service struct {
	ID int64 `json:"id"`
	// Tenant owner. There is intentionally no outlet_id because services are shared across the business.
	BusinessID int64  `json:"business_id"`
	Name       string `json:"name"`
	// Measurement type constrained to KILOGRAM, PIECE, METER, or SQUARE_METER.
	Unit                     string             `json:"unit"`
	UnitPriceAmount          int64              `json:"unit_price_amount"`
	EstimatedDurationMinutes int32              `json:"estimated_duration_minutes"`
	IsActive                 bool               `json:"is_active"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	// Optional business-shared service description; changing it does not rewrite historical order-item snapshots.
	Description pgtype.Text `json:"description"`
}

// Stable session lineage; refresh rotation and logout serialize on this row.
type SessionFamily struct {
	ID         int64              `json:"id"`
	BusinessID int64              `json:"business_id"`
	UserID     int64              `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	// Revokes every access and refresh token in this family, including consumed descendants.
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// Authenticated account owned by one business; it is not a global operator account.
type User struct {
	ID int64 `json:"id"`
	// Tenant owner; prevents a user from belonging to multiple businesses.
	BusinessID int64 `json:"business_id"`
	// Case-insensitively unique login identifier; unique globally by design so login needs no business selector.
	Email    string `json:"email"`
	FullName string `json:"full_name"`
	// One-way password hash only; plaintext passwords and reversible secrets are never stored.
	PasswordHash string `json:"password_hash"`
	// Coarse business role, constrained to ADMIN or LAUNDRY_STAFF.
	Role string `json:"role"`
	// False blocks authentication and authorization while preserving history.
	IsActive    bool               `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Tenant-safe assignment of a user to an outlet in the same business.
type UserOutlet struct {
	// Shared tenant key required by both user and outlet foreign keys.
	BusinessID int64 `json:"business_id"`
	// Assigned user; must belong to business_id.
	UserID int64 `json:"user_id"`
	// Assigned outlet; must belong to business_id.
	OutletID   int64              `json:"outlet_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

// Explicit tenant-scoped permission grant. Authorization still validates actor role and outlet scope.
type UserPermission struct {
	// Shared tenant key for recipient and grantor foreign keys.
	BusinessID int64 `json:"business_id"`
	// Permission recipient; must belong to business_id.
	UserID         int64  `json:"user_id"`
	PermissionCode string `json:"permission_code"`
	// Granting user; must belong to business_id. Whether the actor may grant is enforced by application authorization.
	GrantedBy int64              `json:"granted_by"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
}
