// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package postgresql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const allocateInvoiceNumber = `-- name: AllocateInvoiceNumber :one
INSERT INTO invoice_counters (business_id, outlet_id, counter_date, next_number)
VALUES ($1, $2, $3, 2::bigint)
ON CONFLICT (business_id, outlet_id, counter_date)
DO UPDATE SET next_number = invoice_counters.next_number + 1, updated_at = now()
RETURNING counter_date, (next_number - 1)::bigint AS invoice_sequence
`

type AllocateInvoiceNumberParams struct {
	BusinessID  int64       `json:"business_id"`
	OutletID    int64       `json:"outlet_id"`
	CounterDate pgtype.Date `json:"counter_date"`
}

type AllocateInvoiceNumberRow struct {
	CounterDate     pgtype.Date `json:"counter_date"`
	InvoiceSequence int64       `json:"invoice_sequence"`
}

func (q *Queries) AllocateInvoiceNumber(ctx context.Context, arg AllocateInvoiceNumberParams) (AllocateInvoiceNumberRow, error) {
	row := q.db.QueryRow(ctx, allocateInvoiceNumber, arg.BusinessID, arg.OutletID, arg.CounterDate)
	var i AllocateInvoiceNumberRow
	err := row.Scan(&i.CounterDate, &i.InvoiceSequence)
	return i, err
}

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders SET status='CANCELLED', cancelled_at=now(), cancelled_by=$1,
    cancellation_reason=$2, deleted_at=now(), updated_at=now()
WHERE business_id=$3 AND id=$4
RETURNING id, business_id, outlet_id, status, payment_status, cancelled_at, cancelled_by,
          cancellation_reason, deleted_at, updated_at
`

type CancelOrderParams struct {
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Reason      pgtype.Text `json:"reason"`
	BusinessID  int64       `json:"business_id"`
	OrderID     int64       `json:"order_id"`
}

type CancelOrderRow struct {
	ID                 int64              `json:"id"`
	BusinessID         int64              `json:"business_id"`
	OutletID           int64              `json:"outlet_id"`
	Status             string             `json:"status"`
	PaymentStatus      string             `json:"payment_status"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy        pgtype.Int8        `json:"cancelled_by"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (CancelOrderRow, error) {
	row := q.db.QueryRow(ctx, cancelOrder,
		arg.ActorUserID,
		arg.Reason,
		arg.BusinessID,
		arg.OrderID,
	)
	var i CancelOrderRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.Status,
		&i.PaymentStatus,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOrders = `-- name: CountOrders :one
SELECT count(*)
FROM orders
WHERE business_id = $1
  AND ($2::boolean OR outlet_id = ANY($3::bigint[]))
  AND ($4::bigint IS NULL OR outlet_id = $4::bigint)
  AND ($5::text IS NULL OR status = $5::text)
`

type CountOrdersParams struct {
	BusinessID int64       `json:"business_id"`
	IsAdmin    bool        `json:"is_admin"`
	OutletIds  []int64     `json:"outlet_ids"`
	OutletID   pgtype.Int8 `json:"outlet_id"`
	Status     pgtype.Text `json:"status"`
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders,
		arg.BusinessID,
		arg.IsAdmin,
		arg.OutletIds,
		arg.OutletID,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInitialOrderStatus = `-- name: CreateInitialOrderStatus :exec
INSERT INTO order_status_history (business_id, outlet_id, order_id, from_status, to_status, changed_by)
VALUES ($1, $2, $3, NULL, 'RECEIVED', $4)
`

type CreateInitialOrderStatusParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	OrderID    int64 `json:"order_id"`
	ChangedBy  int64 `json:"changed_by"`
}

func (q *Queries) CreateInitialOrderStatus(ctx context.Context, arg CreateInitialOrderStatusParams) error {
	_, err := q.db.Exec(ctx, createInitialOrderStatus,
		arg.BusinessID,
		arg.OutletID,
		arg.OrderID,
		arg.ChangedBy,
	)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    business_id, outlet_id, customer_id, invoice_number, total_amount, notes,
    received_at, due_at, created_by, idempotency_key, request_hash
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11
)
RETURNING id, business_id, outlet_id, customer_id, invoice_number, status, payment_status,
          total_amount, notes, received_at, due_at, created_by, created_at, updated_at
`

type CreateOrderParams struct {
	BusinessID     int64              `json:"business_id"`
	OutletID       int64              `json:"outlet_id"`
	CustomerID     int64              `json:"customer_id"`
	InvoiceNumber  string             `json:"invoice_number"`
	TotalAmount    int64              `json:"total_amount"`
	Notes          pgtype.Text        `json:"notes"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	CreatedBy      int64              `json:"created_by"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	RequestHash    []byte             `json:"request_hash"`
}

type CreateOrderRow struct {
	ID            int64              `json:"id"`
	BusinessID    int64              `json:"business_id"`
	OutletID      int64              `json:"outlet_id"`
	CustomerID    int64              `json:"customer_id"`
	InvoiceNumber string             `json:"invoice_number"`
	Status        string             `json:"status"`
	PaymentStatus string             `json:"payment_status"`
	TotalAmount   int64              `json:"total_amount"`
	Notes         pgtype.Text        `json:"notes"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	DueAt         pgtype.Timestamptz `json:"due_at"`
	CreatedBy     int64              `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.BusinessID,
		arg.OutletID,
		arg.CustomerID,
		arg.InvoiceNumber,
		arg.TotalAmount,
		arg.Notes,
		arg.ReceivedAt,
		arg.DueAt,
		arg.CreatedBy,
		arg.IdempotencyKey,
		arg.RequestHash,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.CustomerID,
		&i.InvoiceNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.Notes,
		&i.ReceivedAt,
		&i.DueAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (
    business_id, outlet_id, order_id, service_id, perfume_id,
    service_name_snapshot, service_unit_snapshot, unit_price_amount_snapshot,
    perfume_name_snapshot, quantity, line_total_amount, notes
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12
)
`

type CreateOrderItemParams struct {
	BusinessID              int64          `json:"business_id"`
	OutletID                int64          `json:"outlet_id"`
	OrderID                 int64          `json:"order_id"`
	ServiceID               int64          `json:"service_id"`
	PerfumeID               pgtype.Int8    `json:"perfume_id"`
	ServiceNameSnapshot     string         `json:"service_name_snapshot"`
	ServiceUnitSnapshot     string         `json:"service_unit_snapshot"`
	UnitPriceAmountSnapshot int64          `json:"unit_price_amount_snapshot"`
	PerfumeNameSnapshot     pgtype.Text    `json:"perfume_name_snapshot"`
	Quantity                pgtype.Numeric `json:"quantity"`
	LineTotalAmount         int64          `json:"line_total_amount"`
	Notes                   pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.BusinessID,
		arg.OutletID,
		arg.OrderID,
		arg.ServiceID,
		arg.PerfumeID,
		arg.ServiceNameSnapshot,
		arg.ServiceUnitSnapshot,
		arg.UnitPriceAmountSnapshot,
		arg.PerfumeNameSnapshot,
		arg.Quantity,
		arg.LineTotalAmount,
		arg.Notes,
	)
	return err
}

const getActiveOrderCustomer = `-- name: GetActiveOrderCustomer :one
SELECT id, name
FROM customers
WHERE business_id = $1 AND id = $2
  AND deleted_at IS NULL
FOR SHARE
`

type GetActiveOrderCustomerParams struct {
	BusinessID int64 `json:"business_id"`
	CustomerID int64 `json:"customer_id"`
}

type GetActiveOrderCustomerRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetActiveOrderCustomer(ctx context.Context, arg GetActiveOrderCustomerParams) (GetActiveOrderCustomerRow, error) {
	row := q.db.QueryRow(ctx, getActiveOrderCustomer, arg.BusinessID, arg.CustomerID)
	var i GetActiveOrderCustomerRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getActiveOrderOutlet = `-- name: GetActiveOrderOutlet :one
SELECT id, code, name
FROM outlets
WHERE business_id = $1 AND id = $2 AND is_active
FOR SHARE
`

type GetActiveOrderOutletParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
}

type GetActiveOrderOutletRow struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) GetActiveOrderOutlet(ctx context.Context, arg GetActiveOrderOutletParams) (GetActiveOrderOutletRow, error) {
	row := q.db.QueryRow(ctx, getActiveOrderOutlet, arg.BusinessID, arg.OutletID)
	var i GetActiveOrderOutletRow
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const getActiveOrderPerfume = `-- name: GetActiveOrderPerfume :one
SELECT id, business_id, name
FROM perfumes
WHERE business_id = $1 AND id = $2
  AND is_active AND deleted_at IS NULL
FOR SHARE
`

type GetActiveOrderPerfumeParams struct {
	BusinessID int64 `json:"business_id"`
	PerfumeID  int64 `json:"perfume_id"`
}

type GetActiveOrderPerfumeRow struct {
	ID         int64  `json:"id"`
	BusinessID int64  `json:"business_id"`
	Name       string `json:"name"`
}

func (q *Queries) GetActiveOrderPerfume(ctx context.Context, arg GetActiveOrderPerfumeParams) (GetActiveOrderPerfumeRow, error) {
	row := q.db.QueryRow(ctx, getActiveOrderPerfume, arg.BusinessID, arg.PerfumeID)
	var i GetActiveOrderPerfumeRow
	err := row.Scan(&i.ID, &i.BusinessID, &i.Name)
	return i, err
}

const getActiveOrderService = `-- name: GetActiveOrderService :one
SELECT id, business_id, name, unit, unit_price_amount
FROM services
WHERE business_id = $1 AND id = $2
  AND is_active AND deleted_at IS NULL
FOR SHARE
`

type GetActiveOrderServiceParams struct {
	BusinessID int64 `json:"business_id"`
	ServiceID  int64 `json:"service_id"`
}

type GetActiveOrderServiceRow struct {
	ID              int64  `json:"id"`
	BusinessID      int64  `json:"business_id"`
	Name            string `json:"name"`
	Unit            string `json:"unit"`
	UnitPriceAmount int64  `json:"unit_price_amount"`
}

func (q *Queries) GetActiveOrderService(ctx context.Context, arg GetActiveOrderServiceParams) (GetActiveOrderServiceRow, error) {
	row := q.db.QueryRow(ctx, getActiveOrderService, arg.BusinessID, arg.ServiceID)
	var i GetActiveOrderServiceRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Unit,
		&i.UnitPriceAmount,
	)
	return i, err
}

const getActiveStaffOrderOutlet = `-- name: GetActiveStaffOrderOutlet :one
SELECT u.user_id
FROM user_outlets AS u
JOIN outlets AS o ON o.business_id = u.business_id AND o.id = u.outlet_id
WHERE u.business_id = $1 AND u.user_id = $2
  AND u.outlet_id = $3 AND o.is_active
FOR SHARE OF u, o
`

type GetActiveStaffOrderOutletParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
	OutletID   int64 `json:"outlet_id"`
}

func (q *Queries) GetActiveStaffOrderOutlet(ctx context.Context, arg GetActiveStaffOrderOutletParams) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveStaffOrderOutlet, arg.BusinessID, arg.UserID, arg.OutletID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, business_id, outlet_id, customer_id, invoice_number, status, payment_status,
       total_amount, notes, received_at, due_at, created_by, created_at, updated_at
FROM orders
WHERE business_id = $1 AND id = $2
  AND ($3::boolean OR outlet_id = ANY($4::bigint[]))
`

type GetOrderParams struct {
	BusinessID int64   `json:"business_id"`
	OrderID    int64   `json:"order_id"`
	IsAdmin    bool    `json:"is_admin"`
	OutletIds  []int64 `json:"outlet_ids"`
}

type GetOrderRow struct {
	ID            int64              `json:"id"`
	BusinessID    int64              `json:"business_id"`
	OutletID      int64              `json:"outlet_id"`
	CustomerID    int64              `json:"customer_id"`
	InvoiceNumber string             `json:"invoice_number"`
	Status        string             `json:"status"`
	PaymentStatus string             `json:"payment_status"`
	TotalAmount   int64              `json:"total_amount"`
	Notes         pgtype.Text        `json:"notes"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	DueAt         pgtype.Timestamptz `json:"due_at"`
	CreatedBy     int64              `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder,
		arg.BusinessID,
		arg.OrderID,
		arg.IsAdmin,
		arg.OutletIds,
	)
	var i GetOrderRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.CustomerID,
		&i.InvoiceNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.Notes,
		&i.ReceivedAt,
		&i.DueAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
SELECT id, business_id, outlet_id, customer_id, invoice_number, status, payment_status,
       total_amount, notes, received_at, due_at, created_by, created_at, updated_at, request_hash
FROM orders
WHERE business_id = $1 AND outlet_id = $2
  AND idempotency_key = $3
`

type GetOrderByIdempotencyKeyParams struct {
	BusinessID     int64       `json:"business_id"`
	OutletID       int64       `json:"outlet_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

type GetOrderByIdempotencyKeyRow struct {
	ID            int64              `json:"id"`
	BusinessID    int64              `json:"business_id"`
	OutletID      int64              `json:"outlet_id"`
	CustomerID    int64              `json:"customer_id"`
	InvoiceNumber string             `json:"invoice_number"`
	Status        string             `json:"status"`
	PaymentStatus string             `json:"payment_status"`
	TotalAmount   int64              `json:"total_amount"`
	Notes         pgtype.Text        `json:"notes"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	DueAt         pgtype.Timestamptz `json:"due_at"`
	CreatedBy     int64              `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	RequestHash   []byte             `json:"request_hash"`
}

func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, arg GetOrderByIdempotencyKeyParams) (GetOrderByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, arg.BusinessID, arg.OutletID, arg.IdempotencyKey)
	var i GetOrderByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.CustomerID,
		&i.InvoiceNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.Notes,
		&i.ReceivedAt,
		&i.DueAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestHash,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT o.id, o.business_id, o.outlet_id, o.status, o.payment_status, o.total_amount, o.completed_at,
       o.cancelled_at, o.cancelled_by, o.cancellation_reason, o.deleted_at
FROM orders AS o
JOIN outlets AS outlet ON outlet.business_id=o.business_id AND outlet.id=o.outlet_id AND outlet.is_active
JOIN users AS current_actor ON current_actor.business_id=o.business_id
  AND current_actor.id=$1 AND current_actor.is_active
  AND current_actor.role=CASE WHEN $2::boolean THEN 'ADMIN' ELSE 'LAUNDRY_STAFF' END
WHERE o.business_id=$3 AND o.id=$4
  AND ($2::boolean OR EXISTS (
      SELECT 1 FROM user_outlets AS assignment
      WHERE assignment.business_id=o.business_id AND assignment.outlet_id=o.outlet_id
        AND assignment.user_id=$1
  ))
FOR UPDATE OF o, outlet, current_actor
`

type GetOrderForUpdateParams struct {
	UserID     int64 `json:"user_id"`
	IsAdmin    bool  `json:"is_admin"`
	BusinessID int64 `json:"business_id"`
	OrderID    int64 `json:"order_id"`
}

type GetOrderForUpdateRow struct {
	ID                 int64              `json:"id"`
	BusinessID         int64              `json:"business_id"`
	OutletID           int64              `json:"outlet_id"`
	Status             string             `json:"status"`
	PaymentStatus      string             `json:"payment_status"`
	TotalAmount        int64              `json:"total_amount"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy        pgtype.Int8        `json:"cancelled_by"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetOrderForUpdate(ctx context.Context, arg GetOrderForUpdateParams) (GetOrderForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate,
		arg.UserID,
		arg.IsAdmin,
		arg.BusinessID,
		arg.OrderID,
	)
	var i GetOrderForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.DeletedAt,
	)
	return i, err
}

const getOrderTime = `-- name: GetOrderTime :one
SELECT now()::timestamptz AS received_at, CURRENT_DATE::date AS counter_date
`

type GetOrderTimeRow struct {
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
	CounterDate pgtype.Date        `json:"counter_date"`
}

func (q *Queries) GetOrderTime(ctx context.Context) (GetOrderTimeRow, error) {
	row := q.db.QueryRow(ctx, getOrderTime)
	var i GetOrderTimeRow
	err := row.Scan(&i.ReceivedAt, &i.CounterDate)
	return i, err
}

const insertOrderAuditLog = `-- name: InsertOrderAuditLog :exec
INSERT INTO audit_logs (business_id, outlet_id, actor_user_id, action, entity_type, entity_id, new_values, ip_address, user_agent)
VALUES ($1, $2, $3, 'ORDER_CREATED', 'order', $4,
        $5, $6, $7)
`

type InsertOrderAuditLogParams struct {
	BusinessID  int64       `json:"business_id"`
	OutletID    pgtype.Int8 `json:"outlet_id"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	OrderID     pgtype.Int8 `json:"order_id"`
	NewValues   []byte      `json:"new_values"`
	IpAddress   *netip.Addr `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertOrderAuditLog(ctx context.Context, arg InsertOrderAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertOrderAuditLog,
		arg.BusinessID,
		arg.OutletID,
		arg.ActorUserID,
		arg.OrderID,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const insertOrderLifecycleAuditLog = `-- name: InsertOrderLifecycleAuditLog :exec
INSERT INTO audit_logs (business_id, outlet_id, actor_user_id, action, entity_type, entity_id, old_values, new_values, ip_address, user_agent)
VALUES ($1, $2, $3, $4, 'order',
        $5, $6, $7, $8, $9)
`

type InsertOrderLifecycleAuditLogParams struct {
	BusinessID  int64       `json:"business_id"`
	OutletID    pgtype.Int8 `json:"outlet_id"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	OrderID     pgtype.Int8 `json:"order_id"`
	OldValues   []byte      `json:"old_values"`
	NewValues   []byte      `json:"new_values"`
	IpAddress   *netip.Addr `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertOrderLifecycleAuditLog(ctx context.Context, arg InsertOrderLifecycleAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertOrderLifecycleAuditLog,
		arg.BusinessID,
		arg.OutletID,
		arg.ActorUserID,
		arg.Action,
		arg.OrderID,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const insertOrderStatusHistory = `-- name: InsertOrderStatusHistory :exec
INSERT INTO order_status_history (business_id, outlet_id, order_id, from_status, to_status, changed_by, notes)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
`

type InsertOrderStatusHistoryParams struct {
	BusinessID int64       `json:"business_id"`
	OutletID   int64       `json:"outlet_id"`
	OrderID    int64       `json:"order_id"`
	FromStatus pgtype.Text `json:"from_status"`
	ToStatus   string      `json:"to_status"`
	ChangedBy  int64       `json:"changed_by"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) InsertOrderStatusHistory(ctx context.Context, arg InsertOrderStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, insertOrderStatusHistory,
		arg.BusinessID,
		arg.OutletID,
		arg.OrderID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedBy,
		arg.Notes,
	)
	return err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, service_id, perfume_id, service_name_snapshot, service_unit_snapshot,
       unit_price_amount_snapshot, perfume_name_snapshot, quantity::text AS quantity,
       line_total_amount, notes
FROM order_items
WHERE business_id = $1 AND outlet_id = $2 AND order_id = $3
ORDER BY id
`

type ListOrderItemsParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	OrderID    int64 `json:"order_id"`
}

type ListOrderItemsRow struct {
	ID                      int64       `json:"id"`
	ServiceID               int64       `json:"service_id"`
	PerfumeID               pgtype.Int8 `json:"perfume_id"`
	ServiceNameSnapshot     string      `json:"service_name_snapshot"`
	ServiceUnitSnapshot     string      `json:"service_unit_snapshot"`
	UnitPriceAmountSnapshot int64       `json:"unit_price_amount_snapshot"`
	PerfumeNameSnapshot     pgtype.Text `json:"perfume_name_snapshot"`
	Quantity                string      `json:"quantity"`
	LineTotalAmount         int64       `json:"line_total_amount"`
	Notes                   pgtype.Text `json:"notes"`
}

func (q *Queries) ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]ListOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItems, arg.BusinessID, arg.OutletID, arg.OrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsRow
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.PerfumeID,
			&i.ServiceNameSnapshot,
			&i.ServiceUnitSnapshot,
			&i.UnitPriceAmountSnapshot,
			&i.PerfumeNameSnapshot,
			&i.Quantity,
			&i.LineTotalAmount,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderStatusHistory = `-- name: ListOrderStatusHistory :many
SELECT h.id, h.from_status, h.to_status, h.changed_by, u.full_name AS changed_by_name,
       h.notes, h.changed_at
FROM order_status_history AS h
JOIN users AS u ON u.business_id=h.business_id AND u.id=h.changed_by
WHERE h.business_id=$1 AND h.outlet_id=$2
  AND h.order_id=$3
ORDER BY h.changed_at, h.id
`

type ListOrderStatusHistoryParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	OrderID    int64 `json:"order_id"`
}

type ListOrderStatusHistoryRow struct {
	ID            int64              `json:"id"`
	FromStatus    pgtype.Text        `json:"from_status"`
	ToStatus      string             `json:"to_status"`
	ChangedBy     int64              `json:"changed_by"`
	ChangedByName string             `json:"changed_by_name"`
	Notes         pgtype.Text        `json:"notes"`
	ChangedAt     pgtype.Timestamptz `json:"changed_at"`
}

func (q *Queries) ListOrderStatusHistory(ctx context.Context, arg ListOrderStatusHistoryParams) ([]ListOrderStatusHistoryRow, error) {
	rows, err := q.db.Query(ctx, listOrderStatusHistory, arg.BusinessID, arg.OutletID, arg.OrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderStatusHistoryRow
	for rows.Next() {
		var i ListOrderStatusHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedBy,
			&i.ChangedByName,
			&i.Notes,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, business_id, outlet_id, customer_id, invoice_number, status, payment_status,
       total_amount, notes, received_at, due_at, created_by, created_at, updated_at
FROM orders
WHERE business_id = $1
  AND ($2::boolean OR outlet_id = ANY($3::bigint[]))
  AND ($4::bigint IS NULL OR outlet_id = $4::bigint)
  AND ($5::text IS NULL OR status = $5::text)
ORDER BY created_at DESC, id DESC
LIMIT $7 OFFSET $6
`

type ListOrdersParams struct {
	BusinessID int64       `json:"business_id"`
	IsAdmin    bool        `json:"is_admin"`
	OutletIds  []int64     `json:"outlet_ids"`
	OutletID   pgtype.Int8 `json:"outlet_id"`
	Status     pgtype.Text `json:"status"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListOrdersRow struct {
	ID            int64              `json:"id"`
	BusinessID    int64              `json:"business_id"`
	OutletID      int64              `json:"outlet_id"`
	CustomerID    int64              `json:"customer_id"`
	InvoiceNumber string             `json:"invoice_number"`
	Status        string             `json:"status"`
	PaymentStatus string             `json:"payment_status"`
	TotalAmount   int64              `json:"total_amount"`
	Notes         pgtype.Text        `json:"notes"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	DueAt         pgtype.Timestamptz `json:"due_at"`
	CreatedBy     int64              `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.BusinessID,
		arg.IsAdmin,
		arg.OutletIds,
		arg.OutletID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.OutletID,
			&i.CustomerID,
			&i.InvoiceNumber,
			&i.Status,
			&i.PaymentStatus,
			&i.TotalAmount,
			&i.Notes,
			&i.ReceivedAt,
			&i.DueAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCurrentOrderOutletAssignment = `-- name: LockCurrentOrderOutletAssignment :one
SELECT user_id FROM user_outlets
WHERE business_id=$1 AND user_id=$2 AND outlet_id=$3
FOR SHARE
`

type LockCurrentOrderOutletAssignmentParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
	OutletID   int64 `json:"outlet_id"`
}

func (q *Queries) LockCurrentOrderOutletAssignment(ctx context.Context, arg LockCurrentOrderOutletAssignmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockCurrentOrderOutletAssignment, arg.BusinessID, arg.UserID, arg.OutletID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const lockOrderIdempotency = `-- name: LockOrderIdempotency :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockOrderIdempotency(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, lockOrderIdempotency, lockKey)
	return err
}

const transitionOrderStatus = `-- name: TransitionOrderStatus :one
UPDATE orders SET status=$1,
    completed_at=CASE WHEN $1::text='COMPLETED' THEN now() ELSE NULL END,
    updated_at=now()
WHERE business_id=$2 AND id=$3
RETURNING id, business_id, outlet_id, status, payment_status, completed_at, updated_at
`

type TransitionOrderStatusParams struct {
	ToStatus   string `json:"to_status"`
	BusinessID int64  `json:"business_id"`
	OrderID    int64  `json:"order_id"`
}

type TransitionOrderStatusRow struct {
	ID            int64              `json:"id"`
	BusinessID    int64              `json:"business_id"`
	OutletID      int64              `json:"outlet_id"`
	Status        string             `json:"status"`
	PaymentStatus string             `json:"payment_status"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) TransitionOrderStatus(ctx context.Context, arg TransitionOrderStatusParams) (TransitionOrderStatusRow, error) {
	row := q.db.QueryRow(ctx, transitionOrderStatus, arg.ToStatus, arg.BusinessID, arg.OrderID)
	var i TransitionOrderStatusRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.Status,
		&i.PaymentStatus,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
