// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package postgresql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrderPaymentRefunds = `-- name: CountOrderPaymentRefunds :one
SELECT count(*) FROM payment_refunds
WHERE business_id=$1 AND outlet_id=$2 AND order_id=$3
`

type CountOrderPaymentRefundsParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	OrderID    int64 `json:"order_id"`
}

func (q *Queries) CountOrderPaymentRefunds(ctx context.Context, arg CountOrderPaymentRefundsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderPaymentRefunds, arg.BusinessID, arg.OutletID, arg.OrderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrderPayments = `-- name: CountOrderPayments :one
SELECT count(*) FROM payments
WHERE business_id=$1 AND outlet_id=$2 AND order_id=$3
`

type CountOrderPaymentsParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	OrderID    int64 `json:"order_id"`
}

func (q *Queries) CountOrderPayments(ctx context.Context, arg CountOrderPaymentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderPayments, arg.BusinessID, arg.OutletID, arg.OrderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConfirmedPayment = `-- name: CreateConfirmedPayment :one
INSERT INTO payments (
    business_id, outlet_id, order_id, amount, method, status, external_reference,
    notes, confirmed_at, created_by, idempotency_key, request_hash
)
VALUES (
    $1, $2, $3, $4,
    $5, 'CONFIRMED', $6, $7,
    now(), $8, $9, $10
)
RETURNING id, business_id, outlet_id, order_id, amount, method, status,
          external_reference, notes, confirmed_at, created_by, created_at
`

type CreateConfirmedPaymentParams struct {
	BusinessID        int64       `json:"business_id"`
	OutletID          int64       `json:"outlet_id"`
	OrderID           int64       `json:"order_id"`
	Amount            int64       `json:"amount"`
	Method            string      `json:"method"`
	ExternalReference pgtype.Text `json:"external_reference"`
	Notes             pgtype.Text `json:"notes"`
	CreatedBy         int64       `json:"created_by"`
	IdempotencyKey    pgtype.Text `json:"idempotency_key"`
	RequestHash       []byte      `json:"request_hash"`
}

type CreateConfirmedPaymentRow struct {
	ID                int64              `json:"id"`
	BusinessID        int64              `json:"business_id"`
	OutletID          int64              `json:"outlet_id"`
	OrderID           int64              `json:"order_id"`
	Amount            int64              `json:"amount"`
	Method            string             `json:"method"`
	Status            string             `json:"status"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Notes             pgtype.Text        `json:"notes"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
	CreatedBy         int64              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateConfirmedPayment(ctx context.Context, arg CreateConfirmedPaymentParams) (CreateConfirmedPaymentRow, error) {
	row := q.db.QueryRow(ctx, createConfirmedPayment,
		arg.BusinessID,
		arg.OutletID,
		arg.OrderID,
		arg.Amount,
		arg.Method,
		arg.ExternalReference,
		arg.Notes,
		arg.CreatedBy,
		arg.IdempotencyKey,
		arg.RequestHash,
	)
	var i CreateConfirmedPaymentRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.ExternalReference,
		&i.Notes,
		&i.ConfirmedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getConfirmedPaymentTotal = `-- name: GetConfirmedPaymentTotal :one
SELECT COALESCE(sum(amount), 0)::bigint AS paid_amount
FROM payments
WHERE business_id=$1 AND outlet_id=$2
  AND order_id=$3 AND status='CONFIRMED'
`

type GetConfirmedPaymentTotalParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	OrderID    int64 `json:"order_id"`
}

func (q *Queries) GetConfirmedPaymentTotal(ctx context.Context, arg GetConfirmedPaymentTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, getConfirmedPaymentTotal, arg.BusinessID, arg.OutletID, arg.OrderID)
	var paid_amount int64
	err := row.Scan(&paid_amount)
	return paid_amount, err
}

const getOrderPaymentForUpdate = `-- name: GetOrderPaymentForUpdate :one
SELECT id, amount, method, status, external_reference, notes, confirmed_at, voided_at,
       voided_by, void_reason, created_by, created_at
FROM payments
WHERE business_id=$1 AND outlet_id=$2
  AND order_id=$3 AND id=$4
FOR UPDATE
`

type GetOrderPaymentForUpdateParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	OrderID    int64 `json:"order_id"`
	PaymentID  int64 `json:"payment_id"`
}

type GetOrderPaymentForUpdateRow struct {
	ID                int64              `json:"id"`
	Amount            int64              `json:"amount"`
	Method            string             `json:"method"`
	Status            string             `json:"status"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Notes             pgtype.Text        `json:"notes"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
	VoidedAt          pgtype.Timestamptz `json:"voided_at"`
	VoidedBy          pgtype.Int8        `json:"voided_by"`
	VoidReason        pgtype.Text        `json:"void_reason"`
	CreatedBy         int64              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOrderPaymentForUpdate(ctx context.Context, arg GetOrderPaymentForUpdateParams) (GetOrderPaymentForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOrderPaymentForUpdate,
		arg.BusinessID,
		arg.OutletID,
		arg.OrderID,
		arg.PaymentID,
	)
	var i GetOrderPaymentForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.ExternalReference,
		&i.Notes,
		&i.ConfirmedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, business_id, outlet_id, order_id, amount, method, status,
       external_reference, notes, confirmed_at, voided_at, voided_by, void_reason,
       created_by, created_at, request_hash
FROM payments
WHERE business_id=$1 AND outlet_id=$2
  AND order_id=$3 AND idempotency_key=$4
`

type GetPaymentByIdempotencyKeyParams struct {
	BusinessID     int64       `json:"business_id"`
	OutletID       int64       `json:"outlet_id"`
	OrderID        int64       `json:"order_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

type GetPaymentByIdempotencyKeyRow struct {
	ID                int64              `json:"id"`
	BusinessID        int64              `json:"business_id"`
	OutletID          int64              `json:"outlet_id"`
	OrderID           int64              `json:"order_id"`
	Amount            int64              `json:"amount"`
	Method            string             `json:"method"`
	Status            string             `json:"status"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Notes             pgtype.Text        `json:"notes"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
	VoidedAt          pgtype.Timestamptz `json:"voided_at"`
	VoidedBy          pgtype.Int8        `json:"voided_by"`
	VoidReason        pgtype.Text        `json:"void_reason"`
	CreatedBy         int64              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RequestHash       []byte             `json:"request_hash"`
}

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, arg GetPaymentByIdempotencyKeyParams) (GetPaymentByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey,
		arg.BusinessID,
		arg.OutletID,
		arg.OrderID,
		arg.IdempotencyKey,
	)
	var i GetPaymentByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.ExternalReference,
		&i.Notes,
		&i.ConfirmedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RequestHash,
	)
	return i, err
}

const insertPaymentAuditLog = `-- name: InsertPaymentAuditLog :exec
INSERT INTO audit_logs (business_id, outlet_id, actor_user_id, action, entity_type, entity_id, old_values, new_values, ip_address, user_agent)
VALUES ($1, $2, $3, $4, 'payment',
        $5, $6, $7, $8, $9)
`

type InsertPaymentAuditLogParams struct {
	BusinessID  int64       `json:"business_id"`
	OutletID    pgtype.Int8 `json:"outlet_id"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	PaymentID   pgtype.Int8 `json:"payment_id"`
	OldValues   []byte      `json:"old_values"`
	NewValues   []byte      `json:"new_values"`
	IpAddress   *netip.Addr `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertPaymentAuditLog(ctx context.Context, arg InsertPaymentAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertPaymentAuditLog,
		arg.BusinessID,
		arg.OutletID,
		arg.ActorUserID,
		arg.Action,
		arg.PaymentID,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const listOrderPayments = `-- name: ListOrderPayments :many
SELECT id, amount, method, status, external_reference, notes, confirmed_at, voided_at,
       voided_by, void_reason, created_by, created_at
FROM payments
WHERE business_id=$1 AND outlet_id=$2 AND order_id=$3
ORDER BY created_at, id
LIMIT $5 OFFSET $4
`

type ListOrderPaymentsParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	OrderID    int64 `json:"order_id"`
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type ListOrderPaymentsRow struct {
	ID                int64              `json:"id"`
	Amount            int64              `json:"amount"`
	Method            string             `json:"method"`
	Status            string             `json:"status"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Notes             pgtype.Text        `json:"notes"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
	VoidedAt          pgtype.Timestamptz `json:"voided_at"`
	VoidedBy          pgtype.Int8        `json:"voided_by"`
	VoidReason        pgtype.Text        `json:"void_reason"`
	CreatedBy         int64              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOrderPayments(ctx context.Context, arg ListOrderPaymentsParams) ([]ListOrderPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listOrderPayments,
		arg.BusinessID,
		arg.OutletID,
		arg.OrderID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderPaymentsRow
	for rows.Next() {
		var i ListOrderPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Method,
			&i.Status,
			&i.ExternalReference,
			&i.Notes,
			&i.ConfirmedAt,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderPaymentStatus = `-- name: UpdateOrderPaymentStatus :one
UPDATE orders
SET payment_status=$1, updated_at=now()
WHERE business_id=$2 AND outlet_id=$3 AND id=$4
RETURNING payment_status, updated_at
`

type UpdateOrderPaymentStatusParams struct {
	PaymentStatus string `json:"payment_status"`
	BusinessID    int64  `json:"business_id"`
	OutletID      int64  `json:"outlet_id"`
	OrderID       int64  `json:"order_id"`
}

type UpdateOrderPaymentStatusRow struct {
	PaymentStatus string             `json:"payment_status"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) (UpdateOrderPaymentStatusRow, error) {
	row := q.db.QueryRow(ctx, updateOrderPaymentStatus,
		arg.PaymentStatus,
		arg.BusinessID,
		arg.OutletID,
		arg.OrderID,
	)
	var i UpdateOrderPaymentStatusRow
	err := row.Scan(&i.PaymentStatus, &i.UpdatedAt)
	return i, err
}

const voidConfirmedPayment = `-- name: VoidConfirmedPayment :one
UPDATE payments SET status='VOIDED', voided_at=now(), voided_by=$1, void_reason=$2
WHERE business_id=$3 AND outlet_id=$4
  AND order_id=$5 AND id=$6 AND status='CONFIRMED'
RETURNING id, amount, method, status, external_reference, notes, confirmed_at, voided_at,
          voided_by, void_reason, created_by, created_at
`

type VoidConfirmedPaymentParams struct {
	VoidedBy   pgtype.Int8 `json:"voided_by"`
	VoidReason pgtype.Text `json:"void_reason"`
	BusinessID int64       `json:"business_id"`
	OutletID   int64       `json:"outlet_id"`
	OrderID    int64       `json:"order_id"`
	PaymentID  int64       `json:"payment_id"`
}

type VoidConfirmedPaymentRow struct {
	ID                int64              `json:"id"`
	Amount            int64              `json:"amount"`
	Method            string             `json:"method"`
	Status            string             `json:"status"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Notes             pgtype.Text        `json:"notes"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
	VoidedAt          pgtype.Timestamptz `json:"voided_at"`
	VoidedBy          pgtype.Int8        `json:"voided_by"`
	VoidReason        pgtype.Text        `json:"void_reason"`
	CreatedBy         int64              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) VoidConfirmedPayment(ctx context.Context, arg VoidConfirmedPaymentParams) (VoidConfirmedPaymentRow, error) {
	row := q.db.QueryRow(ctx, voidConfirmedPayment,
		arg.VoidedBy,
		arg.VoidReason,
		arg.BusinessID,
		arg.OutletID,
		arg.OrderID,
		arg.PaymentID,
	)
	var i VoidConfirmedPaymentRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.ExternalReference,
		&i.Notes,
		&i.ConfirmedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
