// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: perfumes.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPerfumes = `-- name: CountPerfumes :one
SELECT count(*)
FROM perfumes
WHERE business_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%'
       OR COALESCE(description, '') ILIKE '%' || $2::text || '%')
  AND ($3::boolean IS NULL OR is_active = $3::boolean)
`

type CountPerfumesParams struct {
	BusinessID int64       `json:"business_id"`
	Search     string      `json:"search"`
	IsActive   pgtype.Bool `json:"is_active"`
}

func (q *Queries) CountPerfumes(ctx context.Context, arg CountPerfumesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPerfumes, arg.BusinessID, arg.Search, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPerfume = `-- name: CreatePerfume :one
INSERT INTO perfumes (business_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, business_id, name, description, is_active, created_at, updated_at
`

type CreatePerfumeParams struct {
	BusinessID  int64       `json:"business_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type CreatePerfumeRow struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePerfume(ctx context.Context, arg CreatePerfumeParams) (CreatePerfumeRow, error) {
	row := q.db.QueryRow(ctx, createPerfume, arg.BusinessID, arg.Name, arg.Description)
	var i CreatePerfumeRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPerfume = `-- name: GetPerfume :one
SELECT id, business_id, name, description, is_active, created_at, updated_at
FROM perfumes
WHERE business_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetPerfumeParams struct {
	BusinessID int64 `json:"business_id"`
	PerfumeID  int64 `json:"perfume_id"`
}

type GetPerfumeRow struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPerfume(ctx context.Context, arg GetPerfumeParams) (GetPerfumeRow, error) {
	row := q.db.QueryRow(ctx, getPerfume, arg.BusinessID, arg.PerfumeID)
	var i GetPerfumeRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPerfumeForUpdate = `-- name: GetPerfumeForUpdate :one
SELECT id, business_id, name, description, is_active, created_at, updated_at
FROM perfumes
WHERE business_id = $1 AND id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type GetPerfumeForUpdateParams struct {
	BusinessID int64 `json:"business_id"`
	PerfumeID  int64 `json:"perfume_id"`
}

type GetPerfumeForUpdateRow struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPerfumeForUpdate(ctx context.Context, arg GetPerfumeForUpdateParams) (GetPerfumeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPerfumeForUpdate, arg.BusinessID, arg.PerfumeID)
	var i GetPerfumeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPerfumes = `-- name: ListPerfumes :many
SELECT id, business_id, name, description, is_active, created_at, updated_at
FROM perfumes
WHERE business_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%'
       OR COALESCE(description, '') ILIKE '%' || $2::text || '%')
  AND ($3::boolean IS NULL OR is_active = $3::boolean)
ORDER BY lower(name), id
LIMIT $5 OFFSET $4
`

type ListPerfumesParams struct {
	BusinessID int64       `json:"business_id"`
	Search     string      `json:"search"`
	IsActive   pgtype.Bool `json:"is_active"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListPerfumesRow struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPerfumes(ctx context.Context, arg ListPerfumesParams) ([]ListPerfumesRow, error) {
	rows, err := q.db.Query(ctx, listPerfumes,
		arg.BusinessID,
		arg.Search,
		arg.IsActive,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPerfumesRow
	for rows.Next() {
		var i ListPerfumesRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePerfume = `-- name: SoftDeletePerfume :one
UPDATE perfumes
SET is_active = FALSE, deleted_at = now(), updated_at = now()
WHERE business_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id
`

type SoftDeletePerfumeParams struct {
	BusinessID int64 `json:"business_id"`
	PerfumeID  int64 `json:"perfume_id"`
}

func (q *Queries) SoftDeletePerfume(ctx context.Context, arg SoftDeletePerfumeParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeletePerfume, arg.BusinessID, arg.PerfumeID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updatePerfume = `-- name: UpdatePerfume :one
UPDATE perfumes
SET name = $1, description = $2, is_active = $3, updated_at = now()
WHERE business_id = $4 AND id = $5 AND deleted_at IS NULL
RETURNING id, business_id, name, description, is_active, created_at, updated_at
`

type UpdatePerfumeParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	BusinessID  int64       `json:"business_id"`
	PerfumeID   int64       `json:"perfume_id"`
}

type UpdatePerfumeRow struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePerfume(ctx context.Context, arg UpdatePerfumeParams) (UpdatePerfumeRow, error) {
	row := q.db.QueryRow(ctx, updatePerfume,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.BusinessID,
		arg.PerfumeID,
	)
	var i UpdatePerfumeRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
