// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_tenants.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const businessAuditCount = `-- name: BusinessAuditCount :one
SELECT count(*) FROM audit_logs WHERE business_id=$1
`

func (q *Queries) BusinessAuditCount(ctx context.Context, businessID int64) (int64, error) {
	row := q.db.QueryRow(ctx, businessAuditCount, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const businessAuditView = `-- name: BusinessAuditView :many
SELECT id,business_id,outlet_id,actor_user_id,actor_platform_admin_id,support_session_id,platform_audit_id,action,entity_type,entity_id,occurred_at FROM audit_logs WHERE business_id=$1 ORDER BY id DESC LIMIT $2 OFFSET $3
`

type BusinessAuditViewParams struct {
	BusinessID int64 `json:"business_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type BusinessAuditViewRow struct {
	ID                   int64              `json:"id"`
	BusinessID           int64              `json:"business_id"`
	OutletID             pgtype.Int8        `json:"outlet_id"`
	ActorUserID          pgtype.Int8        `json:"actor_user_id"`
	ActorPlatformAdminID pgtype.Int8        `json:"actor_platform_admin_id"`
	SupportSessionID     pgtype.Int8        `json:"support_session_id"`
	PlatformAuditID      pgtype.Int8        `json:"platform_audit_id"`
	Action               string             `json:"action"`
	EntityType           string             `json:"entity_type"`
	EntityID             pgtype.Int8        `json:"entity_id"`
	OccurredAt           pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) BusinessAuditView(ctx context.Context, arg BusinessAuditViewParams) ([]BusinessAuditViewRow, error) {
	rows, err := q.db.Query(ctx, businessAuditView, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BusinessAuditViewRow
	for rows.Next() {
		var i BusinessAuditViewRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.OutletID,
			&i.ActorUserID,
			&i.ActorPlatformAdminID,
			&i.SupportSessionID,
			&i.PlatformAuditID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const businessWritePlatformAudit = `-- name: BusinessWritePlatformAudit :exec
INSERT INTO audit_logs(business_id,actor_user_id,actor_platform_admin_id,support_session_id,platform_audit_id,action,entity_type,entity_id,new_values) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type BusinessWritePlatformAuditParams struct {
	BusinessID           int64       `json:"business_id"`
	ActorUserID          pgtype.Int8 `json:"actor_user_id"`
	ActorPlatformAdminID pgtype.Int8 `json:"actor_platform_admin_id"`
	SupportSessionID     pgtype.Int8 `json:"support_session_id"`
	PlatformAuditID      pgtype.Int8 `json:"platform_audit_id"`
	Action               string      `json:"action"`
	EntityType           string      `json:"entity_type"`
	EntityID             pgtype.Int8 `json:"entity_id"`
	NewValues            []byte      `json:"new_values"`
}

func (q *Queries) BusinessWritePlatformAudit(ctx context.Context, arg BusinessWritePlatformAuditParams) error {
	_, err := q.db.Exec(ctx, businessWritePlatformAudit,
		arg.BusinessID,
		arg.ActorUserID,
		arg.ActorPlatformAdminID,
		arg.SupportSessionID,
		arg.PlatformAuditID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.NewValues,
	)
	return err
}

const platformAuditCount = `-- name: PlatformAuditCount :one
SELECT count(*) FROM platform_audit_logs WHERE ($1::bigint IS NULL OR business_id=$1)
`

func (q *Queries) PlatformAuditCount(ctx context.Context, businessID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, platformAuditCount, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const platformAuditView = `-- name: PlatformAuditView :many
SELECT id,business_id,actor_platform_admin_id,support_session_id,reason,action,target_type,target_id,outcome,request_id,metadata,occurred_at FROM platform_audit_logs WHERE ($1::bigint IS NULL OR business_id=$1) ORDER BY id DESC LIMIT $3 OFFSET $2
`

type PlatformAuditViewParams struct {
	BusinessID pgtype.Int8 `json:"business_id"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type PlatformAuditViewRow struct {
	ID                   int64              `json:"id"`
	BusinessID           pgtype.Int8        `json:"business_id"`
	ActorPlatformAdminID pgtype.Int8        `json:"actor_platform_admin_id"`
	SupportSessionID     pgtype.Int8        `json:"support_session_id"`
	Reason               pgtype.Text        `json:"reason"`
	Action               string             `json:"action"`
	TargetType           string             `json:"target_type"`
	TargetID             pgtype.Int8        `json:"target_id"`
	Outcome              string             `json:"outcome"`
	RequestID            pgtype.Text        `json:"request_id"`
	Metadata             []byte             `json:"metadata"`
	OccurredAt           pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) PlatformAuditView(ctx context.Context, arg PlatformAuditViewParams) ([]PlatformAuditViewRow, error) {
	rows, err := q.db.Query(ctx, platformAuditView, arg.BusinessID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformAuditViewRow
	for rows.Next() {
		var i PlatformAuditViewRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ActorPlatformAdminID,
			&i.SupportSessionID,
			&i.Reason,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Outcome,
			&i.RequestID,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformBusinessCounts = `-- name: PlatformBusinessCounts :one
SELECT (SELECT count(*) FROM outlets o WHERE o.business_id=b.id)::bigint AS outlets,(SELECT count(*) FROM users u WHERE u.business_id=b.id AND u.role='ADMIN' AND u.is_active)::bigint AS active_admins FROM businesses b WHERE b.id=$1
`

type PlatformBusinessCountsRow struct {
	Outlets      int64 `json:"outlets"`
	ActiveAdmins int64 `json:"active_admins"`
}

func (q *Queries) PlatformBusinessCounts(ctx context.Context, id int64) (PlatformBusinessCountsRow, error) {
	row := q.db.QueryRow(ctx, platformBusinessCounts, id)
	var i PlatformBusinessCountsRow
	err := row.Scan(&i.Outlets, &i.ActiveAdmins)
	return i, err
}

const platformCountBusinesses = `-- name: PlatformCountBusinesses :one
SELECT count(*) FROM businesses WHERE ($1::boolean IS NULL OR is_active=$1) AND name ILIKE '%' || $2::text || '%'
`

type PlatformCountBusinessesParams struct {
	Active pgtype.Bool `json:"active"`
	Search string      `json:"search"`
}

func (q *Queries) PlatformCountBusinesses(ctx context.Context, arg PlatformCountBusinessesParams) (int64, error) {
	row := q.db.QueryRow(ctx, platformCountBusinesses, arg.Active, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const platformCreateBusiness = `-- name: PlatformCreateBusiness :one
INSERT INTO businesses(name,phone,address) VALUES ($1,$2,$3) RETURNING id,name,timezone,phone,address,is_active,created_at,updated_at
`

type PlatformCreateBusinessParams struct {
	Name    string      `json:"name"`
	Phone   pgtype.Text `json:"phone"`
	Address pgtype.Text `json:"address"`
}

func (q *Queries) PlatformCreateBusiness(ctx context.Context, arg PlatformCreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, platformCreateBusiness, arg.Name, arg.Phone, arg.Address)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const platformCreateFirstAdmin = `-- name: PlatformCreateFirstAdmin :one
INSERT INTO users(business_id,email,full_name,password_hash,role) VALUES ($1,$2,$3,$4,'ADMIN') RETURNING id,business_id,email,full_name,role,is_active
`

type PlatformCreateFirstAdminParams struct {
	BusinessID   int64  `json:"business_id"`
	Email        string `json:"email"`
	FullName     string `json:"full_name"`
	PasswordHash string `json:"password_hash"`
}

type PlatformCreateFirstAdminRow struct {
	ID         int64  `json:"id"`
	BusinessID int64  `json:"business_id"`
	Email      string `json:"email"`
	FullName   string `json:"full_name"`
	Role       string `json:"role"`
	IsActive   bool   `json:"is_active"`
}

func (q *Queries) PlatformCreateFirstAdmin(ctx context.Context, arg PlatformCreateFirstAdminParams) (PlatformCreateFirstAdminRow, error) {
	row := q.db.QueryRow(ctx, platformCreateFirstAdmin,
		arg.BusinessID,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
	)
	var i PlatformCreateFirstAdminRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const platformGetBusiness = `-- name: PlatformGetBusiness :one
SELECT id,name,timezone,phone,address,is_active,created_at,updated_at FROM businesses WHERE id=$1
`

func (q *Queries) PlatformGetBusiness(ctx context.Context, id int64) (Business, error) {
	row := q.db.QueryRow(ctx, platformGetBusiness, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const platformListBusinesses = `-- name: PlatformListBusinesses :many
SELECT id,name,timezone,phone,address,is_active,created_at,updated_at FROM businesses WHERE ($1::boolean IS NULL OR is_active=$1) AND name ILIKE '%' || $2::text || '%' ORDER BY id LIMIT $4 OFFSET $3
`

type PlatformListBusinessesParams struct {
	Active     pgtype.Bool `json:"active"`
	Search     string      `json:"search"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) PlatformListBusinesses(ctx context.Context, arg PlatformListBusinessesParams) ([]Business, error) {
	rows, err := q.db.Query(ctx, platformListBusinesses,
		arg.Active,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Timezone,
			&i.Phone,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformLockBusiness = `-- name: PlatformLockBusiness :one
SELECT id,is_active FROM businesses WHERE id=$1 FOR UPDATE
`

type PlatformLockBusinessRow struct {
	ID       int64 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) PlatformLockBusiness(ctx context.Context, id int64) (PlatformLockBusinessRow, error) {
	row := q.db.QueryRow(ctx, platformLockBusiness, id)
	var i PlatformLockBusinessRow
	err := row.Scan(&i.ID, &i.IsActive)
	return i, err
}

const platformRevokeBusinessSupport = `-- name: PlatformRevokeBusinessSupport :exec
UPDATE platform_support_requests SET revoked_at=clock_timestamp(),revocation_reason='Business deactivated' WHERE business_id=$1 AND revoked_at IS NULL
`

func (q *Queries) PlatformRevokeBusinessSupport(ctx context.Context, businessID int64) error {
	_, err := q.db.Exec(ctx, platformRevokeBusinessSupport, businessID)
	return err
}

const platformRevokeTenantFamilies = `-- name: PlatformRevokeTenantFamilies :exec
UPDATE session_families SET revoked_at=clock_timestamp() WHERE business_id=$1 AND revoked_at IS NULL
`

func (q *Queries) PlatformRevokeTenantFamilies(ctx context.Context, businessID int64) error {
	_, err := q.db.Exec(ctx, platformRevokeTenantFamilies, businessID)
	return err
}

const platformSetBusinessActive = `-- name: PlatformSetBusinessActive :exec
UPDATE businesses SET is_active=$2,updated_at=clock_timestamp() WHERE id=$1
`

type PlatformSetBusinessActiveParams struct {
	ID       int64 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) PlatformSetBusinessActive(ctx context.Context, arg PlatformSetBusinessActiveParams) error {
	_, err := q.db.Exec(ctx, platformSetBusinessActive, arg.ID, arg.IsActive)
	return err
}

const platformWriteTenantAudit = `-- name: PlatformWriteTenantAudit :one
INSERT INTO platform_audit_logs(actor_platform_admin_id,business_id,support_session_id,reason,action,target_type,target_id,outcome,request_id,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,'SUCCESS',$8,$9) RETURNING id
`

type PlatformWriteTenantAuditParams struct {
	ActorPlatformAdminID pgtype.Int8 `json:"actor_platform_admin_id"`
	BusinessID           pgtype.Int8 `json:"business_id"`
	SupportSessionID     pgtype.Int8 `json:"support_session_id"`
	Reason               pgtype.Text `json:"reason"`
	Action               string      `json:"action"`
	TargetType           string      `json:"target_type"`
	TargetID             pgtype.Int8 `json:"target_id"`
	RequestID            pgtype.Text `json:"request_id"`
	Metadata             []byte      `json:"metadata"`
}

func (q *Queries) PlatformWriteTenantAudit(ctx context.Context, arg PlatformWriteTenantAuditParams) (int64, error) {
	row := q.db.QueryRow(ctx, platformWriteTenantAudit,
		arg.ActorPlatformAdminID,
		arg.BusinessID,
		arg.SupportSessionID,
		arg.Reason,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.RequestID,
		arg.Metadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const supportCountPerfumes = `-- name: SupportCountPerfumes :one
SELECT count(*) FROM perfumes WHERE business_id=$1 AND deleted_at IS NULL
`

func (q *Queries) SupportCountPerfumes(ctx context.Context, businessID int64) (int64, error) {
	row := q.db.QueryRow(ctx, supportCountPerfumes, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const supportCountRequests = `-- name: SupportCountRequests :one
SELECT count(*) FROM platform_support_requests WHERE business_id=$1
`

func (q *Queries) SupportCountRequests(ctx context.Context, businessID int64) (int64, error) {
	row := q.db.QueryRow(ctx, supportCountRequests, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const supportCountSessions = `-- name: SupportCountSessions :one
SELECT count(*) FROM platform_support_sessions WHERE business_id=$1
`

func (q *Queries) SupportCountSessions(ctx context.Context, businessID int64) (int64, error) {
	row := q.db.QueryRow(ctx, supportCountSessions, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const supportCreateRequest = `-- name: SupportCreateRequest :one
INSERT INTO platform_support_requests(business_id,requested_by_user_id,reason,access_scope,expires_at) VALUES ($1,$2,$3,$4,$5) RETURNING id, business_id, requested_by_user_id, reason, access_scope, created_at, expires_at, revoked_at, revocation_reason
`

type SupportCreateRequestParams struct {
	BusinessID        int64              `json:"business_id"`
	RequestedByUserID int64              `json:"requested_by_user_id"`
	Reason            string             `json:"reason"`
	AccessScope       string             `json:"access_scope"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SupportCreateRequest(ctx context.Context, arg SupportCreateRequestParams) (PlatformSupportRequest, error) {
	row := q.db.QueryRow(ctx, supportCreateRequest,
		arg.BusinessID,
		arg.RequestedByUserID,
		arg.Reason,
		arg.AccessScope,
		arg.ExpiresAt,
	)
	var i PlatformSupportRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.RequestedByUserID,
		&i.Reason,
		&i.AccessScope,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const supportCreateSession = `-- name: SupportCreateSession :one
INSERT INTO platform_support_sessions(business_id,support_request_id,platform_admin_id,platform_family_id,reason,access_scope,expires_at) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, business_id, support_request_id, platform_admin_id, platform_family_id, reason, access_scope, started_at, expires_at, ended_at, end_reason
`

type SupportCreateSessionParams struct {
	BusinessID       int64              `json:"business_id"`
	SupportRequestID int64              `json:"support_request_id"`
	PlatformAdminID  int64              `json:"platform_admin_id"`
	PlatformFamilyID int64              `json:"platform_family_id"`
	Reason           string             `json:"reason"`
	AccessScope      string             `json:"access_scope"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SupportCreateSession(ctx context.Context, arg SupportCreateSessionParams) (PlatformSupportSession, error) {
	row := q.db.QueryRow(ctx, supportCreateSession,
		arg.BusinessID,
		arg.SupportRequestID,
		arg.PlatformAdminID,
		arg.PlatformFamilyID,
		arg.Reason,
		arg.AccessScope,
		arg.ExpiresAt,
	)
	var i PlatformSupportSession
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.SupportRequestID,
		&i.PlatformAdminID,
		&i.PlatformFamilyID,
		&i.Reason,
		&i.AccessScope,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const supportDiagnostics = `-- name: SupportDiagnostics :one
SELECT (SELECT count(*) FROM outlets o WHERE o.business_id=b.id)::bigint AS outlets,(SELECT count(*) FROM users u WHERE u.business_id=b.id)::bigint AS users,(SELECT count(*) FROM perfumes p WHERE p.business_id=b.id AND p.deleted_at IS NULL)::bigint AS perfumes FROM businesses b WHERE b.id=$1
`

type SupportDiagnosticsRow struct {
	Outlets  int64 `json:"outlets"`
	Users    int64 `json:"users"`
	Perfumes int64 `json:"perfumes"`
}

func (q *Queries) SupportDiagnostics(ctx context.Context, id int64) (SupportDiagnosticsRow, error) {
	row := q.db.QueryRow(ctx, supportDiagnostics, id)
	var i SupportDiagnosticsRow
	err := row.Scan(&i.Outlets, &i.Users, &i.Perfumes)
	return i, err
}

const supportEndSession = `-- name: SupportEndSession :one
UPDATE platform_support_sessions SET ended_at=COALESCE(ended_at,clock_timestamp()),end_reason=COALESCE(end_reason,$3) WHERE business_id=$1 AND id=$2 RETURNING id, business_id, support_request_id, platform_admin_id, platform_family_id, reason, access_scope, started_at, expires_at, ended_at, end_reason
`

type SupportEndSessionParams struct {
	BusinessID int64       `json:"business_id"`
	ID         int64       `json:"id"`
	EndReason  pgtype.Text `json:"end_reason"`
}

func (q *Queries) SupportEndSession(ctx context.Context, arg SupportEndSessionParams) (PlatformSupportSession, error) {
	row := q.db.QueryRow(ctx, supportEndSession, arg.BusinessID, arg.ID, arg.EndReason)
	var i PlatformSupportSession
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.SupportRequestID,
		&i.PlatformAdminID,
		&i.PlatformFamilyID,
		&i.Reason,
		&i.AccessScope,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const supportGetPerfume = `-- name: SupportGetPerfume :one
SELECT id,business_id,name,description,is_active,version FROM perfumes WHERE business_id=$1 AND id=$2 AND deleted_at IS NULL
`

type SupportGetPerfumeParams struct {
	BusinessID int64 `json:"business_id"`
	ID         int64 `json:"id"`
}

type SupportGetPerfumeRow struct {
	ID          int64       `json:"id"`
	BusinessID  int64       `json:"business_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	Version     int64       `json:"version"`
}

func (q *Queries) SupportGetPerfume(ctx context.Context, arg SupportGetPerfumeParams) (SupportGetPerfumeRow, error) {
	row := q.db.QueryRow(ctx, supportGetPerfume, arg.BusinessID, arg.ID)
	var i SupportGetPerfumeRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.Version,
	)
	return i, err
}

const supportGetPlatformFamily = `-- name: SupportGetPlatformFamily :one
SELECT t.family_id FROM platform_refresh_tokens t JOIN platform_session_families f ON f.id=t.family_id AND f.platform_admin_id=t.platform_admin_id WHERE t.id=$1 AND t.platform_admin_id=$2 AND t.revoked_at IS NULL AND t.expires_at>clock_timestamp() AND f.revoked_at IS NULL FOR SHARE OF f,t
`

type SupportGetPlatformFamilyParams struct {
	ID              int64 `json:"id"`
	PlatformAdminID int64 `json:"platform_admin_id"`
}

func (q *Queries) SupportGetPlatformFamily(ctx context.Context, arg SupportGetPlatformFamilyParams) (int64, error) {
	row := q.db.QueryRow(ctx, supportGetPlatformFamily, arg.ID, arg.PlatformAdminID)
	var family_id int64
	err := row.Scan(&family_id)
	return family_id, err
}

const supportGetRequest = `-- name: SupportGetRequest :one
SELECT id, business_id, requested_by_user_id, reason, access_scope, created_at, expires_at, revoked_at, revocation_reason FROM platform_support_requests WHERE business_id=$1 AND id=$2
`

type SupportGetRequestParams struct {
	BusinessID int64 `json:"business_id"`
	ID         int64 `json:"id"`
}

func (q *Queries) SupportGetRequest(ctx context.Context, arg SupportGetRequestParams) (PlatformSupportRequest, error) {
	row := q.db.QueryRow(ctx, supportGetRequest, arg.BusinessID, arg.ID)
	var i PlatformSupportRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.RequestedByUserID,
		&i.Reason,
		&i.AccessScope,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const supportListPerfumes = `-- name: SupportListPerfumes :many
SELECT id,business_id,name,description,is_active,version FROM perfumes WHERE business_id=$1 AND deleted_at IS NULL ORDER BY id LIMIT $2 OFFSET $3
`

type SupportListPerfumesParams struct {
	BusinessID int64 `json:"business_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type SupportListPerfumesRow struct {
	ID          int64       `json:"id"`
	BusinessID  int64       `json:"business_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	Version     int64       `json:"version"`
}

func (q *Queries) SupportListPerfumes(ctx context.Context, arg SupportListPerfumesParams) ([]SupportListPerfumesRow, error) {
	rows, err := q.db.Query(ctx, supportListPerfumes, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportListPerfumesRow
	for rows.Next() {
		var i SupportListPerfumesRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supportListRequests = `-- name: SupportListRequests :many
SELECT id, business_id, requested_by_user_id, reason, access_scope, created_at, expires_at, revoked_at, revocation_reason FROM platform_support_requests WHERE business_id=$1 ORDER BY id DESC LIMIT $2 OFFSET $3
`

type SupportListRequestsParams struct {
	BusinessID int64 `json:"business_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) SupportListRequests(ctx context.Context, arg SupportListRequestsParams) ([]PlatformSupportRequest, error) {
	rows, err := q.db.Query(ctx, supportListRequests, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformSupportRequest
	for rows.Next() {
		var i PlatformSupportRequest
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.RequestedByUserID,
			&i.Reason,
			&i.AccessScope,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevocationReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supportListSessions = `-- name: SupportListSessions :many
SELECT id, business_id, support_request_id, platform_admin_id, platform_family_id, reason, access_scope, started_at, expires_at, ended_at, end_reason FROM platform_support_sessions WHERE business_id=$1 ORDER BY id DESC LIMIT $2 OFFSET $3
`

type SupportListSessionsParams struct {
	BusinessID int64 `json:"business_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) SupportListSessions(ctx context.Context, arg SupportListSessionsParams) ([]PlatformSupportSession, error) {
	rows, err := q.db.Query(ctx, supportListSessions, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformSupportSession
	for rows.Next() {
		var i PlatformSupportSession
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.SupportRequestID,
			&i.PlatformAdminID,
			&i.PlatformFamilyID,
			&i.Reason,
			&i.AccessScope,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.EndedAt,
			&i.EndReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supportLockOwner = `-- name: SupportLockOwner :one
SELECT u.id,u.password_hash FROM users u JOIN businesses b ON b.id=u.business_id WHERE u.business_id=$1 AND u.id=$2 AND u.role='ADMIN' AND u.is_active AND b.is_active FOR SHARE OF b,u
`

type SupportLockOwnerParams struct {
	BusinessID int64 `json:"business_id"`
	ID         int64 `json:"id"`
}

type SupportLockOwnerRow struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) SupportLockOwner(ctx context.Context, arg SupportLockOwnerParams) (SupportLockOwnerRow, error) {
	row := q.db.QueryRow(ctx, supportLockOwner, arg.BusinessID, arg.ID)
	var i SupportLockOwnerRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const supportLockRequest = `-- name: SupportLockRequest :one
SELECT r.id, r.business_id, r.requested_by_user_id, r.reason, r.access_scope, r.created_at, r.expires_at, r.revoked_at, r.revocation_reason FROM platform_support_requests r JOIN businesses b ON b.id=r.business_id JOIN users u ON u.business_id=r.business_id AND u.id=r.requested_by_user_id WHERE r.business_id=$1 AND r.id=$2 AND r.revoked_at IS NULL AND r.expires_at>clock_timestamp() AND b.is_active AND u.is_active AND u.role='ADMIN' FOR UPDATE OF r FOR SHARE OF b,u
`

type SupportLockRequestParams struct {
	BusinessID int64 `json:"business_id"`
	ID         int64 `json:"id"`
}

func (q *Queries) SupportLockRequest(ctx context.Context, arg SupportLockRequestParams) (PlatformSupportRequest, error) {
	row := q.db.QueryRow(ctx, supportLockRequest, arg.BusinessID, arg.ID)
	var i PlatformSupportRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.RequestedByUserID,
		&i.Reason,
		&i.AccessScope,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const supportLockSession = `-- name: SupportLockSession :one
SELECT s.id, s.business_id, s.support_request_id, s.platform_admin_id, s.platform_family_id, s.reason, s.access_scope, s.started_at, s.expires_at, s.ended_at, s.end_reason FROM platform_support_sessions s JOIN platform_support_requests r ON r.business_id=s.business_id AND r.id=s.support_request_id JOIN businesses b ON b.id=s.business_id JOIN users u ON u.business_id=r.business_id AND u.id=r.requested_by_user_id WHERE s.business_id=$1 AND s.id=$2 AND s.platform_admin_id=$3 AND s.platform_family_id=$4 AND s.ended_at IS NULL AND s.expires_at>clock_timestamp() AND r.revoked_at IS NULL AND r.expires_at>clock_timestamp() AND b.is_active AND u.is_active AND u.role='ADMIN' FOR SHARE OF b,r,s,u
`

type SupportLockSessionParams struct {
	BusinessID       int64 `json:"business_id"`
	ID               int64 `json:"id"`
	PlatformAdminID  int64 `json:"platform_admin_id"`
	PlatformFamilyID int64 `json:"platform_family_id"`
}

func (q *Queries) SupportLockSession(ctx context.Context, arg SupportLockSessionParams) (PlatformSupportSession, error) {
	row := q.db.QueryRow(ctx, supportLockSession,
		arg.BusinessID,
		arg.ID,
		arg.PlatformAdminID,
		arg.PlatformFamilyID,
	)
	var i PlatformSupportSession
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.SupportRequestID,
		&i.PlatformAdminID,
		&i.PlatformFamilyID,
		&i.Reason,
		&i.AccessScope,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const supportRevokeRequest = `-- name: SupportRevokeRequest :one
UPDATE platform_support_requests SET revoked_at=COALESCE(revoked_at,clock_timestamp()),revocation_reason=COALESCE(revocation_reason,$3) WHERE business_id=$1 AND id=$2 RETURNING id, business_id, requested_by_user_id, reason, access_scope, created_at, expires_at, revoked_at, revocation_reason
`

type SupportRevokeRequestParams struct {
	BusinessID       int64       `json:"business_id"`
	ID               int64       `json:"id"`
	RevocationReason pgtype.Text `json:"revocation_reason"`
}

func (q *Queries) SupportRevokeRequest(ctx context.Context, arg SupportRevokeRequestParams) (PlatformSupportRequest, error) {
	row := q.db.QueryRow(ctx, supportRevokeRequest, arg.BusinessID, arg.ID, arg.RevocationReason)
	var i PlatformSupportRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.RequestedByUserID,
		&i.Reason,
		&i.AccessScope,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const supportSessionStillValid = `-- name: SupportSessionStillValid :one
SELECT EXISTS(SELECT 1 FROM platform_support_sessions s JOIN platform_support_requests r ON r.id=s.support_request_id WHERE s.id=$1 AND s.ended_at IS NULL AND s.expires_at>clock_timestamp() AND r.revoked_at IS NULL AND r.expires_at>clock_timestamp())
`

func (q *Queries) SupportSessionStillValid(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, supportSessionStillValid, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const supportUpdatePerfumeDescription = `-- name: SupportUpdatePerfumeDescription :one
UPDATE perfumes SET description=$3,version=version+1,updated_at=clock_timestamp() WHERE business_id=$1 AND id=$2 AND version=$4 AND deleted_at IS NULL RETURNING id,business_id,name,description,is_active,version
`

type SupportUpdatePerfumeDescriptionParams struct {
	BusinessID  int64       `json:"business_id"`
	ID          int64       `json:"id"`
	Description pgtype.Text `json:"description"`
	Version     int64       `json:"version"`
}

type SupportUpdatePerfumeDescriptionRow struct {
	ID          int64       `json:"id"`
	BusinessID  int64       `json:"business_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	Version     int64       `json:"version"`
}

func (q *Queries) SupportUpdatePerfumeDescription(ctx context.Context, arg SupportUpdatePerfumeDescriptionParams) (SupportUpdatePerfumeDescriptionRow, error) {
	row := q.db.QueryRow(ctx, supportUpdatePerfumeDescription,
		arg.BusinessID,
		arg.ID,
		arg.Description,
		arg.Version,
	)
	var i SupportUpdatePerfumeDescriptionRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.Version,
	)
	return i, err
}
