// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_auth.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlatformRefreshToken = `-- name: CreatePlatformRefreshToken :one
INSERT INTO platform_refresh_tokens (platform_admin_id, family_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4) RETURNING id, expires_at
`

type CreatePlatformRefreshTokenParams struct {
	PlatformAdminID int64              `json:"platform_admin_id"`
	FamilyID        int64              `json:"family_id"`
	TokenHash       string             `json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type CreatePlatformRefreshTokenRow struct {
	ID        int64              `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePlatformRefreshToken(ctx context.Context, arg CreatePlatformRefreshTokenParams) (CreatePlatformRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createPlatformRefreshToken,
		arg.PlatformAdminID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i CreatePlatformRefreshTokenRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const createPlatformSessionFamily = `-- name: CreatePlatformSessionFamily :one
INSERT INTO platform_session_families (platform_admin_id) VALUES ($1) RETURNING id
`

func (q *Queries) CreatePlatformSessionFamily(ctx context.Context, platformAdminID int64) (int64, error) {
	row := q.db.QueryRow(ctx, createPlatformSessionFamily, platformAdminID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findPlatformRefreshFamily = `-- name: FindPlatformRefreshFamily :one
SELECT family_id, platform_admin_id FROM platform_refresh_tokens WHERE token_hash = $1
`

type FindPlatformRefreshFamilyRow struct {
	FamilyID        int64 `json:"family_id"`
	PlatformAdminID int64 `json:"platform_admin_id"`
}

func (q *Queries) FindPlatformRefreshFamily(ctx context.Context, tokenHash string) (FindPlatformRefreshFamilyRow, error) {
	row := q.db.QueryRow(ctx, findPlatformRefreshFamily, tokenHash)
	var i FindPlatformRefreshFamilyRow
	err := row.Scan(&i.FamilyID, &i.PlatformAdminID)
	return i, err
}

const getActivePlatformAdmin = `-- name: GetActivePlatformAdmin :one
SELECT id, email FROM platform_admins WHERE id = $1 AND is_active
`

type GetActivePlatformAdminRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) GetActivePlatformAdmin(ctx context.Context, id int64) (GetActivePlatformAdminRow, error) {
	row := q.db.QueryRow(ctx, getActivePlatformAdmin, id)
	var i GetActivePlatformAdminRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const getActivePlatformSession = `-- name: GetActivePlatformSession :one
SELECT t.id FROM platform_refresh_tokens t
JOIN platform_session_families f ON f.id = t.family_id AND f.platform_admin_id = t.platform_admin_id
WHERE t.id = $1 AND t.platform_admin_id = $2 AND t.revoked_at IS NULL
  AND t.expires_at > now() AND f.revoked_at IS NULL
`

type GetActivePlatformSessionParams struct {
	ID              int64 `json:"id"`
	PlatformAdminID int64 `json:"platform_admin_id"`
}

func (q *Queries) GetActivePlatformSession(ctx context.Context, arg GetActivePlatformSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, getActivePlatformSession, arg.ID, arg.PlatformAdminID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPlatformAdminForLogin = `-- name: GetPlatformAdminForLogin :one
SELECT id, email, password_hash, is_active FROM platform_admins WHERE email = lower(btrim($1))
`

type GetPlatformAdminForLoginRow struct {
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) GetPlatformAdminForLogin(ctx context.Context, btrim string) (GetPlatformAdminForLoginRow, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminForLogin, btrim)
	var i GetPlatformAdminForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}

const getPlatformLogoutSession = `-- name: GetPlatformLogoutSession :one
SELECT t.id, t.family_id FROM platform_refresh_tokens t
JOIN platform_session_families f ON f.id = t.family_id AND f.platform_admin_id = t.platform_admin_id
WHERE t.id = $1 AND t.platform_admin_id = $2 AND t.expires_at > now() AND f.revoked_at IS NULL
`

type GetPlatformLogoutSessionParams struct {
	ID              int64 `json:"id"`
	PlatformAdminID int64 `json:"platform_admin_id"`
}

type GetPlatformLogoutSessionRow struct {
	ID       int64 `json:"id"`
	FamilyID int64 `json:"family_id"`
}

func (q *Queries) GetPlatformLogoutSession(ctx context.Context, arg GetPlatformLogoutSessionParams) (GetPlatformLogoutSessionRow, error) {
	row := q.db.QueryRow(ctx, getPlatformLogoutSession, arg.ID, arg.PlatformAdminID)
	var i GetPlatformLogoutSessionRow
	err := row.Scan(&i.ID, &i.FamilyID)
	return i, err
}

const getPlatformRefreshByID = `-- name: GetPlatformRefreshByID :one
SELECT id, family_id FROM platform_refresh_tokens WHERE id = $1 AND platform_admin_id = $2
`

type GetPlatformRefreshByIDParams struct {
	ID              int64 `json:"id"`
	PlatformAdminID int64 `json:"platform_admin_id"`
}

type GetPlatformRefreshByIDRow struct {
	ID       int64 `json:"id"`
	FamilyID int64 `json:"family_id"`
}

func (q *Queries) GetPlatformRefreshByID(ctx context.Context, arg GetPlatformRefreshByIDParams) (GetPlatformRefreshByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlatformRefreshByID, arg.ID, arg.PlatformAdminID)
	var i GetPlatformRefreshByIDRow
	err := row.Scan(&i.ID, &i.FamilyID)
	return i, err
}

const getPlatformRefreshForUpdate = `-- name: GetPlatformRefreshForUpdate :one
SELECT id, platform_admin_id, family_id, expires_at, revoked_at FROM platform_refresh_tokens
WHERE token_hash = $1 FOR UPDATE
`

type GetPlatformRefreshForUpdateRow struct {
	ID              int64              `json:"id"`
	PlatformAdminID int64              `json:"platform_admin_id"`
	FamilyID        int64              `json:"family_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetPlatformRefreshForUpdate(ctx context.Context, tokenHash string) (GetPlatformRefreshForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPlatformRefreshForUpdate, tokenHash)
	var i GetPlatformRefreshForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PlatformAdminID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertPlatformAuditLog = `-- name: InsertPlatformAuditLog :exec
INSERT INTO platform_audit_logs (actor_platform_admin_id, action, target_type, target_id, outcome, request_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6, '{}'::jsonb)
`

type InsertPlatformAuditLogParams struct {
	ActorPlatformAdminID pgtype.Int8 `json:"actor_platform_admin_id"`
	Action               string      `json:"action"`
	TargetType           string      `json:"target_type"`
	TargetID             pgtype.Int8 `json:"target_id"`
	Outcome              string      `json:"outcome"`
	RequestID            pgtype.Text `json:"request_id"`
}

func (q *Queries) InsertPlatformAuditLog(ctx context.Context, arg InsertPlatformAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertPlatformAuditLog,
		arg.ActorPlatformAdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Outcome,
		arg.RequestID,
	)
	return err
}

const lockPlatformSessionFamily = `-- name: LockPlatformSessionFamily :one
SELECT id, platform_admin_id, revoked_at FROM platform_session_families
WHERE id = $1 AND platform_admin_id = $2 FOR UPDATE
`

type LockPlatformSessionFamilyParams struct {
	ID              int64 `json:"id"`
	PlatformAdminID int64 `json:"platform_admin_id"`
}

type LockPlatformSessionFamilyRow struct {
	ID              int64              `json:"id"`
	PlatformAdminID int64              `json:"platform_admin_id"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) LockPlatformSessionFamily(ctx context.Context, arg LockPlatformSessionFamilyParams) (LockPlatformSessionFamilyRow, error) {
	row := q.db.QueryRow(ctx, lockPlatformSessionFamily, arg.ID, arg.PlatformAdminID)
	var i LockPlatformSessionFamilyRow
	err := row.Scan(&i.ID, &i.PlatformAdminID, &i.RevokedAt)
	return i, err
}

const revokePlatformRefreshToken = `-- name: RevokePlatformRefreshToken :execrows
UPDATE platform_refresh_tokens SET revoked_at = now()
WHERE id = $1 AND platform_admin_id = $2 AND revoked_at IS NULL
`

type RevokePlatformRefreshTokenParams struct {
	ID              int64 `json:"id"`
	PlatformAdminID int64 `json:"platform_admin_id"`
}

func (q *Queries) RevokePlatformRefreshToken(ctx context.Context, arg RevokePlatformRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePlatformRefreshToken, arg.ID, arg.PlatformAdminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePlatformSessionFamily = `-- name: RevokePlatformSessionFamily :execrows
UPDATE platform_session_families SET revoked_at = now()
WHERE id = $1 AND platform_admin_id = $2 AND revoked_at IS NULL
`

type RevokePlatformSessionFamilyParams struct {
	ID              int64 `json:"id"`
	PlatformAdminID int64 `json:"platform_admin_id"`
}

func (q *Queries) RevokePlatformSessionFamily(ctx context.Context, arg RevokePlatformSessionFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePlatformSessionFamily, arg.ID, arg.PlatformAdminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
