// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresql

import (
	"context"
)

type Querier interface {
	CheckDatabaseHealth(ctx context.Context) (int32, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error)
	GetActiveRefreshSession(ctx context.Context, arg GetActiveRefreshSessionParams) (GetActiveRefreshSessionRow, error)
	GetActiveUser(ctx context.Context, arg GetActiveUserParams) (GetActiveUserRow, error)
	GetRefreshTokenForUpdate(ctx context.Context, tokenHash string) (GetRefreshTokenForUpdateRow, error)
	GetUserForLogin(ctx context.Context, lower string) (GetUserForLoginRow, error)
	ListUserOutletIDs(ctx context.Context, arg ListUserOutletIDsParams) ([]int64, error)
	ListUserPermissionCodes(ctx context.Context, arg ListUserPermissionCodesParams) ([]string, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
