// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipts.sql

package postgresql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearActiveDefaultReceiptTemplates = `-- name: ClearActiveDefaultReceiptTemplates :exec
UPDATE receipt_templates SET is_default=FALSE, updated_at=now()
WHERE business_id=$1 AND outlet_id=$2
  AND is_default AND deleted_at IS NULL
`

type ClearActiveDefaultReceiptTemplatesParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
}

func (q *Queries) ClearActiveDefaultReceiptTemplates(ctx context.Context, arg ClearActiveDefaultReceiptTemplatesParams) error {
	_, err := q.db.Exec(ctx, clearActiveDefaultReceiptTemplates, arg.BusinessID, arg.OutletID)
	return err
}

const createReceiptTemplate = `-- name: CreateReceiptTemplate :one
INSERT INTO receipt_templates (
    business_id,outlet_id,name,header_text,footer_text,
    whatsapp_message_template,paper_width_mm,is_default
)
VALUES (
    $1,$2,$3,$4,$5,
    $6,$7,$8
)
RETURNING id,business_id,outlet_id,name,header_text,footer_text,
          whatsapp_message_template,paper_width_mm,is_default,created_at,updated_at
`

type CreateReceiptTemplateParams struct {
	BusinessID              int64       `json:"business_id"`
	OutletID                int64       `json:"outlet_id"`
	Name                    string      `json:"name"`
	HeaderText              pgtype.Text `json:"header_text"`
	FooterText              pgtype.Text `json:"footer_text"`
	WhatsappMessageTemplate pgtype.Text `json:"whatsapp_message_template"`
	PaperWidthMm            int32       `json:"paper_width_mm"`
	IsDefault               bool        `json:"is_default"`
}

type CreateReceiptTemplateRow struct {
	ID                      int64              `json:"id"`
	BusinessID              int64              `json:"business_id"`
	OutletID                int64              `json:"outlet_id"`
	Name                    string             `json:"name"`
	HeaderText              pgtype.Text        `json:"header_text"`
	FooterText              pgtype.Text        `json:"footer_text"`
	WhatsappMessageTemplate pgtype.Text        `json:"whatsapp_message_template"`
	PaperWidthMm            int32              `json:"paper_width_mm"`
	IsDefault               bool               `json:"is_default"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateReceiptTemplate(ctx context.Context, arg CreateReceiptTemplateParams) (CreateReceiptTemplateRow, error) {
	row := q.db.QueryRow(ctx, createReceiptTemplate,
		arg.BusinessID,
		arg.OutletID,
		arg.Name,
		arg.HeaderText,
		arg.FooterText,
		arg.WhatsappMessageTemplate,
		arg.PaperWidthMm,
		arg.IsDefault,
	)
	var i CreateReceiptTemplateRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.Name,
		&i.HeaderText,
		&i.FooterText,
		&i.WhatsappMessageTemplate,
		&i.PaperWidthMm,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthorizedReceiptOrder = `-- name: GetAuthorizedReceiptOrder :one
SELECT o.id, o.business_id, o.outlet_id, o.customer_id, o.invoice_number,
       o.status, o.payment_status, o.total_amount, o.received_at, o.due_at,
       o.customer_name_snapshot, o.customer_phone_snapshot, o.receipt_qr_id,
       outlet.code AS outlet_code, outlet.name AS outlet_name,
       outlet.phone AS outlet_phone, outlet.address AS outlet_address,
       template.id AS receipt_template_id, template.name AS receipt_template_name,
       template.header_text AS receipt_header_text, template.footer_text AS receipt_footer_text,
       template.whatsapp_message_template, template.paper_width_mm
FROM orders o
JOIN outlets outlet ON outlet.business_id=o.business_id AND outlet.id=o.outlet_id AND outlet.is_active
JOIN businesses b ON b.id=o.business_id AND b.is_active
JOIN users actor ON actor.business_id=o.business_id AND actor.id=$1
    AND actor.is_active
    AND actor.role=CASE WHEN $2::boolean THEN 'ADMIN' ELSE 'LAUNDRY_STAFF' END
LEFT JOIN receipt_templates template ON template.business_id=o.business_id
    AND template.outlet_id=o.outlet_id AND template.is_default AND template.deleted_at IS NULL
WHERE o.business_id=$3
  AND ($4::bigint IS NULL OR o.outlet_id=$4::bigint)
  AND (
      ($5::bigint IS NOT NULL AND o.id=$5::bigint)
      OR ($6::text IS NOT NULL AND o.receipt_qr_id=$6::text)
  )
  AND ($2::boolean OR EXISTS (
      SELECT 1 FROM user_outlets assignment
      WHERE assignment.business_id=o.business_id
        AND assignment.outlet_id=o.outlet_id
        AND assignment.user_id=actor.id
  ))
`

type GetAuthorizedReceiptOrderParams struct {
	UserID     int64       `json:"user_id"`
	IsAdmin    bool        `json:"is_admin"`
	BusinessID int64       `json:"business_id"`
	OutletID   pgtype.Int8 `json:"outlet_id"`
	OrderID    pgtype.Int8 `json:"order_id"`
	QrID       pgtype.Text `json:"qr_id"`
}

type GetAuthorizedReceiptOrderRow struct {
	ID                      int64              `json:"id"`
	BusinessID              int64              `json:"business_id"`
	OutletID                int64              `json:"outlet_id"`
	CustomerID              int64              `json:"customer_id"`
	InvoiceNumber           string             `json:"invoice_number"`
	Status                  string             `json:"status"`
	PaymentStatus           string             `json:"payment_status"`
	TotalAmount             int64              `json:"total_amount"`
	ReceivedAt              pgtype.Timestamptz `json:"received_at"`
	DueAt                   pgtype.Timestamptz `json:"due_at"`
	CustomerNameSnapshot    string             `json:"customer_name_snapshot"`
	CustomerPhoneSnapshot   pgtype.Text        `json:"customer_phone_snapshot"`
	ReceiptQrID             string             `json:"receipt_qr_id"`
	OutletCode              string             `json:"outlet_code"`
	OutletName              string             `json:"outlet_name"`
	OutletPhone             pgtype.Text        `json:"outlet_phone"`
	OutletAddress           pgtype.Text        `json:"outlet_address"`
	ReceiptTemplateID       pgtype.Int8        `json:"receipt_template_id"`
	ReceiptTemplateName     pgtype.Text        `json:"receipt_template_name"`
	ReceiptHeaderText       pgtype.Text        `json:"receipt_header_text"`
	ReceiptFooterText       pgtype.Text        `json:"receipt_footer_text"`
	WhatsappMessageTemplate pgtype.Text        `json:"whatsapp_message_template"`
	PaperWidthMm            pgtype.Int4        `json:"paper_width_mm"`
}

func (q *Queries) GetAuthorizedReceiptOrder(ctx context.Context, arg GetAuthorizedReceiptOrderParams) (GetAuthorizedReceiptOrderRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizedReceiptOrder,
		arg.UserID,
		arg.IsAdmin,
		arg.BusinessID,
		arg.OutletID,
		arg.OrderID,
		arg.QrID,
	)
	var i GetAuthorizedReceiptOrderRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.CustomerID,
		&i.InvoiceNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.ReceivedAt,
		&i.DueAt,
		&i.CustomerNameSnapshot,
		&i.CustomerPhoneSnapshot,
		&i.ReceiptQrID,
		&i.OutletCode,
		&i.OutletName,
		&i.OutletPhone,
		&i.OutletAddress,
		&i.ReceiptTemplateID,
		&i.ReceiptTemplateName,
		&i.ReceiptHeaderText,
		&i.ReceiptFooterText,
		&i.WhatsappMessageTemplate,
		&i.PaperWidthMm,
	)
	return i, err
}

const getAuthorizedReceiptOutlet = `-- name: GetAuthorizedReceiptOutlet :one
SELECT outlet.id
FROM outlets outlet
JOIN businesses b ON b.id=outlet.business_id AND b.is_active
JOIN users actor ON actor.business_id=outlet.business_id AND actor.id=$1
    AND actor.is_active
    AND actor.role=CASE WHEN $2::boolean THEN 'ADMIN' ELSE 'LAUNDRY_STAFF' END
WHERE outlet.business_id=$3 AND outlet.id=$4
  AND outlet.is_active
  AND ($2::boolean OR EXISTS (
      SELECT 1 FROM user_outlets assignment
      WHERE assignment.business_id=outlet.business_id
        AND assignment.outlet_id=outlet.id AND assignment.user_id=actor.id
  ))
`

type GetAuthorizedReceiptOutletParams struct {
	UserID     int64 `json:"user_id"`
	IsAdmin    bool  `json:"is_admin"`
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
}

func (q *Queries) GetAuthorizedReceiptOutlet(ctx context.Context, arg GetAuthorizedReceiptOutletParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAuthorizedReceiptOutlet,
		arg.UserID,
		arg.IsAdmin,
		arg.BusinessID,
		arg.OutletID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getReceiptConfirmedPaymentTotal = `-- name: GetReceiptConfirmedPaymentTotal :one
SELECT coalesce(sum(amount),0)::bigint
FROM payments
WHERE business_id=$1 AND outlet_id=$2
  AND order_id=$3 AND status='CONFIRMED'
`

type GetReceiptConfirmedPaymentTotalParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	OrderID    int64 `json:"order_id"`
}

func (q *Queries) GetReceiptConfirmedPaymentTotal(ctx context.Context, arg GetReceiptConfirmedPaymentTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, getReceiptConfirmedPaymentTotal, arg.BusinessID, arg.OutletID, arg.OrderID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getReceiptTemplateForUpdate = `-- name: GetReceiptTemplateForUpdate :one
SELECT id, business_id, outlet_id, name, header_text, footer_text,
       whatsapp_message_template, paper_width_mm, is_default, created_at, updated_at
FROM receipt_templates
WHERE business_id=$1 AND outlet_id=$2
  AND id=$3 AND deleted_at IS NULL
FOR UPDATE
`

type GetReceiptTemplateForUpdateParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	TemplateID int64 `json:"template_id"`
}

type GetReceiptTemplateForUpdateRow struct {
	ID                      int64              `json:"id"`
	BusinessID              int64              `json:"business_id"`
	OutletID                int64              `json:"outlet_id"`
	Name                    string             `json:"name"`
	HeaderText              pgtype.Text        `json:"header_text"`
	FooterText              pgtype.Text        `json:"footer_text"`
	WhatsappMessageTemplate pgtype.Text        `json:"whatsapp_message_template"`
	PaperWidthMm            int32              `json:"paper_width_mm"`
	IsDefault               bool               `json:"is_default"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetReceiptTemplateForUpdate(ctx context.Context, arg GetReceiptTemplateForUpdateParams) (GetReceiptTemplateForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getReceiptTemplateForUpdate, arg.BusinessID, arg.OutletID, arg.TemplateID)
	var i GetReceiptTemplateForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.Name,
		&i.HeaderText,
		&i.FooterText,
		&i.WhatsappMessageTemplate,
		&i.PaperWidthMm,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveDefaultReceiptTemplate = `-- name: HasActiveDefaultReceiptTemplate :one
SELECT EXISTS (
    SELECT 1 FROM receipt_templates
    WHERE business_id=$1 AND outlet_id=$2
      AND is_default AND deleted_at IS NULL
)
`

type HasActiveDefaultReceiptTemplateParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
}

func (q *Queries) HasActiveDefaultReceiptTemplate(ctx context.Context, arg HasActiveDefaultReceiptTemplateParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveDefaultReceiptTemplate, arg.BusinessID, arg.OutletID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertReceiptTemplateAuditLog = `-- name: InsertReceiptTemplateAuditLog :exec
INSERT INTO audit_logs (business_id,outlet_id,actor_user_id,action,entity_type,entity_id,
                        old_values,new_values,ip_address,user_agent)
VALUES ($1,$2,$3,$4,
        'receipt_template',$5,$6,$7,
        $8,$9)
`

type InsertReceiptTemplateAuditLogParams struct {
	BusinessID  int64       `json:"business_id"`
	OutletID    pgtype.Int8 `json:"outlet_id"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	TemplateID  pgtype.Int8 `json:"template_id"`
	OldValues   []byte      `json:"old_values"`
	NewValues   []byte      `json:"new_values"`
	IpAddress   *netip.Addr `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertReceiptTemplateAuditLog(ctx context.Context, arg InsertReceiptTemplateAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertReceiptTemplateAuditLog,
		arg.BusinessID,
		arg.OutletID,
		arg.ActorUserID,
		arg.Action,
		arg.TemplateID,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const listReceiptTemplates = `-- name: ListReceiptTemplates :many
SELECT id, business_id, outlet_id, name, header_text, footer_text,
       whatsapp_message_template, paper_width_mm, is_default, created_at, updated_at
FROM receipt_templates
WHERE business_id=$1 AND outlet_id=$2
  AND deleted_at IS NULL
ORDER BY is_default DESC, lower(name), id
`

type ListReceiptTemplatesParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
}

type ListReceiptTemplatesRow struct {
	ID                      int64              `json:"id"`
	BusinessID              int64              `json:"business_id"`
	OutletID                int64              `json:"outlet_id"`
	Name                    string             `json:"name"`
	HeaderText              pgtype.Text        `json:"header_text"`
	FooterText              pgtype.Text        `json:"footer_text"`
	WhatsappMessageTemplate pgtype.Text        `json:"whatsapp_message_template"`
	PaperWidthMm            int32              `json:"paper_width_mm"`
	IsDefault               bool               `json:"is_default"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListReceiptTemplates(ctx context.Context, arg ListReceiptTemplatesParams) ([]ListReceiptTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listReceiptTemplates, arg.BusinessID, arg.OutletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceiptTemplatesRow
	for rows.Next() {
		var i ListReceiptTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.OutletID,
			&i.Name,
			&i.HeaderText,
			&i.FooterText,
			&i.WhatsappMessageTemplate,
			&i.PaperWidthMm,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReceiptTemplateOutlet = `-- name: LockReceiptTemplateOutlet :one
SELECT outlet.id
FROM outlets outlet
JOIN businesses b ON b.id=outlet.business_id AND b.is_active
JOIN users actor ON actor.business_id=outlet.business_id AND actor.id=$1
    AND actor.is_active
    AND actor.role=CASE WHEN $2::boolean THEN 'ADMIN' ELSE 'LAUNDRY_STAFF' END
WHERE outlet.business_id=$3 AND outlet.id=$4
  AND outlet.is_active
  AND ($2::boolean OR EXISTS (
      SELECT 1 FROM user_outlets assignment
      WHERE assignment.business_id=outlet.business_id
        AND assignment.outlet_id=outlet.id AND assignment.user_id=actor.id
  ))
FOR UPDATE OF outlet
`

type LockReceiptTemplateOutletParams struct {
	UserID     int64 `json:"user_id"`
	IsAdmin    bool  `json:"is_admin"`
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
}

func (q *Queries) LockReceiptTemplateOutlet(ctx context.Context, arg LockReceiptTemplateOutletParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockReceiptTemplateOutlet,
		arg.UserID,
		arg.IsAdmin,
		arg.BusinessID,
		arg.OutletID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setNextReceiptTemplateDefault = `-- name: SetNextReceiptTemplateDefault :exec
WITH candidate AS (
    SELECT template.id FROM receipt_templates template
    WHERE template.business_id=$1 AND template.outlet_id=$2
      AND template.id<>$3 AND template.deleted_at IS NULL
    ORDER BY template.id LIMIT 1
)
UPDATE receipt_templates target SET is_default=TRUE,updated_at=now()
FROM candidate
WHERE target.business_id=$1 AND target.outlet_id=$2
  AND target.id=candidate.id
`

type SetNextReceiptTemplateDefaultParams struct {
	BusinessID        int64 `json:"business_id"`
	OutletID          int64 `json:"outlet_id"`
	ExcludeTemplateID int64 `json:"exclude_template_id"`
}

func (q *Queries) SetNextReceiptTemplateDefault(ctx context.Context, arg SetNextReceiptTemplateDefaultParams) error {
	_, err := q.db.Exec(ctx, setNextReceiptTemplateDefault, arg.BusinessID, arg.OutletID, arg.ExcludeTemplateID)
	return err
}

const softDeleteReceiptTemplate = `-- name: SoftDeleteReceiptTemplate :one
UPDATE receipt_templates SET deleted_at=now(),is_default=FALSE,updated_at=now()
WHERE business_id=$1 AND outlet_id=$2
  AND id=$3 AND deleted_at IS NULL
RETURNING id,business_id,outlet_id,name,header_text,footer_text,
          whatsapp_message_template,paper_width_mm,is_default,created_at,updated_at
`

type SoftDeleteReceiptTemplateParams struct {
	BusinessID int64 `json:"business_id"`
	OutletID   int64 `json:"outlet_id"`
	TemplateID int64 `json:"template_id"`
}

type SoftDeleteReceiptTemplateRow struct {
	ID                      int64              `json:"id"`
	BusinessID              int64              `json:"business_id"`
	OutletID                int64              `json:"outlet_id"`
	Name                    string             `json:"name"`
	HeaderText              pgtype.Text        `json:"header_text"`
	FooterText              pgtype.Text        `json:"footer_text"`
	WhatsappMessageTemplate pgtype.Text        `json:"whatsapp_message_template"`
	PaperWidthMm            int32              `json:"paper_width_mm"`
	IsDefault               bool               `json:"is_default"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SoftDeleteReceiptTemplate(ctx context.Context, arg SoftDeleteReceiptTemplateParams) (SoftDeleteReceiptTemplateRow, error) {
	row := q.db.QueryRow(ctx, softDeleteReceiptTemplate, arg.BusinessID, arg.OutletID, arg.TemplateID)
	var i SoftDeleteReceiptTemplateRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.Name,
		&i.HeaderText,
		&i.FooterText,
		&i.WhatsappMessageTemplate,
		&i.PaperWidthMm,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReceiptTemplate = `-- name: UpdateReceiptTemplate :one
UPDATE receipt_templates SET
    name=$1, header_text=$2, footer_text=$3,
    whatsapp_message_template=$4,
    paper_width_mm=$5, is_default=$6, updated_at=now()
WHERE business_id=$7 AND outlet_id=$8
  AND id=$9 AND deleted_at IS NULL
RETURNING id,business_id,outlet_id,name,header_text,footer_text,
          whatsapp_message_template,paper_width_mm,is_default,created_at,updated_at
`

type UpdateReceiptTemplateParams struct {
	Name                    string      `json:"name"`
	HeaderText              pgtype.Text `json:"header_text"`
	FooterText              pgtype.Text `json:"footer_text"`
	WhatsappMessageTemplate pgtype.Text `json:"whatsapp_message_template"`
	PaperWidthMm            int32       `json:"paper_width_mm"`
	IsDefault               bool        `json:"is_default"`
	BusinessID              int64       `json:"business_id"`
	OutletID                int64       `json:"outlet_id"`
	TemplateID              int64       `json:"template_id"`
}

type UpdateReceiptTemplateRow struct {
	ID                      int64              `json:"id"`
	BusinessID              int64              `json:"business_id"`
	OutletID                int64              `json:"outlet_id"`
	Name                    string             `json:"name"`
	HeaderText              pgtype.Text        `json:"header_text"`
	FooterText              pgtype.Text        `json:"footer_text"`
	WhatsappMessageTemplate pgtype.Text        `json:"whatsapp_message_template"`
	PaperWidthMm            int32              `json:"paper_width_mm"`
	IsDefault               bool               `json:"is_default"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateReceiptTemplate(ctx context.Context, arg UpdateReceiptTemplateParams) (UpdateReceiptTemplateRow, error) {
	row := q.db.QueryRow(ctx, updateReceiptTemplate,
		arg.Name,
		arg.HeaderText,
		arg.FooterText,
		arg.WhatsappMessageTemplate,
		arg.PaperWidthMm,
		arg.IsDefault,
		arg.BusinessID,
		arg.OutletID,
		arg.TemplateID,
	)
	var i UpdateReceiptTemplateRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OutletID,
		&i.Name,
		&i.HeaderText,
		&i.FooterText,
		&i.WhatsappMessageTemplate,
		&i.PaperWidthMm,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
