// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOutletReport = `-- name: GetOutletReport :one
WITH outlet_scope AS MATERIALIZED (
    SELECT b.timezone
    FROM outlets o
    JOIN businesses b ON b.id=o.business_id AND b.is_active
    JOIN users actor ON actor.business_id=o.business_id
        AND actor.id=$1 AND actor.is_active
        AND actor.role=CASE WHEN $2::boolean THEN 'ADMIN' ELSE 'LAUNDRY_STAFF' END
    WHERE o.business_id=$3
      AND o.id=$4
      AND o.is_active
      AND ($2::boolean OR EXISTS (
          SELECT 1 FROM user_outlets assignment
          WHERE assignment.business_id=o.business_id
            AND assignment.outlet_id=o.id
            AND assignment.user_id=actor.id
      ))
), report_range AS MATERIALIZED (
    SELECT s.timezone,
           $5::date AS from_date,
           $6::date AS to_date,
           $5::timestamp AT TIME ZONE s.timezone AS start_at,
           ($6::date + 1)::timestamp AT TIME ZONE s.timezone AS end_at
    FROM outlet_scope s
), calendar AS (
    SELECT g::date AS report_date
    FROM report_range r
    CROSS JOIN LATERAL generate_series(r.from_date::timestamp, r.to_date::timestamp, interval '1 day') g
), income_daily AS (
    SELECT (p.confirmed_at AT TIME ZONE r.timezone)::date AS report_date,
           count(*)::bigint AS payment_count,
           sum(p.amount)::numeric AS received_amount
    FROM payments p
    CROSS JOIN report_range r
    WHERE p.business_id=$3
      AND p.outlet_id=$4
      AND p.status='CONFIRMED'
      AND p.confirmed_at >= r.start_at AND p.confirmed_at < r.end_at
    GROUP BY 1
), income_methods AS (
    SELECT p.method, count(*)::bigint AS payment_count, sum(p.amount)::numeric AS received_amount
    FROM payments p
    CROSS JOIN report_range r
    WHERE p.business_id=$3
      AND p.outlet_id=$4
      AND p.status='CONFIRMED'
      AND p.confirmed_at >= r.start_at AND p.confirmed_at < r.end_at
    GROUP BY p.method
), expense_daily AS (
    SELECT (e.expense_at AT TIME ZONE r.timezone)::date AS report_date,
           count(*)::bigint AS expense_count,
           sum(e.amount)::numeric AS expense_amount
    FROM expenses e
    CROSS JOIN report_range r
    WHERE e.business_id=$3
      AND e.outlet_id=$4
      AND e.expense_at >= r.start_at AND e.expense_at < r.end_at
    GROUP BY 1
), payments_by_order AS MATERIALIZED (
    SELECT p.business_id, p.outlet_id, p.order_id, sum(p.amount)::numeric AS collected_amount
    FROM payments p
    WHERE p.business_id=$3
      AND p.outlet_id=$4
      AND p.status='CONFIRMED'
    GROUP BY p.business_id, p.outlet_id, p.order_id
), order_cohort AS (
    SELECT o.id, o.customer_id, o.status, o.total_amount::numeric AS order_value,
           (o.received_at AT TIME ZONE r.timezone)::date AS report_date,
           coalesce(p.collected_amount, 0)::numeric AS collected_amount,
           CASE WHEN o.status <> 'CANCELLED'
                THEN greatest(o.total_amount::numeric - coalesce(p.collected_amount, 0), 0)
                ELSE 0::numeric END AS outstanding_amount
    FROM orders o
    CROSS JOIN report_range r
    LEFT JOIN payments_by_order p
      ON p.business_id=o.business_id AND p.outlet_id=o.outlet_id AND p.order_id=o.id
    WHERE o.business_id=$3
      AND o.outlet_id=$4
      AND o.received_at >= r.start_at AND o.received_at < r.end_at
), orders_daily AS (
    SELECT report_date, count(*)::bigint AS order_count,
           sum(order_value)::numeric AS order_value_amount,
           sum(collected_amount)::numeric AS collected_amount,
           sum(outstanding_amount)::numeric AS outstanding_balance_amount,
           count(*) FILTER (WHERE status='CANCELLED')::bigint AS cancelled_count,
           coalesce(sum(order_value) FILTER (WHERE status='CANCELLED'),0)::numeric AS cancelled_order_value_amount
    FROM order_cohort GROUP BY report_date
), cancellation_daily AS (
    SELECT (o.cancelled_at AT TIME ZONE r.timezone)::date AS report_date,
           count(*)::bigint AS cancellation_count,
           sum(o.total_amount)::numeric AS cancelled_order_value_amount
    FROM orders o
    CROSS JOIN report_range r
    WHERE o.business_id=$3
      AND o.outlet_id=$4
      AND o.status='CANCELLED'
      AND o.cancelled_at >= r.start_at AND o.cancelled_at < r.end_at
    GROUP BY 1
), customer_rank AS (
    SELECT c.id AS customer_id, c.name,
           count(*)::bigint AS order_count,
           sum(o.order_value)::numeric AS order_value_amount
    FROM order_cohort o
    JOIN customers c ON c.business_id=$3 AND c.id=o.customer_id
    GROUP BY c.id, c.name
), customer_top AS (
    SELECT customer_id, name, order_count, order_value_amount,
           row_number() OVER (ORDER BY order_count DESC, order_value_amount DESC, lower(name), customer_id) AS rank
    FROM customer_rank
), report_payload AS (
    SELECT CASE $7::text
      WHEN 'income' THEN (
        SELECT jsonb_build_object(
          'summary', jsonb_build_object('payment_count', coalesce(sum(payment_count),0), 'received_amount', coalesce(sum(received_amount),0)),
          'daily', coalesce((SELECT jsonb_agg(jsonb_build_object('date',c.report_date,'payment_count',coalesce(i.payment_count,0),'received_amount',coalesce(i.received_amount,0)) ORDER BY c.report_date) FROM calendar c LEFT JOIN income_daily i USING(report_date)), '[]'::jsonb),
          'by_method', coalesce((SELECT jsonb_agg(jsonb_build_object('method',method,'payment_count',payment_count,'received_amount',received_amount) ORDER BY method) FROM income_methods), '[]'::jsonb))
        FROM income_daily
      )
      WHEN 'expenses' THEN (
        SELECT jsonb_build_object(
          'summary', jsonb_build_object('expense_count', coalesce(sum(expense_count),0), 'expense_amount', coalesce(sum(expense_amount),0)),
          'daily', coalesce((SELECT jsonb_agg(jsonb_build_object('date',c.report_date,'expense_count',coalesce(e.expense_count,0),'expense_amount',coalesce(e.expense_amount,0)) ORDER BY c.report_date) FROM calendar c LEFT JOIN expense_daily e USING(report_date)), '[]'::jsonb))
        FROM expense_daily
      )
      WHEN 'profit-loss' THEN (
        SELECT jsonb_build_object(
          'summary', jsonb_build_object('received_amount',coalesce(sum(coalesce(i.received_amount,0)),0),'expense_amount',coalesce(sum(coalesce(e.expense_amount,0)),0),'profit_loss_amount',coalesce(sum(coalesce(i.received_amount,0)-coalesce(e.expense_amount,0)),0)),
          'daily', coalesce(jsonb_agg(jsonb_build_object('date',c.report_date,'received_amount',coalesce(i.received_amount,0),'expense_amount',coalesce(e.expense_amount,0),'profit_loss_amount',coalesce(i.received_amount,0)-coalesce(e.expense_amount,0)) ORDER BY c.report_date),'[]'::jsonb))
        FROM calendar c LEFT JOIN income_daily i USING(report_date) LEFT JOIN expense_daily e USING(report_date)
      )
      WHEN 'orders' THEN (
        SELECT jsonb_build_object(
          'summary', jsonb_build_object('order_count',coalesce(sum(order_count),0),'order_value_amount',coalesce(sum(order_value_amount),0),'collected_amount',coalesce(sum(collected_amount),0),'outstanding_balance_amount',coalesce(sum(outstanding_balance_amount),0),'cancelled_count',coalesce(sum(cancelled_count),0),'cancelled_order_value_amount',coalesce(sum(cancelled_order_value_amount),0)),
          'daily', coalesce((SELECT jsonb_agg(jsonb_build_object('date',c.report_date,'order_count',coalesce(o.order_count,0),'order_value_amount',coalesce(o.order_value_amount,0),'collected_amount',coalesce(o.collected_amount,0),'outstanding_balance_amount',coalesce(o.outstanding_balance_amount,0),'cancelled_count',coalesce(o.cancelled_count,0),'cancelled_order_value_amount',coalesce(o.cancelled_order_value_amount,0)) ORDER BY c.report_date) FROM calendar c LEFT JOIN orders_daily o USING(report_date)),'[]'::jsonb))
        FROM orders_daily
      )
      WHEN 'cancellations' THEN (
        SELECT jsonb_build_object(
          'summary', jsonb_build_object('cancellation_count',coalesce(sum(cancellation_count),0),'cancelled_order_value_amount',coalesce(sum(cancelled_order_value_amount),0)),
          'daily', coalesce((SELECT jsonb_agg(jsonb_build_object('date',c.report_date,'cancellation_count',coalesce(x.cancellation_count,0),'cancelled_order_value_amount',coalesce(x.cancelled_order_value_amount,0)) ORDER BY c.report_date) FROM calendar c LEFT JOIN cancellation_daily x USING(report_date)),'[]'::jsonb))
        FROM cancellation_daily
      )
      WHEN 'customers' THEN (
        SELECT jsonb_build_object(
          'summary', jsonb_build_object('distinct_customer_count',count(*)::bigint),
          'top_customers', coalesce((SELECT jsonb_agg(jsonb_build_object('customer_id',customer_id,'name',name,'order_count',order_count,'order_value_amount',order_value_amount) ORDER BY rank) FROM customer_top WHERE rank <= 10),'[]'::jsonb))
        FROM customer_rank
      )
      ELSE NULL
    END AS payload
)
SELECT jsonb_build_object(
    'from_date', r.from_date, 'to_date', r.to_date, 'timezone', r.timezone,
    'summary', coalesce(p.payload->'summary','{}'::jsonb),
    'daily', coalesce(p.payload->'daily','[]'::jsonb),
    'by_method', coalesce(p.payload->'by_method','[]'::jsonb),
    'top_customers', coalesce(p.payload->'top_customers','[]'::jsonb)
) AS report
FROM report_range r CROSS JOIN report_payload p
`

type GetOutletReportParams struct {
	UserID     int64       `json:"user_id"`
	IsAdmin    bool        `json:"is_admin"`
	BusinessID int64       `json:"business_id"`
	OutletID   int64       `json:"outlet_id"`
	DateFrom   pgtype.Date `json:"date_from"`
	DateTo     pgtype.Date `json:"date_to"`
	ReportType string      `json:"report_type"`
}

func (q *Queries) GetOutletReport(ctx context.Context, arg GetOutletReportParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOutletReport,
		arg.UserID,
		arg.IsAdmin,
		arg.BusinessID,
		arg.OutletID,
		arg.DateFrom,
		arg.DateTo,
		arg.ReportType,
	)
	var report []byte
	err := row.Scan(&report)
	return report, err
}
