// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countServices = `-- name: CountServices :one
SELECT count(*)
FROM services
WHERE business_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%'
       OR COALESCE(description, '') ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR unit = $3::text)
  AND ($4::boolean IS NULL OR is_active = $4::boolean)
`

type CountServicesParams struct {
	BusinessID int64       `json:"business_id"`
	Search     string      `json:"search"`
	Unit       pgtype.Text `json:"unit"`
	IsActive   pgtype.Bool `json:"is_active"`
}

func (q *Queries) CountServices(ctx context.Context, arg CountServicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countServices,
		arg.BusinessID,
		arg.Search,
		arg.Unit,
		arg.IsActive,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (business_id, name, description, unit, unit_price_amount, estimated_duration_minutes)
VALUES ($1, $2, $3, $4,
        $5, $6)
RETURNING id, business_id, name, description, unit, unit_price_amount,
          estimated_duration_minutes, is_active, created_at, updated_at
`

type CreateServiceParams struct {
	BusinessID               int64       `json:"business_id"`
	Name                     string      `json:"name"`
	Description              pgtype.Text `json:"description"`
	Unit                     string      `json:"unit"`
	UnitPriceAmount          int64       `json:"unit_price_amount"`
	EstimatedDurationMinutes int32       `json:"estimated_duration_minutes"`
}

type CreateServiceRow struct {
	ID                       int64              `json:"id"`
	BusinessID               int64              `json:"business_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	Unit                     string             `json:"unit"`
	UnitPriceAmount          int64              `json:"unit_price_amount"`
	EstimatedDurationMinutes int32              `json:"estimated_duration_minutes"`
	IsActive                 bool               `json:"is_active"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (CreateServiceRow, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.BusinessID,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.UnitPriceAmount,
		arg.EstimatedDurationMinutes,
	)
	var i CreateServiceRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.UnitPriceAmount,
		&i.EstimatedDurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getService = `-- name: GetService :one
SELECT id, business_id, name, description, unit, unit_price_amount,
       estimated_duration_minutes, is_active, created_at, updated_at
FROM services
WHERE business_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetServiceParams struct {
	BusinessID int64 `json:"business_id"`
	ServiceID  int64 `json:"service_id"`
}

type GetServiceRow struct {
	ID                       int64              `json:"id"`
	BusinessID               int64              `json:"business_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	Unit                     string             `json:"unit"`
	UnitPriceAmount          int64              `json:"unit_price_amount"`
	EstimatedDurationMinutes int32              `json:"estimated_duration_minutes"`
	IsActive                 bool               `json:"is_active"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetService(ctx context.Context, arg GetServiceParams) (GetServiceRow, error) {
	row := q.db.QueryRow(ctx, getService, arg.BusinessID, arg.ServiceID)
	var i GetServiceRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.UnitPriceAmount,
		&i.EstimatedDurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceForUpdate = `-- name: GetServiceForUpdate :one
SELECT id, business_id, name, description, unit, unit_price_amount,
       estimated_duration_minutes, is_active, created_at, updated_at
FROM services
WHERE business_id = $1 AND id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type GetServiceForUpdateParams struct {
	BusinessID int64 `json:"business_id"`
	ServiceID  int64 `json:"service_id"`
}

type GetServiceForUpdateRow struct {
	ID                       int64              `json:"id"`
	BusinessID               int64              `json:"business_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	Unit                     string             `json:"unit"`
	UnitPriceAmount          int64              `json:"unit_price_amount"`
	EstimatedDurationMinutes int32              `json:"estimated_duration_minutes"`
	IsActive                 bool               `json:"is_active"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetServiceForUpdate(ctx context.Context, arg GetServiceForUpdateParams) (GetServiceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getServiceForUpdate, arg.BusinessID, arg.ServiceID)
	var i GetServiceForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.UnitPriceAmount,
		&i.EstimatedDurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, business_id, name, description, unit, unit_price_amount,
       estimated_duration_minutes, is_active, created_at, updated_at
FROM services
WHERE business_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%'
       OR COALESCE(description, '') ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR unit = $3::text)
  AND ($4::boolean IS NULL OR is_active = $4::boolean)
ORDER BY lower(name), unit, id
LIMIT $6 OFFSET $5
`

type ListServicesParams struct {
	BusinessID int64       `json:"business_id"`
	Search     string      `json:"search"`
	Unit       pgtype.Text `json:"unit"`
	IsActive   pgtype.Bool `json:"is_active"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListServicesRow struct {
	ID                       int64              `json:"id"`
	BusinessID               int64              `json:"business_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	Unit                     string             `json:"unit"`
	UnitPriceAmount          int64              `json:"unit_price_amount"`
	EstimatedDurationMinutes int32              `json:"estimated_duration_minutes"`
	IsActive                 bool               `json:"is_active"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices,
		arg.BusinessID,
		arg.Search,
		arg.Unit,
		arg.IsActive,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesRow
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.UnitPriceAmount,
			&i.EstimatedDurationMinutes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteService = `-- name: SoftDeleteService :one
UPDATE services
SET is_active = FALSE, deleted_at = now(), updated_at = now()
WHERE business_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteServiceParams struct {
	BusinessID int64 `json:"business_id"`
	ServiceID  int64 `json:"service_id"`
}

func (q *Queries) SoftDeleteService(ctx context.Context, arg SoftDeleteServiceParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteService, arg.BusinessID, arg.ServiceID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $1, description = $2, unit = $3,
    unit_price_amount = $4,
    estimated_duration_minutes = $5,
    is_active = $6, updated_at = now()
WHERE business_id = $7 AND id = $8 AND deleted_at IS NULL
RETURNING id, business_id, name, description, unit, unit_price_amount,
          estimated_duration_minutes, is_active, created_at, updated_at
`

type UpdateServiceParams struct {
	Name                     string      `json:"name"`
	Description              pgtype.Text `json:"description"`
	Unit                     string      `json:"unit"`
	UnitPriceAmount          int64       `json:"unit_price_amount"`
	EstimatedDurationMinutes int32       `json:"estimated_duration_minutes"`
	IsActive                 bool        `json:"is_active"`
	BusinessID               int64       `json:"business_id"`
	ServiceID                int64       `json:"service_id"`
}

type UpdateServiceRow struct {
	ID                       int64              `json:"id"`
	BusinessID               int64              `json:"business_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	Unit                     string             `json:"unit"`
	UnitPriceAmount          int64              `json:"unit_price_amount"`
	EstimatedDurationMinutes int32              `json:"estimated_duration_minutes"`
	IsActive                 bool               `json:"is_active"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (UpdateServiceRow, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.UnitPriceAmount,
		arg.EstimatedDurationMinutes,
		arg.IsActive,
		arg.BusinessID,
		arg.ServiceID,
	)
	var i UpdateServiceRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.UnitPriceAmount,
		&i.EstimatedDurationMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
